### ISSUE TITLE
Mach -O linker issue

### ISSUE THREAD

**Issue by poojagaonkar** [AzureAD/azure-activedirectory-library-for-objc#1001]
I have added the library using Cocoapods but facing an issue I have described [here](https://stackoverflow.com/questions/44798241/apple-mach-o-linker-error-adal)
Any help on this?

**Comment by RPangrle** [comment]
This isn't an issue with the library, rather a problem with either how CocoaPods is set up, your project is set up, or both. If you're not sure where to start I would recommend trying to recreate your project and podfile from scratch carefully following the directions on the cocoapods website.
