### ISSUE TITLE
XCode 9 error: Compiling IB documents for earlier than iOS 7 is no longer supported

### ISSUE THREAD

**Issue by nbrandes1** [AzureAD/azure-activedirectory-library-for-objc#1005]
When I try to build the library with XCode 9 I am running into this error:

`/Pods/ADALiOS/ADALiOS/ADALiOS/ADAL_iPad_Storyboard.storyboard:global: error: Compiling IB documents for earlier than iOS 7 is no longer supported. [12]`

Is there any immediate solution, or just wait for an update?

**Comment by MisterPear** [comment]
Why did you close this issue ?
Did you fix it ?

**Comment by pvroosendaal** [comment]
I'm having the same issue.. What's the fix?

**Comment by MichaelMcKinney** [comment]
Same issue, any ideas?

**Comment by pvroosendaal** [comment]
You need to use the ‘ADAL’ pod instead of ‘ADALiOS’
See #1051 for more info.
https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1051

**Comment by anonymoushitec** [comment]
Hi, I met the same issue. 
You just go to storyboard, Interface Builder Document -> choose a version build for.
That fix my issue.
Goodluck!

**Comment by Lakshmipathikv** [comment]
Try changing the Builds for in File Inspector to a higher version then Clean and Build.

See screenshot
![screen shot 2018-01-23 at 1 25 25 pm](https://user-images.githubusercontent.com/4640240/35264009-08cb883c-0041-11e8-8980-654b39f7f4bc.png)

**Comment by henninghall** [comment]
Is it possible to do this automatically for all effected files?

**Comment by acalism** [comment]
For Xcode 9.4, there is no "Interface Builder Document" section, you can edit xib's source code, cut one `<capability name="">` line, and reopen as "Interface Builder XIB Document", and it will automatically insert the cut line and show "Interface Builder Document" section in File Inspector, then you can change its "Builds for" item.

**Comment by fayaj1** [comment]
just change the Deployment Target, it will working fine.

**Comment by ArsalanWahid** [comment]
@fayaj1  Thanks this worked for me

**Comment by bradparks** [comment]
If you cant find any of the above things, do the following:
- In the menu, choose `View | Navigators | Project Navigator`
- In the tab that shows up, probably on the left, click on the root icon, probably the name of your project.
- press `CMD+I`
- Now look at the main toolbar. There's probably a yellow triangle with a white exclamation mark in it. Click on it, and choose "Perform Changes".
- Now choose `Product | Build`. It will hopefully build!
