### ISSUE TITLE
2.5.x Releases

### ISSUE THREAD

**Issue by dtweston** [AzureAD/azure-activedirectory-library-for-objc#1012]
What's going on with the 2.5.x releases? I see branches for 2.5.0 and 2.5.1, but no releases, and the Cocoapods package hasn't been updated either. 

Are these versions waiting for something? (I'd like to upgrade to a newer release so we can at least build with Xcode 9.0)

**Comment by oldalton** [comment]
2.5.1 is currently in testing/verification and we plan to release it after that (tag + cocoapods). If everything goes well, it should be a couple of more weeks. 2.5.0 won't be released that way at all, 2.5.1 is the version you should aim for. Hope it helps.

**Comment by oldalton** [comment]
I'll close this issue, if you have more questions, feel free to reopen it.

**Comment by dtweston** [comment]
Sounds good, thanks for the quick response!
