### ISSUE TITLE
If user changes the local date to a future date, it might cause login failed.

### ISSUE THREAD

**Issue by ddrdjboy** [AzureAD/azure-activedirectory-library-for-objc#1019]
Our developer is using ADAL Lib 2.4.1 and iOS 10.3.2.
 
If a user changes the local date to a future date in the setting of iOS. When we try to login MCC apps, The authenticator app will respond the token pair and an expired date( Actually it's a future date longer than the access token expire time). After the access token expired and the expire date not reached to future date, the user can’t authenticate it properly if we change back the date to the original setting. Seems it will not use refresh token to refresh a new access token anymore before the expiration date and return the expired access token in the cache directory.

Could you please give some suggestions or work around for this issue? 
Thank you very much.

**Comment by RPangrle** [comment]
The user will need to remove their account for the Authenticator and add it back. AAD does not support large clock skews from real time.
