### ISSUE TITLE
Userid is prioritised differently then other ADAL implementations

### ISSUE THREAD

**Issue by bjartebore** [AzureAD/azure-activedirectory-library-for-objc#1020]
I was wondering if there is a reason for the UserId of the UserInformation object to be implemented differently then in the other ADAL implementations (Android, dotnet, cordova). They all base it on UserObjectId with fallback on Subject, but in this implementation you start with upn -> eMail -> subject -> uniqueName -> guestId.

[UserInformation.m](https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/ADAL/src/ADUserInformation.m#L181-L211)

**Comment by oldalton** [comment]
Hi, I believe there're differences in naming.

**In ADAL Objective-C there're two properties:**

```
/* This is the only unique property, as it is used in the key generation for the cache.
 Two ADUserInformation objects are considered the same if this property is the same. Using RequiredDisplayableId
 will validate against this property. */
@property (readonly) NSString* userId;

/*! This property will be the userObjectId if it exists, or the subject if it does not. It is typically a GUID
    and not displayable. Using UniqueId as the ADUserIdentifierType will validate against this property. */
@property (readonly) NSString* uniqueId;
```

userId can be displayable or not, while uniqueId will normally be UserObjectId with fallback on Subject.

**In Android, there're:**

userId - UserObjectId with fallback on Subject, corresponds to uniqueId in Objective-C
displayableId - user's ups, corresponds to userId in Objective-C only if user has a displayable Id

**In .NET there're:**

UniqueId - UserObjectId with fallback on Subject, corresponds to uniqueId in Objective-C
DisplayableId - UPN with fallback on Email, corresponds to userId in Objective-C only if user has a displayable Id

As you can see, there's slight naming differences on each platform with basically the same content. Feel free to reopen this issue if it doesn't answer your question.
