### ISSUE TITLE
ADAL/src/validation folder missing from pod spec 

### ISSUE THREAD

**Issue by jonhocking** [AzureAD/azure-activedirectory-library-for-objc#1033]
Hi All
 
The `/ADAL/src/validation` folder appears to be missing from the included section in the latest `2.5.1` iOS pod spec. This means that I'm unable to compile my project when using ADAL with cocoapods due to import references to `ADAuthorityValidation.h` in both `ADAuthenticationRequest+AcquireToken.m` and `ADAuthenticationRequest.m`

In the meantime I can install ADAL manually but thought I'd raise a ticket as I'd love to get back to using ADAL via cocoapods as soon as possible.

Thanks!
Jon

**Comment by RPangrle** [comment]
You must have some bad state in your cocoapods repo, because this is how we define source files in our podspec:

```
app.source_files = "ADAL/src/**/*.{h,m}"
```

We don't specifiy individual directories, we recursively grab them all, and I can't repro your issue locally.
