### ISSUE TITLE
Framework no longer supported in iOS 11 SDK

### ISSUE THREAD

**Issue by pvroosendaal** [AzureAD/azure-activedirectory-library-for-objc#1051]
I'm using the ADALiOS framework, but when compiling my app in Xcode beta (with iOS 11 SDK set as Base SDK) I get an error saying "Compiling IB documents for earlier than iOS 7 is no longer supported.".

<img width="341" alt="screen shot 2017-08-30 at 11 36 09" src="https://user-images.githubusercontent.com/16560001/29866466-c5f9dc7e-8d78-11e7-889e-bfe3d4cdb6f6.png">

When do you expect to release an update?

**Comment by RPangrle** [comment]
This is not an issue on ADAL 2.1+, An update will come for ADAL 1.2.x, but we recommend updating to 2.5.1.

**Comment by pvroosendaal** [comment]
Ok, thanks. Why is 'ADALiOS' on version 1.2.x and 'ADAL' on version 2.5.1? What's the difference betweens those pods?

**Comment by pvroosendaal** [comment]
@RPangrle could you answer my previous question please? Furthermore, perhaps someone should also update this documentation: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devquickstarts-ios
Because this says you should use pod 'ADALiOS'.

**Comment by RPangrle** [comment]
The ADALiOS cocoapod is effectively deprecated, even though it's not marked deprecated officially for contractual reasons. The ADAL cocoapod supports both macOS and iOS, the ADALiOS cocoapod only supported iOS, it was deprecated partly because using a pod named 'ADALiOS' to get the macOS version of ADAL was counter intuitive.

**Comment by pvroosendaal** [comment]
Thanks for the info, much appreciated.

**Comment by charpeni** [comment]
@RPangrle Now that iOS 11 is here, can we have the update for 1.2? I know that upgrading to 2.5 is recommended, but for now an update would be time saving.

**Comment by xinatanil** [comment]
Getting an update for 1.2 becomes critical. Some of us would gladly update to 2.5, but OneDrive iOS SDK works only with 1.2.
