### ISSUE TITLE
Office Mac crashed due to missing null check 

### ISSUE THREAD

**Issue by yozho** [AzureAD/azure-activedirectory-library-for-objc#1063]
It's reported from Watson crash http://watson/BucketDetails?iBucket=128016692841&EventType=610 

From the symbolicated crash log, it crashed on this line
if (!string || !string.length)

Microsoft Error Reporting log version: 2.0

Error Signature:
Exception: EXC_BAD_INSTRUCTION
ExceptionEnumString: 2
Exception Code: 0x00000001 (0x00006100004c1000)
Date/Time: 2017-09-13 13:09:30 +0000
Application Name: Microsoft Word
Application Bundle ID: com.microsoft.Word
Application Signature: MSWD
Application Bitness: x64
Application Version: 15.38.0.17090200
Crashed Module Name: CoreFoundation
Crashed Module Version: 6.9.0
Crashed Module Offset: 0x00000000001112cb
Blame Module Name: ADAL
Blame Module Version: 2.5.0
UnsymbolicatedChecksum: 451580A3EED20AB0A12000D6C2F4CC17
Blame Module Offset: 0x0000000000017e88
StackHash: 06da_background
Application LCID: 1031
Extra app info: Reg=en Loc=0x0407
Build Type: SHIP
Audience: Production
AudienceGroup: CC
AudienceChannel: Production
Crashed thread: 18
uncaught ObjC exception, reason: -[NSNull length]: unrecognized selector sent to instance 0x7fffb973e0e0

Last Exception Backtrace:
0 CoreFoundation 0x00007fff9e7a32cb __exceptionPreprocess + 171 
1 libobjc.A.dylib 0x00007fffb35b348d objc_exception_throw + 48 
2 CoreFoundation 0x00007fff9e824f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132 
3 CoreFoundation 0x00007fff9e715755 ___forwarding___ + 1061 
4 CoreFoundation 0x00007fff9e7152a8 _CF_forwarding_prep_0 + 120 
5 ADAL 0x000000011694ae88 +[NSString(ADHelperMethods) adIsStringNilOrBlank:] + 43 
6 ADAL 0x00000001169551c4 -[ADUserInformation initWithIdToken:error:] + 139 
7 ADAL 0x000000011695637d +[ADUserInformation userInformationWithIdToken:error:] + 78 
8 ADAL 0x0000000116940afe -[ADTokenCacheItem(Internal) fillUserInformation:] + 44 
9 ADAL 0x0000000116940fe9 -[ADTokenCacheItem(Internal) fillItemWithResponse:] + 275 
10 ADAL 0x0000000116940a60 -[ADTokenCacheItem(Internal) processTokenResponse:fromRefresh:requestCorrelationId:fieldToCheck:] + 514 
11 ADAL 0x000000011694083a -[ADTokenCacheItem(Internal) processTokenResponse:fromRefresh:requestCorrelationId:] + 67 
12 ADAL 0x000000011695b834 __84-[ADAcquireTokenSilentHandler acquireTokenByRefreshToken:cacheItem:completionBlock:]_block_invoke + 327 
13 ADAL 0x000000011693b0bf -[ADWebAuthResponse handleSuccess:] + 289 
14 ADAL 0x000000011693ac31 -[ADWebAuthResponse handleJSONResponse:completionBlock:] + 262 
15 ADAL 0x000000011693a841 -[ADWebAuthResponse handleResponse:completionBlock:] + 770 
16 ADAL 0x0000000116939fc1 +[ADWebAuthResponse processResponse:request:completion:] + 151 
17 ADAL 0x0000000116964de7 __32-[ADWebAuthRequest sendRequest:]_block_invoke + 76 
18 ADAL 0x000000011695d93c -[ADWebRequest completeWithError:andResponse:] + 158 
19 ADAL 0x000000011695de70 -[ADWebRequest URLSession:task:didCompleteWithError:] + 129 
20 CFNetwork 0x00007fff9da5101f __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.162 + 76 
21 Foundation 0x00007fffa014df19 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7 
22 Foundation 0x00007fffa014dbfc -[NSBlockOperation main] + 101 
23 Foundation 0x00007fffa014c324 -[__NSOperationInternal _start:] + 672 
24 Foundation 0x00007fffa01481db __NSOQSchedule_f + 201 
25 libdispatch.dylib 0x00007fffb3e638fc _dispatch_client_callout + 8 
26 libdispatch.dylib 0x00007fffb3e799a0 _dispatch_queue_serial_drain + 896 
27 libdispatch.dylib 0x00007fffb3e6c306 _dispatch_queue_invoke + 1046 
28 libdispatch.dylib 0x00007fffb3e656b5 _dispatch_root_queue_drain + 476 
29 libdispatch.dylib 0x00007fffb3e6548c _dispatch_worker_thread3 + 99 
30 libsystem_pthread.dylib 0x00007fffb40b25a2 _pthread_wqthread + 1299 
31 libsystem_pthread.dylib 0x00007fffb40b207d start_wqthread + 13 

For more details, please check VSO bug https://office.visualstudio.com/APEX/_workitems/edit/1872185

**Comment by RPangrle** [comment]
Fixed with #1055. Will be released in next patch.

**Comment by RPangrle** [comment]
And EvoSTS has been tracking down when the server eroneously sends nulls in the AT response.
