### ISSUE TITLE
1.2.x branch requires podspec push

### ISSUE THREAD

**Issue by xinatanil** [AzureAD/azure-activedirectory-library-for-objc#1075]
1.2.x branch recently was updated to 1.2.9.1 version, which contains a fix to critical bug that prevented the project from being compiled on Xcode 9.
I know that I should use 2.5 version but OneDriveSDK depends on 1.2.x version, so I kinda don't have a choice here.
As I understand only members of the project can do that, otherwise I'd gladly made it myself.

I'm aware of #1051 and #1005 , but it appears to me that they are simply forgotten, and I do not completely understand why both of them are closed.

Thanks in advance!

**Comment by oldalton** [comment]
We pushed 1.2.10 pod with the fix. It should be resolved by now.
