### ISSUE TITLE
Push 1.2.10 to Cocoapods repo

### ISSUE THREAD

**Issue by ramonpoca** [AzureAD/azure-activedirectory-library-for-objc#1082]
Please, push the 1.2.10 tag to Cocoapods so it can be set as a dependency on OneDrive.
(see https://github.com/OneDrive/onedrive-sdk-ios/issues/124)

**Comment by oldalton** [comment]
1.2.10 has been already pushed to the ADAL cocoa pod a couple of days ago.

**Comment by ramonpoca** [comment]
My bad, seems the pod was renamed ADALiOS => ADAL.
