### ISSUE TITLE
Safari View Controller iOS11

### ISSUE THREAD

**Issue by derekharkin** [AzureAD/azure-activedirectory-library-for-objc#1086]
We use client certificate authentication as a second factor to our IDP. This forces a double user login on the iOS Authenticator app with the switch from the webview to the Safari View Controller when the client certificate is requested by the IDP.

With the style updates to SFSafariViewController in iOS 11 (removed address bar, colors + buttons customizations) it seems SFSafariViewController could be used for all logins, not just those that use client certificates and avoid the double login scenario.

**Comment by derekharkin** [comment]
Reference: https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/293#issuecomment-203679324

**Comment by oldalton** [comment]
Please take a look at our MSAL SDK, which supports Safari View Controller among other components: [MSAL Obj-C](https://github.com/AzureAD/microsoft-authentication-library-for-objc)
