### ISSUE TITLE
How to open url hosted in azure in iOS web view

### ISSUE THREAD

**Issue by ramkrishna880** [AzureAD/azure-activedirectory-library-for-objc#1111]
We are using ADAL Ios library for login.After that when we are trying to open an URL (like terms and conditions page hosted in Azure to use across all the platforms ) in web view we are getting forbidden. we are able to open with intune browser.
Is there any way to show in a web view. please suggest a way to proceed.

**Comment by oldalton** [comment]
I believe you need to use the access token you get from ADAL to authenticate when you're trying to open the webpage (Bearer header). ADAL won't automatically handle that, ADAL will just provide the access token.
