### ISSUE TITLE
Brokered Authentication reply address mismatch

### ISSUE THREAD

**Issue by spencer-microsoft** [AzureAD/azure-activedirectory-library-for-objc#1123]
After being directed to Authenticator app and successfully signing in, I get an error that shows a mismatch in reply adressess:

> The reply address &#39;{our scheme://our bundle id}&#39; does not match the reply addresses configured for the application: &#39;{our azure app id}&#39;. More details: not specified

The only place where we're sending our azure app id is with the clientId parameter, but I need to send the redirect URI as the first one listed ({our scheme://our bundle id}) to allow brokered auth to even open the Authenticator app. Am I missing a place where I need to set the redirectURI?

**Comment by oldalton** [comment]
Please make sure you register your redirect uri in the Azure portal.
You can follow instructions here: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devquickstarts-ios#3-install-and-configure-adal
Feel free to reopen this issue, if it persists.
