### ISSUE TITLE
invalid client id

### ISSUE THREAD

**Issue by gouravgupta72** [AzureAD/azure-activedirectory-library-for-objc#1158]
Hi Folks,

I'm using the latest version of SDK,

we are facing issue after successful login when come back to app its giving me following error

ADAL 2.6.1 iOS Sim 11.2 [2018-02-22 10:54:52 - DE2AC203-DBB0-4FFE-9D31-BFF17B2C885A] ERROR: Error raised: (Domain: "ADOAuthServerErrorDomain" Code: AD_ERROR_SERVER_OAUTH ProtocolCode: "invalid_client"

Any help appreciated.

**Comment by oldalton** [comment]
Hi, here's the explanation:

invalid_client | Client authentication failed. | The client credentials are not valid. To fix, the application administrator updates the credentials.

Please refer to documentation here: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code#error-codes-for-token-endpoint-errors
