### ISSUE TITLE
Compiler warning when upgrading to latest sdk v2.6.1

### ISSUE THREAD

**Issue by ashrat07** [AzureAD/azure-activedirectory-library-for-objc#1171]
We started getting the following compiler warning when we upgraded to the latest sdk v2.6.1. 

`ld: warning: instance method 'speInfo' in category from /Outlook-iOS-vendor/OutlookVendorKit-iOS/ADAL-ADAL/ADAL.framework/ADAL(ADTokenCacheItem+Internal.o) overrides method from class in /Outlook-iOS-vendor/OutlookVendorKit-iOS/ADAL-ADAL/ADAL.framework/ADAL(ADTokenCacheItem.o)`

**Comment by oldalton** [comment]
Hi, this issue is already fixed, but didn't make it into 2.6.1 release. The PR to fix is here: https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/1135

**Comment by oldalton** [comment]
Should be fixed in latest ADAL releases.
