### ISSUE TITLE
AD_ERROR_TOKENBROKER_RESPONSE_NOT_RECEIVED (503 from Authenticator)

### ISSUE THREAD

**Issue by supervixen** [AzureAD/azure-activedirectory-library-for-objc#1206]
Hello,

I started getting AD_ERROR_TOKENBROKER_RESPONSE_NOT_RECEIVED error sporadically on iOS 11.4 (after a device reset). I've since then reinstalled the Authenticator app and re-registered my device to MFA with contact method "Phone App" but this doesn't seem to help. Any insights on why this might be happening?  

ADAL log:

ADAL 2.6.3 iOS 11.4 [2018-06-01 23:40:41] Error raised: (Domain: "ADAuthenticationErrorDomain" Code: AD_ERROR_TOKENBROKER_RESPONSE_NOT_RECEIVED ProtocolCode: "(null)"

error details: 

Error with code: AD_ERROR_TOKENBROKER_RESPONSE_NOT_RECEIVED Domain: ADAuthenticationErrorDomain ProtocolCode:(null) Details:application did not receive response from broker.. Inner error details: Error Domain=ADAuthenticationErrorDomain Code=503 "(null)", AD_ERROR_TOKENBROKER_RESPONSE_NOT_RECEIVED

**Comment by supervixen** [comment]
This had something to do with the force prompt setting

**Comment by supervixen** [comment]
This seems to have something to do with the FORCE_PROMPT setting. I wanted to support bypassing the token cache for debugging purposes. I'm authenticating first to a 1st party and then to 3rd party resource for the 3rd party. If I use FORCE_PROMPT for both then this seems happen, and gets resolved if I use PROMPT_AUTO for the second token. Closed the issue but any information will be really appreciated! 

Thanks

**Comment by prsreejith** [comment]
@nkwolf 

Please use the below function in your SceneDelegate.swift class..

 **If you are using  SwifUI**

   func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {

            guard let urlContext = URLContexts.first else {
                return
            }
            let url = urlContext.url
            let sourceApp = urlContext.options.sourceApplication
        
        ADAuthenticationContext.handleADALResponse(url, sourceApplication: sourceApp)
    }


OR in Objective-C codebase use the below code in your Appdelegate 

 - (void)scene:(UIScene *)scene openURLContexts:(NSSet<UIOpenURLContext *> *)URLContexts
 {
     UIOpenURLContext *context = URLContexts.anyObject;
     NSURL *url = context.URL;
     NSString *sourceApplication = context.options.sourceApplication;
     
     [ADAuthenticationContext handleADALResponse:url sourceApplication:sourceApplication];
 }
