### ISSUE TITLE
Get Failed login attempt details ADAL ios

### ISSUE THREAD

**Issue by ramkrishna880** [AzureAD/azure-activedirectory-library-for-objc#1214]
Hi Team,

Can we get failed attempts at the time of login from ADAL library? For example, someone tried twice and both time login is failed. is there any provision to get these details from ADAL library.

Also last login time of a user.

Please help me if any provision.

**Comment by oldalton** [comment]
If sign in fails, the status in ADAuthenticationResult would be AD_FAILED. Please refer to documentation here: https://github.com/AzureAD/azure-activedirectory-library-for-objc#how-to-quickly-get-a-token-from-the-sdk
