### ISSUE TITLE
Cordova Adal Library. Bump to the latest version?

### ISSUE THREAD

**Issue by leewhitbeck** [AzureAD/azure-activedirectory-library-for-objc#1249]
I am using the [cordova adal library](https://github.com/AzureAD/azure-activedirectory-library-for-cordova), which uses version **2.3.1** of **this library**.  It looks like there has been [over a year](https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/changelog.txt)  of updates since version 2.3.1 to this native library. 

I am interested in forking the cordova adal repo and bumping from  2.3.1 to the latest version of this library.  I've never had to update a cordova library, so I was hoping someone here may be able to help answer a couple questions I had:

- Would I face any breaking changes if I tried to fork and upgrade cordova adal to use a more recent version of this library? 
- Does anyone know if there is a reason why the cordova adal library has not been upgraded from 2.3.1?

This will be a first for me, so my plan was to use [this commit](https://github.com/AzureAD/azure-activedirectory-library-for-cordova/pull/141/files) as a guide. This was how the cordova adal team upgraded to 2.3.1. 

Any help/tips before I begin would be greatly appreciated.

**Comment by oldalton** [comment]
Hi @leewhitbeck. Unfortunately, we don't maintain ADAL Cordova library. There should't be any breaking API changes, but there are multiple new features and APIs added that you might need to integrate. The best way to see the list of changes is to go to the "releases" page. 

Adding @xerners for additional information regarding ADAL Cordova library.

**Comment by oldalton** [comment]
This behavior is by design. ADAL doesn't guarantee that the result access token has device id in it. The only way to guarantee it is to use the "claims" parameter to enforce the deviceId. The claims parameter has been added a couple of releases back, so in that sense updating to latest release will help you.

**Comment by leewhitbeck** [comment]
@oldalton Thank you very much for the feedback. Your input has highlighted the root cause of our issues. I really appreciate it.

**Comment by leewhitbeck** [comment]
Hey @oldalton, I'm looking into this issue again as I am working on a forked branch of the cordova adal library that references the latest release of IOS adal.

Looking at [this commit](https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/997), it appears a new "claims" parameter was added.

Is this where I need to send the claim info returned from the below graph api error: 

**_interaction_required:AADSTS53000: Your device is required to be managed to access this resource"_** 

I want to confirm that it is this method and not the extraQueryParameters param before I update the cordova library.

Thanks for all your help

**Comment by oldalton** [comment]
Yes, that's where you would send the claims. But the example here is not claims parameter, claims are JSON: e.g. {"access_token":{"polids":{"essential":true,"values":["<GUID>"]}}}

**Comment by bhumin3i** [comment]
@oldalton we got claim parameter from response like you mentioned, but when I send in extraQueryParameters of below method with Cordova [v0.10.1](https://github.com/AzureAD/azure-activedirectory-library-for-cordova)

```
/**
 * Acquires token using interactive flow. It always shows UI and skips token from cache.
 *
 * @param   {String}  resourceUrl Resource identifier
 * @param   {String}  clientId    Client (application) identifier
 * @param   {String}  redirectUrl Redirect url for this application
 * @param   {String}  userId      User identifier (optional)
 * @param   {String}  extraQueryParameters
 *                                Extra query parameters (optional)
 *                                Parameters should be escaped before passing to this method (e.g. using 'encodeURI()')
 *
 * @returns {Promise} Promise either fulfilled with AuthenticationResult object or rejected with error
 */
AuthenticationContext.prototype.acquireTokenAsync = function (resourceUrl, clientId, redirectUrl, userId, extraQueryParameters) {...}
```
but it seems to be not working, and also I can't see any claim parameter.

**Comment by fkelly** [comment]
I recently discovered that in our codebase we were using the `extraQueryParameters` argument rather than the `claims` argument to request `deviceid` for the access token. For a long time, this worked OK (in that the access token did indeed contain `deviceid`) even though our code was incorrect based on your comment above.

I'm wondering if you have any insight as to why this would have worked before. Was there a change made to ADAL that moved the request logic from `extraQueryParameters` to `claims`? 

Thanks!

**Comment by oldalton** [comment]
@fkelly Can you provide exact format of extraQueryParameters that you were using?
In general, extraQueryParameters don't guarantee that correct token will be returned. If there's already a different access token in cache, it will return it even if it doesn't satisfy conditions in the extraQueryParameters. That has always been that way. If you pass claims, ADAL guarantees that access token cache is bypassed and new network call is made to get the correct token. It might have worked accidentally for you before, if there was no other access token in cache.

**Comment by fkelly** [comment]
@oldalton thank you very much for your extremely quick response.

This is what we _had_ been doing:

```
NSString *extraQueryParameters = @"{\"access_token\":{\"deviceid\":{\"essential\":true}}}";
    NSString *encodedPrms = [extraQueryParameters stringByAddingPercentEncodingWithAllowedCharacters:NSCharacterSet.URLQueryAllowedCharacterSet];

    [self.authContext acquireTokenWithResource:self.resourceId
                                      clientId:self.clientId
                                   redirectUri:self.redirectUri
                                promptBehavior:behavior
                                        userId:self.userId
                          extraQueryParameters:encodedPrms
                               completionBlock:^(ADAuthenticationResult *result) {
                                   [self handleAuthenticationResult:result];
                               }];
```

Per your comment above I'm planning to change it to:

```
    NSString *claims = @"{\"access_token\":{\"deviceid\":{\"essential\":true}}}";
    NSString *encodedClaims = [claims stringByAddingPercentEncodingWithAllowedCharacters:NSCharacterSet.URLQueryAllowedCharacterSet];
    
    ADUserIdentifier *userIdentifier = [ADUserIdentifier identifierWithId:self.userId];
    [self.authContext acquireTokenWithResource:self.resourceId
                                      clientId:self.clientId
                                   redirectUri:self.redirectUri
                                promptBehavior:behavior
                                userIdentifier:userIdentifier
                          extraQueryParameters:@""
                                        claims:encodedClaims
                               completionBlock:^(ADAuthenticationResult *result) {
                                   [self handleAuthenticationResult:result];
                               }];
```

Would that be the correct way to _guarantee_ the `deviceid` is in the token?

Thanks a lot for your help!

**Comment by oldalton** [comment]
@fkelly, Yes that should guarantee that you get claims in the access token, or user is asked to complete an action to fulfill the request. However, please make sure you don't always pass claims to silent auth. That will always bypass access token cache and make network request to the server every time, which is probably not what you want.

**Comment by fkelly** [comment]
So would the correct logic be to call `acquireTokenWithResource` without claims and, if that fails, to then call with claims? Or is there a way to inspect the cached token to see if it contains the deviceid? Or is there another way?

Thanks!

**Comment by oldalton** [comment]
You can do acquireTokenSilent without claims, and acquireToken with claims after that if you don't get deviceId. If you're using acquireToken with PROMPT_AUTO (default), there's no good way to do that. If you use a fallback logic, your user might get prompted twice. So, I'd recommend you to explicitly use acquireTokenSilent API without claims, and only use acquireToken with claims when you're certain that silent token acquisition didn't result in correct token. 

To check for deviceId, your resource should be doing it, and returning you the claims challenge or 401 if it doesn't find necessary claims. Client side shouldn't try to open the access token.

**Comment by fkelly** [comment]
This is all very helpful. Thank you.
