### ISSUE TITLE
Access Token Expired

### ISSUE THREAD

**Issue by AndreaGrantu** [AzureAD/azure-activedirectory-library-for-objc#1255]
Hi,
I'd like to have some information regarding access token (AT):
How can I notice if AT has expired?
Otherwise, If I aware that the access token is expired (through my personal API toward my backend), do I have to recall "acquireToken"?  Is there a way to obtain another AT without showing login view? 

Thanks for the support,

Have a nice evening

**Comment by oldalton** [comment]
Hi. ADAL automatically checks that access token is not expired. 5 minutes (this time is configurable) before the expiry date it will try to refresh the access token before returning. Additionally, ADTokenCacheItem has an isExpired method and expiresOn date property.

**Comment by AndreaGrantu** [comment]
Hi,
thanks for the answer. I have only another issue.
When I call acquireToken , it fails and it raises the following message : 

"Error : The certificate for this server is invalid. You might be connecting to a server that is pretending to be “xxxxxxxx”, which could put your confidential information at risk"

I have also set the argument validateAuthority = false in ADAuthenticationContext init, but it always appears. Is there another way to skip the certification check? Otherwise how can I avoid this this issue?

Thanks again

Have a nice day

**Comment by oldalton** [comment]
You need to fix your server. If you're trying to connect to dev server for example, it might be that SSL certificate is invalid. There's no way to skip the certificate check in ADAL, because that would be a security issue.
