### ISSUE TITLE
No 'Keep Me Signed In' message is shown 

### ISSUE THREAD

**Issue by pbruinink** [AzureAD/azure-activedirectory-library-for-objc#1256]
I have an App that is using ADAL to login the user. After the user is successfully logged in, one of the options in the App is to open a website which is published through the Azure App Proxy (with AzureAD pre-auth enabled). The acquired token is added as a Bearer token to a URLRequest which is opened in a UIWebView. 

This works as expected, but once the App is force-closed the session cookie is no longer available and thus the user has to re-authenticate once a link to the published website is clicked. (note that upon launch we are always acquiring the token first which succeeds).

The solution to this would be to use a PSSO cookie, which is written when the user choses 'YES' on the 'Keep Me Signed In' message after successfully authenticated.But, this message never appears when ADAL is used to acquire a token. We do see it in the after the user has re-authenticate when the link is opened in a UIWebView. Is there a way to present a way to present to 'KMSI' message when using ADAL?

**Comment by oldalton** [comment]
This is expected behavior for UIWebView - it doesn't persist session-only cookies beyond its lifetime. 
Also, ADAL doesn't control the "keep me signed in" message by itself, server side decides it. I think it should never show it for UIWebView. This would work in SFSafariViewController or SFAuthenticationSession though.

**Comment by pbruinink** [comment]
Well, I have to say that's not my experience when using a UIWebView. In a test app that only contains a UIWebView, I DO see the KMSI message after successfully authenticated and when I tap YES I don't have to re-authenticate when opening the App (after it has been force-closed). Just like what I expected when a PSSO has been set.
So this seems to be working fine without using the SFSafariViewController. To my understanding the lifetime of the cookie would be 90 days (as we are using ADFS), but I haven't been able to test if that is also applicable when using a UIWebView.. I can confirm that even after the App has been force-closed for a few days I still don't have to re-authenticate when launching the it again.

Regarding the KMSI PSSO cookie: I know it's not ADAL-controlled but server-controlled, but as ADAL is just using a UIWebView (at least to me it seems to be using that), I wonder why that server-controlled message is never shown?

**Comment by oldalton** [comment]
Server is deciding whether to use persistent cookies or not based on the security of the web container used. ADAL library already provides built-in keychain based caching mechanism for tokens, which is more secure mechanism than cookies. ADAL is using embedded webview, which is not secure web component.
