### ISSUE TITLE
AuthToken is of 8 alpha-numeric characters

### ISSUE THREAD

**Issue by SouvikBhowmick** [AzureAD/azure-activedirectory-library-for-objc#1257]
Hello,
I am facing some serious issue which impacting the delivery of my project. Hence looking for you kind help ASAP. 

Actually I was trying to implement the latest version of ADAL library into my iOS code. After successful login, I am getting both of the access token and refresh token of only 8 alpha-numeric characters. 

Whereas, while I am using the Android version library, I am getting some bigger access token and refresh token, which can be successfully decoded using jwt.io. On the other hand, the token that I got in case of iOS, is not recognised while tried to be decrypted using jwt.io

Please help me to understand what exactly is happening.
N.B. iOS ADAL library version is 2.6.3 and Android ADAL library version is 1.14.+
And the git I was using are as follows:
Android: https://github.com/Azure-Samples/active-directory-android
iOS: https://github.com/AzureAD/azure-activedirectory-library-for-objc

**Comment by oldalton** [comment]
Hi. Are you seeing 8 character tokens in the log? ADAL only logs partial hash of the token for identification and doesn't log the entire token. I'm suspecting that's what you're seeing. ADAL will return correct JWT token to the developer.

**Comment by SouvikBhowmick** [comment]
Hi Olga,
This is to inform that I was using the same code given as sample in this Repo(from Dev branch). On the sample app, I was running **MyTestiOSApp**, after setting up the app details (like authority, resource, clientId, redirectUri) in ADTestAppSettings. I put a breakpoint in ADTestAppAcquireTokenViewController (line number 521), 
<img width="1104" alt="screen shot 2018-08-09 at 6 37 43 pm" src="https://user-images.githubusercontent.com/8613865/43901978-7e768c06-9c06-11e8-82ab-e0f3548fc795.png">
and check the values for the accessToken and refreshToken while debugging the application. 
<img width="1063" alt="screen shot 2018-08-09 at 6 45 47 pm" src="https://user-images.githubusercontent.com/8613865/43901993-88b44f3c-9c06-11e8-9f92-4d3ab1cce1b9.png">
The accessToken, refreshToken what I am getting, seems to be odd w.r.t the Android  equivalent.
Please help.

**Comment by oldalton** [comment]
Hi. Yes, this is expected. If you do "po result", it will log the description of the result object. Instead of the whole token, ADAL logs just a short hash of the token to make sure no PII gets logged. It's just a visual representation for the description log. If you want to see the actual token content, you should do po "result.tokenCacheItem.accessToken". This will allow you to see the full content of the token.
