### ISSUE TITLE
AccessToken is empty

### ISSUE THREAD

**Issue by alexrainman** [AzureAD/azure-activedirectory-library-for-objc#1269]
ADKeychainTokenCache contains one item but AccessToken property is empty.

**Comment by alexrainman** [comment]
I see this error:

```
ERROR: createEncodedCachedResponseAndRequestForXPCTransmission - Invalid protocol-property list - CFURLRequestRef. protoProps=<CFBasicHash 0x604000069ac0 [0x10823ac80]>{type = mutable dict, count = 1,
entries =>
	0 : <CFString 0x103620940 [0x10823ac80]>{contents = "context"} = <ADWebAuthRequest: 0x60c000109990>
}
```

**Comment by oldalton** [comment]
Hi. It's likely that you're seeing the refresh token entry in the cache. ADAL will automatically try to acquire new access token using refresh token when you call acquireTokenSilent.
What is the result you're seeing in ADAL result callback?

**Comment by alexrainman** [comment]
Issue solved. Found that there are multiple tokens saved in the cache and i was getting the first one which, for some reasons, had AccessToken property empty. Now everything is working as expected. Thanks

**Comment by oldalton** [comment]
@alexrainman We generally don't recommend reading cache directly. We'd recommend to use acquireTokenSilent method to read tokens from cache. What's the scenario you're trying to solve by reading from cache directly?

**Comment by alexrainman** [comment]
It has been working just fine for me reading the token directly but i will take a look at acquireTokenSilent method. By the way, this is from Xamarin using my own binding.

**Comment by alexrainman** [comment]
Will this method show a login screen if there's not token?

**Comment by oldalton** [comment]
acquireTokenSilent won't show the login screen. It will return a particular error message to indicate that login screen needs to be shown. If you want to automatically show the login screen, if there're no tokens in cache, you can use acquireToken with AD_PROMPT_AUTO

**Comment by alexrainman** [comment]
@oldalton can you clarify this property?

```obj-c
/*! Returns YES if the user is not not set. */
- (BOOL)isEmptyUser;
```
There are two "not" in the comment and what "user" is that? Upn under UserInformation?

**Comment by alexrainman** [comment]
Is ExpiresOn expressed in UTC?

```obj-c
/*! Compares expiresOn with the current time. If expiresOn is not nil, the function returns the
 comparison of expires on and the current time. If expiresOn is nil, the function returns NO,
 so that the cached token can be tried first.*/
- (BOOL)isExpired;
```

**Comment by oldalton** [comment]
```
/*! Returns YES if the user is not not set. */
- (BOOL)isEmptyUser;
```

Will return YES, if server doesn't return us an id_token (not OIDC compliant). AAD will always return an id_token when requested. 

Will fix the double not in comments, thanks for the note.

**Comment by oldalton** [comment]
And expiresOn property is calculated based on device's time at the time of receiving the token.

**Comment by oldalton** [comment]
Seems the issue has been addressed. Feel free to reopen if you have additional questions.

**Comment by alexrainman** [comment]
Yeah, i got it working. I released my bindings as a nuget named ADALBindingsiOS
