### ISSUE TITLE
No way to cancel an ongoing "acquireToken" call

### ISSUE THREAD

**Issue by MadhviMishra** [AzureAD/azure-activedirectory-library-for-objc#127]
ADAL doesn't have an API to cancel an ongoing login request. In addition it blocks subsequent call if there is already an ongoing login request. We need a way to allow users to get back into the login screen in case there was an error or they navigated away to another webpage from the login page.

![acquiretoken](https://cloud.githubusercontent.com/assets/8524183/4012189/a8c8f546-2a0b-11e4-92a6-dd6995ff05de.png)

**Comment by kunalbalani** [comment]
I eventually fixed this by calling 
ADWebAuthController.cancelCurrentWebAuthSession(). [https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/681](url)
