### ISSUE TITLE
AcquireSilentToken error

### ISSUE THREAD

**Issue by AndreaGrantu** [AzureAD/azure-activedirectory-library-for-objc#1270]
Hi,
I successfully did login using acquireToken and got access token. Then when I kill the app and restart it, the app has to check if Access token is still valid or not in order to show different behaviors due to requirements. 
I tried to use acquireTokenSilent, but every time it shows me USER INPUT NEED ERROR. It seems that in the cache there's no informations stored (I debugged step by step) . Do I have to manually store the access token after first login success? Is there something particular to set in acquireTokenSilent?
Thanks, 
Have a good day!

**Comment by AndreaGrantu** [comment]
I've just debug the application, it obtains the access token successfully, but the verbose log said:
"ERROR: Error raised: (Domain: "ADKeychainErrorDomain" Code: -34018 ProtocolCode: "(null)" "
Is it the reason for the cache store problem?

Thanks!

**Comment by oldalton** [comment]
Please make sure you configured your keychain access group correctly, as described here: https://github.com/AzureAD/azure-activedirectory-library-for-objc#caching

**Comment by oldalton** [comment]
@AndreaGrantu Have you had a chance to try out the suggestion and see if it works for you?

**Comment by AndreaGrantu** [comment]
Yes,
my solution is to set promptBeheviour = Force Refresh in the acquireToken.
In this way, acquireTokenSilent does not rise the USER INPUT NEED ERROR.

**Comment by oldalton** [comment]
I believe this issue has been resolved. Feel free to reopen if you're still experiencing it in the latest ADAL version.
