### ISSUE TITLE
"instance_aware=true" does not return the correct value for authority for soverign clouds

### ISSUE THREAD

**Issue by dianambb** [AzureAD/azure-activedirectory-library-for-objc#1281]
I am following the steps outlined in the wiki but the authority property on the result is still incorrect. Our ADAL SDK version is 2.6.4.

Using an account on GCC High, I am calling the snippit below.

```
let context = ADAuthenticationContext(authority: "https://login.microsoftonline.com/common", error: &error)

context.acquireToken(withResource: "https://graph.microsoft.us",
                               clientId: ADALConstants.clientId,
                               redirectUri: ADALConstants.redirectUri,
                               promptBehavior: promptBehavior,
                               userIdentifier: userIdentifier,
                               extraQueryParameters:"msafed=0&instance_aware=true",
                               completionBlock: completionBlock)
```
In the result returned,

result.authority is "login.microsoftonline.com/common" instead of "login.microsoftonline.us/common". I see the same issue with DoD instance.

**Comment by oldalton** [comment]
Discovery for this tenant returns login.microsoftonline.com, so it's not an ADAL client side issue. We'll follow up on the configuration to understand if login.microsoftonline.com is an expected result.
