### ISSUE TITLE
SharePoint token using Outlook user id token

### ISSUE THREAD

**Issue by venkatkonjeti** [AzureAD/azure-activedirectory-library-for-objc#1295]
I am building a outlook add-in which needs to access the SharePoint resources with user permissions with out asking for signin crdentials again.

I have registered an app in Azure AD and calling "https://login.microsoftonline.com/common/oauth2/authorize" with client id which is prompting for username and password again which I should avoid signin popup as my outlook  already signed in with my office 365/Azure AD credentials.

I know I am missing something here. can someone help me.

Thanks,
Venkat konjeti

**Comment by oldalton** [comment]
Hi. A third party app can't access Outlook's credentials. This is the security boundary. Please let me know if I misunderstood your question.

**Comment by venkatkonjeti** [comment]
> Hi. I'm not very familiar with Outlook add-ins. Generally, a third party app can't access Outlook's credentials. This is the security boundary of the keychain. Please provide more information about what's your setup. Please also provide information about ADAL APIs that you're using. Thanks!

This is a Node JS application and I am using ADAL.js. I had a same impression initially but there is an article [Enable SSO for Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins) which achieves SSO for Graph API this uses Azure AD v2.0 registration. I want to achieve same thing for SharePoint API.

**Comment by rohitnarula7176** [comment]
@venkatkonjeti Please open an issue on the ADAL js repo. I have added the link below:
https://github.com/AzureAD/azure-activedirectory-library-for-js. Closing this as this is not applicable to ADAL Objc.

**Comment by venkatkonjeti** [comment]
Thanks Rohit.
