### ISSUE TITLE
azure-activedirectory-library-for-react-native

### ISSUE THREAD

**Issue by pcooney10** [AzureAD/azure-activedirectory-library-for-objc#1307]
Hey team,

There are `microsoft-authentication-library-for-js`, `azure-activedirectory-library-for-objc`, and `microsoft-authentication-library-for-android` libraries - is a React Native implementation anywhere on the roadmap?

P.S. Thanks for the great work!

**Comment by navyasric** [comment]
@pcooney10 Thanks for your interest. We have plans for ReactJS on our roadmap. For React Native, we are still evaluating plans and do not have a definite roadmap yet.
