### ISSUE TITLE
Crash in [MSIDKeychainUtil appDefaultAccessGroup] in version 2.7.0

### ISSUE THREAD

**Issue by dianambb** [AzureAD/azure-activedirectory-library-for-objc#1310]
This is the top of the call stack. The full crash log has been shared offline.

0   CoreFoundation                	0x00000001acf2ff50 CFRelease + 124 (CFRuntime.c:948)
1   ADAL                          	0x0000000101454dbc __41+[MSIDKeychainUtil appDefaultAccessGroup]_block_invoke + 688 (MSIDKeychainUtil.m:80)
2   libdispatch.dylib             	0x00000001aca84484 _dispatch_client_callout + 16 (object.m:511)
3   libdispatch.dylib             	0x00000001aca54244 _dispatch_once_callout + 28 (once.c:52)
4   ADAL                          	0x0000000101454b04 +[MSIDKeychainUtil appDefaultAccessGroup] + 56 (once.h:84)
5   ADAL                          	0x0000000101454974 __26+[MSIDKeychainUtil teamId]_block_invoke + 52 (MSIDKeychainUtil.m:36)
6   libdispatch.dylib             	0x00000001aca84484 _dispatch_client_callout + 16 (object.m:511)
7   libdispatch.dylib             	0x00000001aca54244 _dispatch_once_callout + 28 (once.c:52)
8   ADAL                          	0x0000000101454938 +[MSIDKeychainUtil teamId] + 56 (once.h:84)
9   ADAL                          	0x0000000101451390 -[MSIDKeychainTokenCache initWithGroup:] + 204 (MSIDKeychainTokenCache.m:106)
10  ADAL                          	0x0000000101418058 -[ADKeychainTokenCache initWithGroup:] + 116 (ADKeychainTokenCache.m:94)
11  ADAL                          	0x0000000101417fc8 -[ADKeychainTokenCache init] + 68 (ADKeychainTokenCache.m:84)
12  ADAL                          	0x0000000101417eac __44+[ADKeychainTokenCache defaultKeychainCache]_block_invoke + 40 (ADKeychainTokenCache.m:64)
13  libdispatch.dylib             	0x00000001aca84484 _dispatch_client_callout + 16 (object.m:511)

**Comment by oldalton** [comment]
Thanks. ADAL 2.7.3 fixes the issue: https://github.com/AzureAD/azure-activedirectory-library-for-objc/releases/tag/2.7.3

**Comment by oldalton** [comment]
I believe this issue has been resolved. Feel free to reopen if you're still experiencing it in the latest ADAL version.
