### ISSUE TITLE
Failed to set item into keychain-ADAL 2.7.3 when i try to reset pin after clicking forgot password

### ISSUE THREAD

**Issue by kiara544** [AzureAD/azure-activedirectory-library-for-objc#1329]
I do not use any other keychain group other than default adalcache.  Issue arrives only if the users hits forgot Pin , Sign in with your organizational Account screen shows up and  after the details are submitted users get failed to set error.

So reverted the ADAL 2.6.5 version and app works fine and users can reset the pin without any issues.

Any help is Appreciated

**Comment by oldalton** [comment]
@kiara544, can you please take a look at the issue here and let me know if it possibly has the same reason? https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1280?slice=test1&accesstokenforfamiliarip=true

If not, please provide sample code you're using and if you declare adalcache entitlement in your app.

**Comment by kiara544** [comment]
@oldalton I tried the work around you mentioned in the above link but it did not work.

Yes my app is using iOS Intune MAM SDK. When Clicked on Forgot Pin button , webview is opened within the app and asks to sign in with organizational account after details are entered the error is thrown.

Sample Code of creating ADAuthContext and Acquiring Token

var authContext:ADAuthenticationContext = {
        var error:ADAuthenticationError? = nil
        let context: ADAuthenticationContext = ADAuthenticationContext(authority: "https://login.microsoftonline.com/common", error: &error)
        context.credentialsType = AD_CREDENTIALS_AUTO
        ADAuthenticationSettings.sharedInstance().enableFullScreen = true
        return context
    }()
    
    func authentication(vc:UIViewController, completionBlock:@escaping (ADAuthenticationResult?)->Void){
        authContext.parentController = vc
        authContext.acquireToken(withResource: resourceURL, clientId: Target.CLIENT_ID, redirectUri: URL(string:Target.REDIRECT_URL), promptBehavior: AD_PROMPT_AUTO, userIdentifier: nil, extraQueryParameters: "nux=1") { (result) in
            completionBlock(result)
        }
    }

Following is added in the Entitlements File 

$(AppIdentifierPrefix)com.microsoft.intune.mam
$(AppIdentifierPrefix)com.microsoft.adalcache

**Comment by oldalton** [comment]
Thank you, I'm suspecting there's an issue in the MAM SDK or some incompatibility.
Can you please provide exact ADAL error with code and description that you're seeing? 

Even better if you could email me your ADAL logs as described here: [Logging](https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/Logging). Please send them to [my email](oldalton@microsoft.com)

Thanks.

**Comment by oldalton** [comment]
The behavior should be improved in ADAL 2.7.5. Please try out.
