### ISSUE TITLE
Forced Second Login Issue

### ISSUE THREAD

**Issue by leewhitbeck** [AzureAD/azure-activedirectory-library-for-objc#1334]
I'm using a [ forked version](https://github.com/mlynch/azure-activedirectory-library-for-cordova) of the microsoft cordova adal library that is referencing release 2.6.4 of this obc library. 

We are experiencing an **issue** where some users of our app are forced to login twice. However, most users are not experiencing this issue. From what we have gathered so far, the double login seems to happen on IOS 12.0.1 for iPhone 7 and iPhone 8 Plus. I don't have any of the logs available, but I can get that info if needed.  

I scanned through the issue listing here, but nothing stood out. Has anyone experienced this double login before? Any updates after the  2.6.4 release that may have fixed this by chance?

Note: the forked cordova library we are using has been updated to use the recent claims parameter on the acquireTokenAsync call for interaction_required scenarios. For most users that flow seems to work fine - we use broker based auth. I'm not sure if the double login is related to this scenario, but I thought it may help to mention this.

**Comment by oldalton** [comment]
Are they forced to login twice when getting a token for 2 different resources or for the same resource?

**Comment by leewhitbeck** [comment]
@oldalton same resource.

**Comment by oldalton** [comment]
@leewhitbeck Do you mind sending us ADAL logs? Please see instructions [here](https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/Logging). Please make sure your logs don't contain any private information. You can send the logs to [my email](mailto:oldalton@microsoft.com)

**Comment by leewhitbeck** [comment]
@oldalton, I am unable to get the logs at the moment due to a **new issue** that we are seeing.  Our Intune administrators made a change in the conditional access policy configurations [requiring only approved apps selections](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/technical-reference#approved-client-app-requirement).  It seems that only Microsoft applications are on this approved list, and I do not see a way for line of business apps to be added. Do you know if there is a way to work around this or does adal not work when this configuration is set? If this issue should be raised somewhere else, just let me know and I can open it elsewhere. Thanks for the help @oldalton

**Comment by oldalton** [comment]
@leewhitbeck, sorry for a late response. You need to configure and use broker, in order to work correctly with conditional access policies. Please see instructions [here](https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/Broker)

**Comment by leewhitbeck** [comment]
@oldalton thanks for reaching out. I am working with MSFT on an open case we have open that is blocking our app. Once that is resolved I can send over the log information.
