### ISSUE TITLE
ADAL 2.7.4 Fails to Compile with Carthage

### ISSUE THREAD

**Issue by corbinreynolds** [AzureAD/azure-activedirectory-library-for-objc#1337]
The `ADAL iOS` scheme in SDK version 2.7.4 fails to compile with Carthage. The compilation error is below:

```
MSIDKeychainUtil.m:69:76: error: values of type 'OSStatus' should not be used as format arguments; add an explicit cast to 'int' instead [-Werror,-Wformat]
                
MSID_LOG_ERROR(nil, @"Failed to delete teamID, result %d", deleteStatus);
                                                                      ~~   ^~~~~~~~~~~~
                                                                      %d   (int)
```

It looks like the log line above, needs to be re-written:

**MSID_LOG_ERROR(nil, @"Failed to delete teamID, result %d", (int)deleteStatus);**

To reproduce the issue, download the Test project and run `carthage update --platform iOS` in the top-level directory. To install Carthage, check the README on the [GitHub Repo](https://github.com/Carthage/Carthage).

[Test.zip](https://github.com/AzureAD/azure-activedirectory-library-for-objc/files/2541018/Test.zip)

**Comment by oldalton** [comment]
Please try with ADAL 2.7.5. We fixed that warning in 2.7.5.
