### ISSUE TITLE
Question Refresh Token Validation

### ISSUE THREAD

**Issue by AndreaGrantu** [AzureAD/azure-activedirectory-library-for-objc#1347]
Hi,
I have one question about the Refresh Token in a particular scenario:
 I have 2 devices (A and B), both logged with the same account at the same time.  Device A changes the account password.

Now I suppose the flow is this:
1.  After N hour (N = access token expiration time), the AT will expire, in both devices. 
2.  So if I try to do an external call with device A, the backend will notice me that AT is expired and the app will consequently try to obtain a new AT using Refresh Token, through with acquireTokenSilent.
3. The acquireTokenSilent will return "failed" and the user will have to redo the login on device A.

Is everything correct till now?

If so, my question is: what will happen in device B after the AT token is expired (and trying to do an external call)? 
The behavior is the same as I explained before?
or ADAL system will notify all the other connected devices with the new refresh token and the session will never expire?

Could you please explain me how does it work in this particular scenario?

Thanks for the support

Andrea

**Comment by oldalton** [comment]
Yes, user would need to sign in on both devices. ADAL doesn't synchronize credentials to iCloud keychain for security reasons.

**Comment by oldalton** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
