### ISSUE TITLE
Unable to Authenticate Azure ADAL iOS Swift Library to access Azure Mobile Apps Easy Tables Data

### ISSUE THREAD

**Issue by kkadapa** [AzureAD/azure-activedirectory-library-for-objc#1348]
I am terribly in need of AD Auth for Swift iOS which can talk to Easy Tables and retrieve data, i religiously tried following this [AzureAD](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-ios-how-to-use-client-library#adal) and i think it's old... I was able to get the Access-Token and retrieve data from Easy Tables in my first time user login call see below: 

var applicationContext : ADAuthenticationContext?
    var dataTask: URLSessionDataTask?
    
  ```
  let client = MSClient(applicationURLString: "https://xxxxxxxxx.org")
    let authority = "https://login.microsoftonline.com/xxxxx.onmicrosoft.com"
    
    let resourceId = "xxxxxxxx-8dbf-xxxxxx-821b-xxxxxx"
    let clientId = "xxxxxx-bca5-42ac-ac3d-xxxxx"
    let adredirectUri = URL(string: "https://xxxxxxxx.org/.auth/login/aad/callback")
```

````
func authenticate(parent: UIViewController, completion: @escaping (MSUser?, NSError?) -> Void) { 

 let authContext = ADAuthenticationContext(authority: authority, error: error)

    authContext!.parentController = parent

    ADAuthenticationSettings.sharedInstance().enableFullScreen = true

    

    authContext?.acquireToken(withResource: resourceId, clientId: clientId, redirectUri: adredirectUri) { (result) in

        

        if result!.status != AD_SUCCEEDED {

            completion(nil, result!.error)

        }

        else {

            print("access TOKEN IS ",result?.tokenCacheItem.accessToken as Any)

            let payload: [String: String] = ["access_token": (result?.tokenCacheItem.accessToken)!]

            

            self.client.login(withProvider: "aad", token: payload, completion: { (MSUser, Error) in

                

                print("mslogin...",MSUser?.userId!.description ?? "defaultuser")

                print("client data",self.client.currentUser!.userId!.description)

                

                //Store default userID and AccessToken

                UserDefaults.standard.set(self.client.currentUser!.userId, forKey: "defaultsuserid")

                UserDefaults.standard.set(result!.accessToken, forKey: "ADaccesstoken")

                

                self.updateSignoutButton(enabled: true)

                

                var expiresOnString = "(nil)"

                if let expiresOn = result!.tokenCacheItem.expiresOn {

                    expiresOnString = String(describing: expiresOn)

                }

                

                let status = String(format: "Access token: %@\nexpiration:%@", result!.accessToken, expiresOnString)

                self.updateLogging(text:status)

                self.getAzureData()

            })
        }
    }
}
````

**Should i store the default userid and access-token retrieved in the first time user login and call acquiretokensilent for subsequent calls to the DB? Could you tell me which method should be called? Is there a Quickstart Swift App i can follow? Also, what should i store in Userdefaults and check in Appdelegate is that refreshtoken ?

I know we should first retrieve an existing access-token from Cache before prompting user to signin. But after i call acquire-token-silently with the cached access-token i am getting the following error:**

ERROR  Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1302 "{"code":401,"message":"IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier\u000d\u000a    (\u000d\u000a    IsReadOnly = False,\u000d\u000a    Count = 2,\u000d\u000a    Clause[0] = X509ThumbprintKeyIdentifierClause(Hash = 0xC142E661FB2A750B96B55FFE87156D0C92593384),\u000d\u000a    Clause[1] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause\u000d\u000a    )\u000d\u000a', \u000atoken: '{\"typ\":\"JWT\",\"alg\":\"RS256\",\"x5t\":\"wULmYfsqdQuWtV_-hxVtDJJZM4Q\",\"kid\":\"wULmYfsqdQuWtV_-hxVtDJJZM4Q\"}.{\"aud\":\"xxxxxxxx-8dbf-4def-821b-d4116d126305\",\"iss\":\"https:\/\/sts.windows.net\/7f786e85-2b61-4bbe-a796-71e91e5e7e38\/\",\"iat\":1543378089,\"nbf\":1543378089,\"exp\":1543381989,\"acr\":\"1\",\"aio\":\"ASQA2\/8JAAAAoKDleM8l5U1sykI7WzzBn3cBpxxxxxxxxx=\",\"amr\":[\"pwd\"],\"appid\":\"0f11fe72-bca5-42ac-ac3d-c520a354ac34\",\"appidacr\":\"0\",\"family_name\":\"xxxxxx\",\"given_name\":\"xxxx xxxx\",\"ipaddr\":\"69.126.158.128\",\"name\":\"xxxxxx\",\"oid\":\"xxxxxx-96c2-xxxx\",\"onprem_sid\":\"S-1-5-21-2222222222-2079600828-449122\",\"scp\":\"user_impersonation\",\"sub\":\"xxxxxxxxxxxxMgKdv8QPxkyHwIs\",\"tid\":\"9889w384502ajsjflsaj-a796-71e91e5e7e38\",\"unique_name\":\"xxxxxx@xxxxxx.edu\",\"upn\":\"xxxx@xxxxxx.edu\",\"uti\":\"sfasfafafsafaf\",\"ver\":\"1.0\"}\u000aRawData: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IndVTG1ZZnNxZFF1V3RWXy1oeFZ0REpKWk00USIsImtpZCI6IndVTG1ZZnNxZFF1V3RWXy1oeFZ0REpKWk00USJ9.eyJhdWQiOiJjMjBlMGQxZi04ZGJmLTRkZWYtODIxYi1kNDExNmQxMjYzMDUiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83Zjc4NmU4NS0yYjYxLTRiYmUtYTc5Ni03MWU5MWU1ZTdlMzgvIiwiaWF0IjoxNTQzMzc4MDg5LCJuYmYiOjE1NDMzNzgwODksImV4cCI6MTU0MzM4MTk4OSwiYWNyIjoiMSIsImFpbyI6IkFTUUEyLzhKQUFBQW9LRGxlTThsNVUxc3lrSTdXenpCbjNjQnBZdWhLWUdkQ2ZjUGtVM1lvVEU9IiwiYW1yIjpbInB3ZCJdLCJhcHBpZCI6IjBmlsfjdaljfaljflajflajflafjlafzU0YWMzNCIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiS2FkYXBhIiwiZ2l2ZW5fbmFtZSI6IktyaXNobmEgS2FydGhpayIsImlwYWRkciI6IjY5LjEyNi4xNTguMTI4IiwibmFtZSI6IkthZGFwYSwgS3Jpc2huYSBLYXJ0aGlrIiwib2lkIjoiZTg5N2VlNDQtYWMwYy00ZDQ4LTk2YzItOGY2ZDM3MWVmNWY4Iiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTEzMzgzMjUyMDAtNTA0NzYwNzc4LTIwNzk2MDA4MjgtNDQ5MTIyIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0afjlsfjalfjslafjaNHZyM2RCb1BpaDhzUXcycDBVTTJ5T3RXb01nS2R2lasljalfalfjalfjlajlafyIsInRpZCI6IjdmNzg2ZTg1LTJiNjEtNGJiZS1hNzk2LTcxZTkxZTVlN2UzOCIsInVuaXF1ZV9uYW1lIjoia2thZGFwYUBub3J0aHdlbGwuZWR1IiwidXBuIjoia2thZGFwYUBub3J0aHdlbGwuZWR1IiwidXRpIjoibEdZZ0VWTllzRXVPWDhHYWk5SmJBUSIsInZlciI6IjEuMCJ9.fj7N8-naJDfMLsNUY_3QtUSMQ4rAOdCrPfmBNlq3_BacdAmVyt7wOQ6aSOmC-rFdD8yIXgT0xr2vYJszCGM9sJRImh08s8u1CX4ugfbVnAjeyGrJPcbLlYuV6aRSLxg4BLM5IhsK4iZa0p7MvGQkeTERRF2q_Lg_giqyPGhyx6WVnd6gbl2o2KgyTh1kRnjWcqQKhvfPbC-NMdLEkBiAJsi0WzMMeLCyzmid7H3k6nsb-fjalfjafljalfjlafjlasjfa'."}" UserInfo={com.Microsoft.MicrosoftAzureMobile.ErrorResponseKey=<NSHTTPURLResponse: 0x1c0029b00> { URL: https://xxxxxxx.org/tables/xxxxlist } { Status Code: 401, Headers {
    "Content-Encoding" =     (
        gzip
    );
    "Content-Type" =     (
        "application/json"
    );
    Date =     (
        "Wed, 28 Nov 2018 14:14:19 GMT"
    );
    "Set-Cookie" =     (
        "ARRAffinity=efbf189aasfasfaab15004f8113326a8b1dasfasfa13a5dfd3f9fddef;Path=/;HttpOnly;Domain=xxxxxxxx.org",
        "incap_ses_221_1861667=ZydXKzBbZWHxL0XAHCkRA7ui/lsAAAAAPHi+ZIRrXqgr5AkpOvL2YQ==; path=/; Domain=.io.xxxxxx.org"
    );
    "Transfer-Encoding" =     (
        Identity
    );
    "Www-Authenticate" =     (
        "Bearer realm=\"xxxxx.xxxx.org\" authorization_uri=\"https://login.windows.net/7f786e85asfafa4bbe-a796-71e91e5e7e38/oauth2/authorize\" resource_id=\"asfasfsafa-8dbf-sssssss-821b-d4116d126305\""
    );
    "X-CDN" =     (
        Incapsula

    );
    "X-Iinfo" =     (
        "5-79518167-79518178 NNNN CT(0 0 0) RT(1543414458987 78) q(0 0 0 0) r(3 3) U11"
    );
    "X-Powered-By" =     (
        "ASP.NET"
    );
} }, NSLocalizedDescription={"code":401,"message":"IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier\u000d\u000a    (\u000d\u000a    IsReadOnly = False,\u000d\u000a    Count = 2,\u000d\u000a    Clause[0] = X509ThumbprintKeyIdentifierClause(Hash = 0xC142E661FB2A750B96BUUUUUUUUUUUUU3384),\u000d\u000a    Clause[1] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause\u000d\u000a    )\u000d\u000a', \u000atoken: '{\"typ\":\"JWT\",\"alg\":\"RS256\",\"x5t\":\"wULmYfsqdQuWtV_-hxVtDJJZM4Q\",\"kid\":\"wULmYfsqdQuWtV_-hxVtDJJZM4Q\"}.{\"aud\":\"c20e0d1f-8dbf-4def-821b-d4116d126305\",\"iss\":\"https:\/\/sts.windows.net\/7f786e85-2b61-4bbe-a796-71e91e5e7e38\/\",\"iat\":1543378089,\"nbf\":1543378089,\"exp\":1543381989,\"acr\":\"1\",\"aio\":\"ASQA2\/8JAAAAoKDleM8l5U1sykI7WzzBn3cBpYuhKYGdCfcPkU3YoTE=\",\"amr\":[\"pwd\"],\"appid\":\"0f11fe72-bca5-42ac-ac3d-c520a354ac34\",\"appidacr\":\"0\",\"family_name\":\"xxxxx\",\"given_name\":\"xxxx xxxx\",\"ipaddr\":\"69.342.158.128\",\"name\":\"ssssss\",\"oid\":\"sasfadsf4-ac0c-4d48-96c2-8f6d371ef5f8\",\"onprem_sid\":\"S-1-5-21-1338325200-45454544-2079600828-449122\",\"scp\":\"user_impersonation\",\"sub\":\"RmQ4vr3dBoPih8sQw2p0UM2yOtWoMgKdv8QPxkyHwIs\",\"tid\":\"7f786e85-2b61-4bbe-a796-71e91e5e7e38\",\"unique_name\":\"xxxxxx@xxxx.edu\",\"upn\":\"xxx@xxx.edu\",\"uti\":\"lGYgEVNYsEuOX8Gai9JbAQ\",\"ver\":\"1.0\"}\u000aRawData: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IndVTG1ZZnNxZFF1V3RWXy1oeFZ0REpKWk00USIsImtpZCI6IndVTG1ZZnNxZFF1V3RWXy1oeFZ0REpKWk00USJ9.eyJhdWQiOiJjMjBlMGQxZi04ZGJmLTRkZWYtODIxYi1kNDExNmQxMjYzMDUiLCJpc3MiOiJodHRwczovL3N0cyasjlfalaljafWF0IjoxNTQzMzc4MDg5LCJuYmYiOjE1NDMzNzgwODksImV4cCI6MTU0MzM4MTk4OSwiYWlasjlfajflahKQUFBQW9LRGxlTThsNVUxc3lrSTdXenpCbjNjQnBZdWhLWUdkQ2ZjUGtVM1lvVEU9IiwiYW1yIjpbInB3ZCJdLCJhcHBpZCI6IjBmMTFmZTcyLWJjYTUtNDJhYy1hYzNkLWM1MjBhMzU0YWMzNCIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiS2FkYXsajflalfjalfjaljfkI6IktyaXNobmEgS2FydGhpayIsImlwYWRkciI6IjY5LjEyNi4xNTguMTI4IiwibmFtZSI6IkthZGFwYSwgS3Jpc2huYSBLYXJ0aGlrIiwib2lkIjoiZTg5N2VlNDQtYWMwYy00ZDQ4LTk2YzItOGY2ZDM3MWVmNWY4Iiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTEzMzgzMjUyMDAtNTA0NzYwNzc4LTIwNzk2MDA4MjgtNDQ5MTIyIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiUm1RNHZyM2RCb1BpaDhzUXcycDBVTTJ5T3RXb01nS2RlsdfjaljflasfInRpZCI6IjdmNzg2ZTg1LTJiNjEtNGJiZS1hNzk2LTcxZTkxZTVlN2UzOCIsInVuaXF1ZV9uYW1lIjoia2thZGFwYUBub3J0aHdlbGwuZWR1IiwidXBuIjoia2thZGFwYUBub3J0aHdlbGwuZWR1IiwidXRpIjoibEdZZ0VWTllzRXVPWDhHYWk5SmJBUSIsInZlciI6IjEuMCJ9.fj7N8-naJDfMLsNUY_3QtUSMQ4rAOdCrPfmBNlq3_BacdAmVyt7wOQ6aSOmC-rFdD8yIXgT0xr2vYJszCGM9sJRImh08s8u1CX4ugfbVnAjeyGrJPcbLlYuV6aRSLxg4BLM5IhsK4iZa0p7MvGQkeTERRF2q_Lg_giqyPGhyx6WVnd6gbl2o2KgyTh1kRnjWcqQKhvfPbC-NMdLEkBiAJsi0WzMMeLCyzmid7H3k6nsb-BqYtJQdMCTHmmxhyiJhHXhlzEnj8rPrduMIEjONC5G_PXJoy5BErR_DcbYd8DGLvGeOGfYCSBrFLV4_5d4xlibVe9syIX8ZhxsKMkKezw'."}, com.Microsoft.MicrosoftAzureMobile.ErrorRequestKey=<NSMutableURLRequest: 0x1c4012430> { URL: https://xxxxxxx.org/tables/xxxxxlist }}
2018-11-28 09:14:21.029353-0500 QuickStart[5979:3817678] ERROR: createEncodedCachedResponseAndRequestForXPCTransmission - Invalid protocol-property list - CFURLRequestRef. protoProps={
    context = "<ADWebAuthRequest: 0x1c01318a0>";
}
2018-11-28 09:14:21.029633-0500 QuickStart[5979:3817678] ADD: failed to create cache dictionary at path=/private/var/mobile/Containers/Data/Application/safafafafaf9772-4F6A-89D3-EAF459DB2A06/Library/Caches/com.microsoft.identity.client.sample.quickstart. key=0x1c4388e30

**Comment by oldalton** [comment]
Yes, you should store userId from the result and use it for subsequent silent requests (acquireTokenSilentWithResource...). You can rely on ADAL to cache refresh and access tokens and return tokens to the app on iOS, no need to cache tokens yourself. So, whenever you need an access token, call ADAL's acquireTokenSilent method and you'll get the correct token back or request to do interactive authentication.

Regarding your first issue, ADAL doesn't have a "login" method, so the failure is not happening on ADAL side. Which SDK is that?

**Comment by kkadapa** [comment]
Wonderful! @oldalton i'll try to do that... i am using this in my POD `pod 'MicrosoftAzureMobile', '~> 3.4.0'` [thisone](https://cocoapods.org/pods/MicrosoftAzureMobile)... I am religiously following [this](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-ios-how-to-use-client-library#adal) documentation for client.login method is this outdated? All i want is the access-token to talk to my easy tables for smooth communication. Thank you so much, seriously appreciate your attention and time.

**Comment by oldalton** [comment]
The original error you posted is coming from MicrosoftAzureMobile space: ERROR Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1302 ". Can you clarify if you're getting an access token successfully from ADAL and getting an error when calling MicrosoftAzureMobile? If that's the case, please refer to MicrosoftAzureMobile SDK.

**Comment by kkadapa** [comment]
Yes ADAL is giving me access-token.. can i use that token to call easy tables data? Should i use [MicrosoftAzureMobile](https://github.com/Azure/azure-mobile-apps-ios-client) sdk to talk to the backend Azure Easy tables or MSAL or is there anything inbuilt sdk using ADAL to talk to easy tables? i thought i can use [this](https://github.com/AzureADQuickStarts/NativeClient-iOS) sample but i am so confused... it all started with [MicrosoftDocs](https://github.com/AzureADQuickStarts/NativeClient-iOS) ... @oldalton Could you kindly point me in the right direction?

**Comment by oldalton** [comment]
Unfortunately, I'm not very familiar with easy tables or MicrosoftAzureMobile. It sounds like you're getting an access token successfully from ADAL, but there's some kind of an exception when you're trying to use the token. It might be that token is valid, but is missing some information. Or you're passing unexpected information to MicrosoftAzureMobile SDK. Therefore, I suggest to open an issue on the [MicrosoftAzureMobile Github page](https://github.com/Azure/azure-mobile-apps-ios-client).

**Comment by oldalton** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
