### ISSUE TITLE
update common endpoint behavior similar to adal.net

### ISSUE THREAD

**Issue by omercs** [AzureAD/azure-activedirectory-library-for-objc#135]
.NET/WinRT/WinPhone

Once the first call is made to common endpoint and the tenant ID is returned by AAD, the Authority property in AuthenticationContext is switched to the specific tenant.

The token is also cached under the specific tenant.
Implications: 
a. If a second call within the same context has user and/or resource arguments which refer to a different tenant, the call fails.
b. If a context is created with common authority, the cache will NOT be hit on the first call.
c. If a context is created with a specific tenant, the cached tokens acquired from common authority can be matched (and vice versa).

**Comment by RandalliLama** [comment]
This will be addressed as part of design for a future major release.
