### ISSUE TITLE
Prompt behaviour "select account" is missing

### ISSUE THREAD

**Issue by mjcheetham** [AzureAD/azure-activedirectory-library-for-objc#1379]
In ADAL.NET (desktop) the available [prompt behaviours](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/68d7dea3643e075be85abbca1ab88ba614465541/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/WinCommon/PromptBehavior.cs) are:

- Auto
- Always
- Never
- RefreshSession
- SelectAccount

..however in the Objective-C implementation the 'select account' option is missing:

https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/0ae4f958c3722d210d08b60b22d0bed5300ba7f3/ADAL/src/public/ADAuthenticationContext.h#L48-L83

To support an authentication scenario where our customers are housed in multiple tenants, we need the ability to offer the account selection experience.

As far as I am aware the prompt behaviours correspond to adding `prompt=<value>` to the initial authentication request, for example `prompt=select_account`, so I don't see a reason why this was omitted from the Objective-C implementation (unless I'm missing something?).

Would it be possible to have the 'select account' prompt behaviour added?

**Comment by antrix1989** [comment]
This feature was added in [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-objc). Please use it instead of ADAL library.
