### ISSUE TITLE
ADAL error on latest cocoapods

### ISSUE THREAD

**Issue by nhart12** [AzureAD/azure-activedirectory-library-for-objc#1392]
On latest version of Cocoapods and ADAL 4.0.0 when I run my app I'm getting the following error: this works on previous cocoapods vesrion 1.5.3  . I have ADAL added to an embedded framework in my project podfile:
target 'MyApp' do
end
target 'MyAppCore' do
    pod 'ADAL'
end

dyld: Library not loaded: @rpath/ADAL.framework/ADAL
  Referenced from: /Users/nathanhart/Library/Developer/Xcode/DerivedData/MyApp-hgukqaxonkuwzablvktyymrxogmf/Build/Products/Debug-iphonesimulator/MyAppCore.framework/MyAppCore
  Reason: image not found

**Comment by oldalton** [comment]
Is this still an issue?

**Comment by nhart12** [comment]
hmm, I don't even remember creating this issue so I'm assuming no it's not still an issue 😃
