### ISSUE TITLE
Does ADAL v4.0.0 work with Workplace Join on macOS?

### ISSUE THREAD

**Issue by macblazer** [AzureAD/azure-activedirectory-library-for-objc#1396]
I tried updating from v2.7.7 to v4.0.0 (via CocoaPods) in my Mac app.  Nicely, there were no code changes required in my code.  However when calling acquireToken with deviceid claims in the extraQueryParameters the user was not prompted for Keychain access for the Workplace Join certificate, and the tokens returned from Azure did not have the computer's device ID inside it.

The specific extraQueryParameters we send is 

`claims=%7B%22access_token%22:%7B%22deviceid%22:%7B%22essential%22:true%7D%7D%7D&domain_hint=test.example.com
`

where the "text.example.com" is the actual Azure domain that we're authenticating against.

Is v4.0.0 expected to work with the Workplace Join certificate and the deviceid claim?

**Comment by pawelkijowskizimperium** [comment]
@macblazer has this been resolved? did you receive any update on this issue? I am facing similar problem.

The deviceid is not returned.

**Comment by macblazer** [comment]
I think ADAL is going to be deprecated in favor of MSAL.

https://github.com/AzureAD/microsoft-authentication-library-for-objc

I have begun converting my code to MSAL which does support Workplace Join on macOS.
