### ISSUE TITLE
we are using ADAL in project user is not able to login he tried reinstalling app but no sucess

### ISSUE THREAD

**Issue by xcodeApps** [AzureAD/azure-activedirectory-library-for-objc#1405]
Not able to login in the device here is the console log which i got from the backend 

ADAL 2.6.3 iOS 11.3 [2019-04-05 05:25:53 - 2F42BAE1-5CC2-4328-A2E4-703CE265F48A] ERROR: Error raised: (Domain: "ADKeychainErrorDomain" Code: -34018 ProtocolCode: "(null)"

**Comment by oldalton** [comment]
@xcodeApps, The error you're seeing means errSecMissingEntitlement. It likely means you haven't added "com.microsoft.adalcache" into your app's entitlements correctly. Please follow the guidance [here](https://github.com/AzureAD/azure-activedirectory-library-for-objc#ios) and let me know if you're still experiencing issues.
