### ISSUE TITLE
Login prompt should not allow user to change user id when type on ADUserIdentifier is set to RequiredDisplayableId

### ISSUE THREAD

**Issue by jboulter11** [AzureAD/azure-activedirectory-library-for-objc#1406]
## Repro Steps
1. call `ADAuthenticationContext.acquireToken` and pass an `ADUserIdentifier` with type set to `RequiredDisplayableId`.
1. User taps "Sign in with another account", changes the user id and finishes login on that id.
1. User is returned to our app and we must present an error because we didn't get a successful login on the required id.
1. User has to change the id in our app and sign in again.

## Desired Steps
1. call `ADAuthenticationContext.acquireToken` and pass an `ADUserIdentifier` with type set to `RequiredDisplayableId`.
1. User does not see "Sign in with another account", must come back to our application via the cancel button to change the id.

The issue is that inside the prompt the user can still tap the "Sign in with another account" button and change the email, even though we're 100% certain that if they do that we'll fail authentication, requiring the user to come back to us, be provided with an error, and then have to login from scratch again.

The user should not be given this option when `ADUserIdentifier`'s `type` is `RequiredDisplayableId`.

**Comment by oldalton** [comment]
Thanks for the question. By design, RequiredDisplayableId ensures a client side only check, it doesn't enforce user id inside the web view. That's because client side doesn't have a good mechanism to lock userId for the server, login_hint that is passed is served as a hint only.
