### ISSUE TITLE
Keep me signed in prompt is does not comes after entering the credentials

### ISSUE THREAD

**Issue by pratik-jaiswal** [AzureAD/azure-activedirectory-library-for-objc#1423]
I'm currently using ADAL 4.0 framework. But after log in there should be one page asking for stay signed in or not, But that page never appears. While using it in a webView that page is coming as expected. But i can not depend on the caching/cookie mechanism of WKWebView because of security concerns. Is there any work around for this? Please let me know.

**Comment by oldalton** [comment]
Thanks for the question. ADAL relies on tokens to provide silent SSO after first sign in, and therefore there's no need for an additional keep me signed in prompt (although ADAL doesn't actually control it by itself). Do you have any issues with relying on tokens and SSO through cache?
