### ISSUE TITLE
When the compatible MAM SDK will be released for ADAL 4.0.0

### ISSUE THREAD

**Issue by apecodingman** [AzureAD/azure-activedirectory-library-for-objc#1425]
For ADAL 4.0.0, when the compatible MAM SDK using WKWebView will be released
------
Note that this version is not yet compatible with the latest MAM SDK, as it requires WKWebView support. If you're using MAM SDK, please use ADAL 2.7.x until we update MAM SDK to support WKWebView.

**Comment by oldalton** [comment]
Let me follow up on this question. Thanks!

**Comment by apecodingman** [comment]
Why asking this question is we tried different ADAL version like 2.7.X and found only ADAL 4.0.0 can support SAML 2.0 authentication with our internal ADFS server. For 2.7.x, it seems it only works when authenticate with Azure AD. So want to know is there a release date for the new Intune lib which compatible with ADAL 4.0.0.
