### ISSUE TITLE
[ADAL4.0]The webview object cannot be read from ADWebAuthDidFinishLoadNotification

### ISSUE THREAD

**Issue by ruixi1994** [AzureAD/azure-activedirectory-library-for-objc#1426]
Office need the object from ADAL in some test scenarios when we don't pass our own webView object. Please help put it back when post this notification.

This is what I add in Office code to make it work:
//APEX_BACK_PORT: Sent webView as object of this notification to support testkit
//TODO: Opened issue for ADAL, remove it after ADAL had the fix
+ (void)notifyWebAuthDidFinishLoad:(NSURL *)url webView:(id)webView
{
    if (s_webAuthDidFinishLoadNotificationName)
    {
        NSMutableDictionary *userInfo = [NSMutableDictionary new];
        if(url) {
            userInfo[@"url"] = url;
        }
        if(webView) {
            userInfo[@"webView"] = webView;
        }
        [[NSNotificationCenter defaultCenter] postNotificationName:s_webAuthDidFinishLoadNotificationName
                                                            object:nil
                                                          userInfo:[userInfo count] > 0 ? userInfo : nil];
    }
}

Please check whether we can have it with next release and I can remove this back_port. Thanks!

**Comment by oldalton** [comment]
This should be fixed in 4.0.1.
