### ISSUE TITLE
How does one switch users

### ISSUE THREAD

**Issue by fowlerp-qlik** [AzureAD/azure-activedirectory-library-for-objc#1427]
We have the desire to switch the user we use to login with (via MS Authenticator) from A to B. We open our ADA enabled App and presses login and no surprise the SSO kicks in and we are logged in as A. We remove A from the MS Authenticator account list and still the same behaviour: we get logged in as A. We un-enroll and delete all Apps (MS Company Portal, MS Authenticator, our App) and start all over again. Upon login via our App we are not prompted to pick an account and again logged in as A.
 
What is required to cause MS Authenticator to forget about A?  Do we need an explicit logout function within our App that removes the appropriate ADAL keychain items?

**Comment by oldalton** [comment]
Thanks for the question. 
Just one thing to confirm. In the step 2 (We remove A from the MS Authenticator account list and still the same behaviour: we get logged in as A) - do you see an app redirecting to the Authenticator app. Or SSO is silent without any UI changes?

If SSO is silent, then yes, you should clear ADAL cache as well. You can do so by calling [ADKeychainTokenCache removeAllForUserId:clientId:error] on the application side.

**Comment by jakkornat** [comment]
Clearing cache does not work properly. Please find the issue here: 
https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1424.

**Comment by oldalton** [comment]
@jakkornat, thanks for the reference. Can you please clarify which ADAL version are you seeing this issue with? @fowlerp-qlik, could you please clarify the user experience? Thanks!

**Comment by jakkornat** [comment]
Use 4.0.0 with WKWebKit support.

**Comment by fowlerp-qlik** [comment]
We are not redirected but are logged in silently. I will try calling 
[ADKeychainTokenCache removeAllForUserId:clientId:error] during our App's logout flow.

**Comment by jasoncoolmax** [comment]
@fowlerp-qlik are you still facing the issue? or it works for you? :)

**Comment by oldalton** [comment]
Closing this issue as stale. Please reopen if needed.
