### ISSUE TITLE
ADAL 2.x and Latest Intune MAM SDK

### ISSUE THREAD

**Issue by andrejacobs** [AzureAD/azure-activedirectory-library-for-objc#1428]
Hi,

Please forgive my ignorance. I am using CocoaPods and thus far have been using the recommended '~> 4.0' for the ADAL pod.

Everything was working fine until I wanted to test that Intune MAM still works. Surprise surprise the app just quits as soon as the auto intune enrollment happens.

I noticed here / Intune repro that you have to use version 2.x of ADAL with Intune.

I changed my Podfile to have '~> 2.7' and it only fetches version 2.7.9 with a pod install.
Noticed that there are version after that like 2.7.12.

How do I ensure that I can get the latest working ADAL that also works with the latest Intune MAM (2x Swift frameworks)?

Please help me, I am desperately trying to get a feature out the door before the end of the week for Q2.

Many thanks!

**Comment by oldalton** [comment]
Hi @andrejacobs. You can configure your CocoaPods file to fetch a particular ADAL version, e.g. 2.7.12. 

pod 'ADAL', '2.7.12'

We're also working on having ADAL 4.0.0 fully supported, and we're sorry for this temporary inconvenience.
