### ISSUE TITLE
AADSTS900384: JWT token failed signature validation

### ISSUE THREAD

**Issue by smudireddy** [AzureAD/azure-activedirectory-library-for-objc#1433]
{ domain: ADOAuthServerErrorDomain code: 202 protocolCode: invalid_request  idtype = RequiredDisplayableId authority host: login.windows.net #####

ADAL-Auth: response received [Error with code: AD_ERROR_SERVER_OAUTH Domain: ADOAuthServerErrorDomain ProtocolCode:invalid_request Details:**AADSTS900384: JWT token failed signature validation [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client**:']

**Comment by smudireddy** [comment]
What can cause the error **AADSTS900384**  while authenticating the user in **.US**  domain of the Azure cloud ?

**Comment by smudireddy** [comment]
[ADAL_for_ios_App_Auth_Issue.txt](https://github.com/AzureAD/azure-activedirectory-library-for-objc/files/3410576/ADAL_for_ios_App_Auth_Issue.txt)

**Comment by smudireddy** [comment]
Please help me to resolve the error **AADSTS900384**

**Comment by oldalton** [comment]
@antrix1989, can you please take a look?

**Comment by smudireddy** [comment]
Application Manifest

[MaaS360-SSO-App.txt](https://github.com/AzureAD/azure-activedirectory-library-for-objc/files/3429369/MaaS360-SSO-App.txt)

**Comment by smudireddy** [comment]
Request:  

https://sts.yulista.com:443/adfs/ls/?login_hint=matthew.grossman%40yulista.com&wfresh=0&wauth=http%3a%2f%2fschemas.microsoft.com%2fws%2f2008%2f06%2fidentity%2fauthenticationmethod%2fpassword&client-request-id=4621bb04-2118-4194-8192-0555ba2d096a&username=matthew.grossman%40yulista.com&wa=wsignin1.0&wtrealm=urn%3afederation%3amicrosoftonline.us&wreply=https%3a%2f%2flogin.microsoftonline.us%2flogin.srf&wctx=estsredirect%3d5%26estsrequest%3drQIIAY1TPY_jZBBeJ7thd0FitUKwxRV7EiCE5KydxI53q7M3cT78tYn9OrF1UvTacRIntl_HdhzHDbqKK9GJig4qdAUSVOjoKKm25SpKdBII3Q9AeI-PguqamdHomZlHo-c5PqhV6Sp1ipEfl8kqefU-c0nRjlVzcOKyZuMNEpL4pVOHuGUxDu3YBMHQMDo9Ptn_4T5_dv9z9tGTA_AMP1o-xT70IYzrNHF1cWEjvzpzLSfy3GBV_ac_Q5GL4ovvMewWw37FsCelez5MkoWzrc4jFMc-DB7sNp4bJ7BaLLgtYc9LbyvsJlnU7kIxnTsvSgcemrvBy9JRsc6fhChOvij_sh8Nej3WkV152suJXNKNpQaMpQWk5lCNLZaQQSJLq0iXi1pNDFICW4IUdUkGTaCB9U5t6aKmGdu4xYkiJ7ptv2VGztxH2pKPx20V4vPN2KbjrrGT-GxujnN2p_mCugNELNheT5xORZFBqRhTct5VkCjV--I11SfbqZI362zWdUV3OpnF1mC13S7aFDf19PUIN3xR3oHJTd5P-YCTTCN0Z40FDwJva44WwOjyyPTYoL0Z6h4ABhVqFCUM9P4G8J5gQzwEPmUMTKenNzcrAEd9ECy8te44Jj1yhxTHxSsnXfo4t25QaeIPB9xO96g80sMmsvi12lGosT_SYj2DOk_OBWJ-o24aodlfK6tQaBmqx0xS1c16bSmVc8mkFY1JOGGgTkBdsiRuPc2ZlEulJTc1Ojyeud329tri-vE12sIWCyXey-wbtie1462wbDEFyM5YJK0QyIRLGsfJWVpLit9GZlYHtQ6gcxp3IDUwaEqBAQx8f8FHDd4EnjICFt4fUiY0m7638vq5b3YQgHqIRsPVwCxwVkdHhlbj5jfxIODGZmfmUYrp0eF4FOyEpRZoN5N5q1OTugojbbRkbGfS0DVyqYVEhWsmsrgjMkEc9Na5DFvu2ua2uTrpsCz5tHxvkSRhXGh7HsFwUfVdu9AsmiV3Ur34rlwpko-C233sxf67h6WTytnB-d5HGFG6Ojx866R8hp3vvdz_4LUc8tVBYa8vH3792-9_ftJ-9Ol76bff_Lz3WQX7sXL631UUFHNOdRP_VCm7ivpHpfT4jb1nRw_-JfnKJNX_w--o_s3zQoaJiwLoXXtoM-WdqRO9ajw_fqdGkJc40cRJ5pxsXBHMFdUwH7-J_QU1&ssoCookie=01b87591-125e-406a-8b40-be695b71180b";

**Comment by smudireddy** [comment]
https://login.microsoftonline.com/common/oauth2/token?x-client-Ver=2.6.5

**Comment by smudireddy** [comment]
Response: 

{ domain: ADOAuthServerErrorDomain code: 202 protocolCode: invalid_request  idtype = RequiredDisplayableId authority host: login.windows.net #####
18/07/2019 10:47:13:925|FLMSOffice365Client|authenticateWithResourceId:completionHandler:withPromptBehavior:[26020]|355<Info>: ADAL-Auth: response received [Error with code: AD_ERROR_SERVER_OAUTH Domain: ADOAuthServerErrorDomain ProtocolCode:invalid_request Details:AADSTS900384: JWT token failed signature validation [Reason - The provided signature value did not match the expected signature value., Thumbprint of key used by client: '33AA57ED11E8ADA2ECA6B7C97910A34B1B944617', Found key 'Start=10/14/2018 00:00:00, End=10/14/2020 00:00:00']

**Comment by smudireddy** [comment]
[iOS_App_ADAL_2_7_12_Error_AADSTS900384.txt](https://github.com/AzureAD/azure-activedirectory-library-for-objc/files/3429396/iOS_App_ADAL_2_7_12_Error_AADSTS900384.txt)

**Comment by smudireddy** [comment]
Hi Sergey Demchenko,

Could you please check this error **AADSTS900384** possibilities.

**Comment by antrix1989** [comment]
Hi @smudireddy, I am following up on this with our server team. I will update you once I get a reply from them.

**Comment by smudireddy** [comment]
Hi Sergey Demchenko,

ADAL + Network trace logs for more details.

[ADAL_For_iOS_JWT_Token_Issue.txt](https://github.com/AzureAD/azure-activedirectory-library-for-objc/files/3444875/ADAL_For_iOS_JWT_Token_Issue.txt)

**Comment by antrix1989** [comment]
Hi @smudireddy, thanks for the logs. Could you try to use `login.microsoftonline.us` authority instead of `login.microsoftonline.com`? Please let me know if it helped.

**Comment by smudireddy** [comment]
Hi Sergey Demchenko,

We will try that option. 
FYI .. Android agent ADAL module working with  login.microsoftonline.com for the same customer tenant and with the same app configuration.

**Comment by antrix1989** [comment]
Hi @smudireddy, that is interesting. We will take a look on the difference between iOS and Android. Were you able to authenticate using login.microsoftonline.us?

Also, I cleaned your personal data from this thread, please send all your private info/logs to my email (sedemche@microsoft.com) instead. Thanks!
