### ISSUE TITLE
xcodebuild fails after upgrading from ADAL 2.6.6 to 2.7.12 or 4.0.0

### ISSUE THREAD

**Issue by pawelkijowskizimperium** [AzureAD/azure-activedirectory-library-for-objc#1434]
I build ADAL 2.6.6 from source like so:

xcodebuild -UseNewBuildSystem=NO -target "ADAL iOS" -configuration Release -arch arm64 -arch i386 -arch armv7  only_active_arch=yes defines_module=yes -sdk "iphoneos"

After upgrading to 2.7.x or 4.0.0

I get the following error:

**xcodebuild: error: The project 'ADAL.xcodeproj' does not contain a target named 'ADAL'.**

I looked at your python build script and it looks like you build with **-scheme "ADAL iOS"**, I tried that and I get the following error:

**clang: error: invalid iOS deployment version '-miphoneos-version-min=12.2', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]**

How can I build ADAL 4.0.0 or 2.7.x from the command line? Could you pls post the xcodebuild command?

**Comment by oldalton** [comment]
Hi, @pawelkijowskizimperium. Are you checking out ADAL directly or using CocoaPods/Carthage? If you're checking it out directly, please make sure you run "git submodule update --init" since latest ADAL versions have a submodule dependency.

**Comment by pawelkijowskizimperium** [comment]
@oldalton I checkout the code directly.

**git submodule update --init** solved the problem.

Thank you.
