### ISSUE TITLE
ADAL 4.0.0 "pod install" fails with error

### ISSUE THREAD

**Issue by pawelkijowskizimperium** [AzureAD/azure-activedirectory-library-for-objc#1435]
Error:

[!] CocoaPods could not find compatible versions for pod "ADAL":
  In Podfile:
    ADAL (~> 4.0)

Specs satisfying the `ADAL (~> 4.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by peyter213** [comment]
I just tried different deployment targets, it looks like ADAL 4.0 requires a minium deployment target of 10.0

Should definitely add this to the documentation

**Comment by oldalton** [comment]
Thanks for pointing this out. Yes, we dropped iOS 9 support in ADAL 4.x. Will update documentation, thanks!

**Comment by pawelkijowskizimperium** [comment]
What's the latest ADAL version supported on iOS 9? is it ADAL 2.7.x?

**Comment by oldalton** [comment]
2.7.x still lists iOS 9 as supported version, but we don't actively develop it anymore. 2.7.x will have bug and security fixes, but not new features. All new features would go into ADAL 4.x and MSAL. Can you please clarify why do you need iOS 9?

**Comment by pawelkijowskizimperium** [comment]
@oldalton supporting iOS 9.0 is requirement dictated by our customers. Thanks for your support.
