### ISSUE TITLE
Does ADAL v4.0.0 compatiable with iOS 13 Beta versions?

### ISSUE THREAD

**Issue by bsg123** [AzureAD/azure-activedirectory-library-for-objc#1436]
Using ADAL v4.0.0 in my app. Its working fine in iOS 12.x. But when I tested in the released iOS 13 Beta versions, Azure Webview is presented on a button tap, Upon entering the valid credentials, the web view dismisses but with an error stating "**Keychain failed during'retrieve wpj identity attr' operation**". And I'm not able to login to the App. 

Error Details:
(lldb) po result
▿ Optional<ADAuthenticationResult>
  - some : (error=Error with code: -34018 Domain: ADKeychainErrorDomain ProtocolCode:(null) Details:Keychain failed during "retrieve wpj identity attr" operation. Inner error details: Error Domain=ADKeychainErrorDomain Code=-34018 "(null)", mrrt=NO, status=AD_FAILED, item=(null), correlationId=F9WES9AC-D312-567B-950D-29856D0C2RF1, authority=(null))

Thanks for any help in advance.
<img width="346" alt="Screenshot 2019-07-26 at 1 11 59 PM" src="https://user-images.githubusercontent.com/9211820/61934908-02082c00-afa7-11e9-88b6-c2600aac340b.png">

**Comment by antrix1989** [comment]
Hi @bsg123, -34018 means "A required entitlement isn't present." 
Please make sure you have enabled keychain sharing in your target.

**Comment by oldalton** [comment]
@bsg123, can you try with the latest 4.0.1 release and let us know if the error went away? Thanks! I wasn't able to reproduce this on my end.

**Comment by ImanuelChen** [comment]
Looks like I didn't have `com.microsoft.adalcache` in my keychain groups. But adding it fixes the issue! Thanks @antrix1989!

Any idea why this is not required on iOS 12?

**Comment by himanthmaddi** [comment]
It is returning same error even I have `com.microsoft.adalcache` in my keychain groups. 

iOS version is 13.1.2 and ADAL version is 2.7.15.

**Comment by antrix1989** [comment]
@himanthmaddi did you modify default keychain group in ADKeychainTokenCache? If you still have this issue, please send me your full ADAL log to sedemche@microsoft.com.

**Comment by himanthmaddi** [comment]
@antrix1989 I have fixed this by updating ADAL library to 4.0.3.
