### ISSUE TITLE
Can this library be used for apps that are not in the same app group?

### ISSUE THREAD

**Issue by SebastianCiuca** [AzureAD/azure-activedirectory-library-for-objc#1442]

**Comment by antrix1989** [comment]
Hi @SebastianCiuca. Yes, it can be used with different app or keychain groups. The only drawback is that apps will lose keychain level [SSO](https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/sso). If you are considering using ADAL for the new project or you haven't integrated it in your project yet, I recommend you using our [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-objc) library instead.

**Comment by SebastianCiuca** [comment]
Thank you!
