### ISSUE TITLE
Is ADAL 2.7.12 compatible to iOS 13?

### ISSUE THREAD

**Issue by ddrdjboy** [AzureAD/azure-activedirectory-library-for-objc#1451]

**Comment by OxyFlax** [comment]
On my side I'm having issues with 2.7.13 + authenticator. Issue was previously fixed but it came back on iOS 13 beta 8 when I tried.

**Comment by oldalton** [comment]
Please use 2.7.14 release: https://github.com/AzureAD/azure-activedirectory-library-for-objc/releases/tag/2.7.14

**Comment by oldalton** [comment]
I've also written up some additional considerations for iOS 13: https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/ADAL-is-not-able-to-complete-brokered-authentication-on-iOS-13
