### ISSUE TITLE
UIWebView is deprecated

### ISSUE THREAD

**Issue by saddamakhtar88** [AzureAD/azure-activedirectory-library-for-objc#1460]
People have started receiving this warning when submitting apps that have references to UIWebView.

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs.

Apple Doc Ref:
https://developer.apple.com/documentation/uikit/uiwebview?language=objc

**Comment by oldalton** [comment]
Please Use ADAL 4.0.x that doesn't utilize UIWebView anymore.

**Comment by saddamakhtar88** [comment]
Thanks. I was looking @2.7.14 release where it is still in use.
