### ISSUE TITLE
ADAL 4.0.2 for iOS 13 release date?

### ISSUE THREAD

**Issue by ImanuelChen** [AzureAD/azure-activedirectory-library-for-objc#1461]
According to the Cocoapod docs (https://cocoapods.org/pods/ADAL), version 4.0.2 will be necessary for iOS 13. However, it doesn't look like 4.0.2 exists on GitHub yet. We would take 2.7.14, but UIWebView still exists in that version.

**What is the release date for 4.0.2?** With the uncertainty of the iOS 13 and Xcode 11 official release date, it would be nice to know when 4.0.2 comes out to better plan our next release.

**Comment by williamgp** [comment]
Yeah, what does this mean actually?
> NOTE: To work with iOS 13 you must have at least version 2.7.14 or 4.0.2

Sounds rather ominous. Is this referencing building against the iOS 13 SDK (Xcode 11) ? Ie, if we are building against the iOS 12 SDK (Xcode 10) are we fine?  Or do we as developer need to rush to get 4.0.2 into our app as soon as it's released? (Which, in that case, hopefully is any day now... )

**Comment by oldalton** [comment]
It's reflecting building against iOS 13 SDK (Xcode 11). If you're building against iOS 12 SDK, you should be fine. 4.0.2 will be released shortly as well in a couple of days. I'll post an update here when it happens. You can also point to release/4.0.2 branch in the meantime to unblock your testing.

**Comment by ImanuelChen** [comment]
I can build 4.0.1 with Xcode 11 though

**Comment by oldalton** [comment]
Hi, yes, you'll be able to build it, but iOS brokered authentication will always fail when handling response. This is because Apple made a breaking change and our SDK is not getting back sourceApplication in AppDelegate callback anymore.

ADAL 4.0.2 has been released: https://github.com/AzureAD/azure-activedirectory-library-for-objc/releases/tag/4.0.2

**Comment by oldalton** [comment]
I've also written up some additional considerations for iOS 13: https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/ADAL-is-not-able-to-complete-brokered-authentication-on-iOS-13
