### ISSUE TITLE
Broker authentication not working with 2.7.14 and iOS 13.1

### ISSUE THREAD

**Issue by Stoexn** [AzureAD/azure-activedirectory-library-for-objc#1462]
I use the recently released version 2.7.14 with an iPhone running iOS 13.1 beta 2.
Instead of the authenticator the WebView opens and returns a keychain error in the acquiretoken callback.
Everything works on iOS 12

**Comment by Stoexn** [comment]
Also tried building it with XCode 10 and XCode 11

**Comment by oldalton** [comment]
Hi
 
Please make sure you follow the guidance in the release notes: https://github.com/AzureAD/azure-activedirectory-library-for-objc/releases/tag/2.7.14
 
Copying from here:
 
Note, when updating to this release, make sure you update your LSApplicationQueriesSchemes in the Info.plist.
New value should be:

```
<key>LSApplicationQueriesSchemes</key>
<array>
     <string>msauth</string>
     <string>msauthv3</string>
</array>
```

This is necessary to compile with Xcode 11.
Thanks,
Olga

**Comment by oldalton** [comment]
Please also make sure your keychain access groups are configured correctly. Can you please clarify which error are you seeing?

**Comment by oldalton** [comment]
I've also written up some additional considerations for iOS 13: https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/ADAL-is-not-able-to-complete-brokered-authentication-on-iOS-13

**Comment by Stoexn** [comment]
Not sure what caused the problem as I already did everything described in the linked wiki page. But re-installing Authenticator solved it

**Comment by pgawlowski** [comment]
Same issue here. 
Reinstall not helping. What is more it is still possible to auth via web however. it claims that device is not enrolled, which is not valid.
