### ISSUE TITLE
ADAuthenticationSettings.defaultKeychainGroup annotated as nonnull even though the documentation says it can be nil

### ISSUE THREAD

**Issue by ImanuelChen** [AzureAD/azure-activedirectory-library-for-objc#1463]
https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/8aa48ac18eb96d5f70bf807cbf171616d55b8b4f/ADAL/src/public/ADAuthenticationSettings.h#L81

The documentation in code says that `defaultKeychainGroup` can be `nil` but the method is annotated as `nonnull`. Therefore, when I call `[ADAuthenticationSettings setDefaultKeychainGroup:nil]`, I get a "Null pased to a callee that requires a non-null argument" warning.

Also, just fyi, the documentation on the repo's GitHub home page (https://github.com/AzureAD/azure-activedirectory-library-for-objc#keychain-setup) states to use a method that does not exist (`[[ADAuthenticationSettings sharedInstance] setSharedCacheKeychainGroup:nil]`, which I assume needs to be changed to `setDefaultKeychainGroup:nil`).)

**Comment by oldalton** [comment]
This should be fixed in latest ADAL release. Please reopen the issue if you're still seeing it.
