### ISSUE TITLE
Deprecated API Usage (UIWebView)

### ISSUE THREAD

**Issue by jakkornat** [AzureAD/azure-activedirectory-library-for-objc#1465]
Hi, 

I've just tried to upload the new version of the app to App Store, but unfortunately I get a message from the Apple itself, sounds like this:

"Dear Developer, 

We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect."

I've also checked twice and the only place there is any usage of UIWebView is the ADAL itself. 

PS. If duplicated somehow, please redirect me :) 

All best!

**Comment by oldalton** [comment]
Thanks for submitting the question.
Please switch to ADAL 4.0.x. It uses WKWebView instead of UIWebView. 
Alternatively, you can switch to our MSAL library which is the recommended library going forward: https://github.com/AzureAD/microsoft-authentication-library-for-objc

**Comment by jakkornat** [comment]
Thanks for your support :)
