### ISSUE TITLE
Password is removed from  the password box - iPadOS 13 - iPad pro

### ISSUE THREAD

**Issue by vibhootitatva** [AzureAD/azure-activedirectory-library-for-objc#1473]
When we connect ADFS Sites For the second time and go for Login,  Password is removed from the password Box on signin button clicked.

We get this issue only in iPad Pro (12.9) Second generations (iPadOS). 

For the First time, there is no user Login Hint, So we set up like this 
`[authContext acquireTokenWithResource:strResouceURL clientId:strClientID   redirectUri:[NSURL URLWithString:strRedirectURI] completionBlock:^(ADAuthenticationResult *result) {  if (AD_SUCCEEDED != result.status){ //NSLog(@"Error:%@",result.error.errorDetails); } else{ //NSLog(@"ADFS Token : %@",result.accessToken); completionBlock(result.accessToken); } }]`

And for the Second time, we have previous user login, so we specify their username in Hint, that we can see in the pre filled in the Email on ADFS Sites.

`[authContext acquireTokenWithResource:strResouceURL clientId:strClientID redirectUri:[NSURL URLWithString:strRedirectURI]
 promptBehavior:AD_FORCE_PROMPT userIdentifier:nil
 extraQueryParameters:[[NSString stringWithFormat:@"login_hint=%@",username] stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLHostAllowedCharacterSet]] completionBlock:^(ADAuthenticationResult *result) { if (AD_SUCCEEDED != result.status){ // display error on the screen
} else{//NSLog(@"ADFS Token : %@",result.accessToken);  completionBlock(result.accessToken);}}]`
 
Let us know what is wrong here. We have ADAL version 2.7.7

**Comment by tatvarajendra** [comment]
Any update?

**Comment by vibhootitatva** [comment]
Any update?

**Comment by oldalton** [comment]
ADAL doesn't have direct control over what is happening inside the webview. However, iOS 13 might have different UserAgent on iPads. That's Apple's change. If your ADFS environment depends on the user agent, make sure it can also recognize new iPadOS user agents.

**Comment by vibhootitatva** [comment]
First thing is, we are not facing the issue in iPad OS. Its device specific. We are facing the issue only in  iPad Pro (12.9) Second generations.

we don't think its user agent issue because  according to user agent guideline : https://forums.developer.apple.com/thread/119186, we have changed the setting and in none of the case, we are able to reporduce the issue in another device having iPad OS, it means, its not user agent issue. its something else.

One more thing to highlight here, if we pass user detail in query string parameter in ADAL method then only we are having issue. If user enter password on ADAL page and click on "sign in" then password is getting blank and not allowing user to login.

but If I use method without query string parameter then its working fine. so there are some issue in method having query string. 

can you please help us here.

**Comment by oldalton** [comment]
What query string/parameter are you sending exactly? ADAL just passes them to the server, so I'm curious to see what exactly you're providing such as it impacts the behavior. Thanks.

**Comment by vibhootitatva** [comment]
Here Query string means user detail, I.e Login user ID. Once user login through the ADAL, we have their login ID, We pass using Key **login_hint**  like below code. 

`[authContext acquireTokenWithResource:strResouceURL
                                         clientId:strClientID
                                      redirectUri:[NSURL URLWithString:strRedirectURI]
                                   promptBehavior:AD_FORCE_PROMPT
                                   userIdentifier:nil
                             extraQueryParameters:[[NSString stringWithFormat:@"login_hint=%@",objLogin.login_Name] stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLHostAllowedCharacterSet]] completionBlock:^(ADAuthenticationResult *result) {
                                 if (AD_SUCCEEDED != result.status){
                                     // display error on the screen
                                 }
                                 else{
                                     completionBlock(result.accessToken);
                                 }
                             }];`

Here is the code for without query string, as we are considering this as a first time user. 

` [authContext acquireTokenWithResource:strResouceURL
                                         clientId:strClientID
                                      redirectUri:[NSURL URLWithString:strRedirectURI] 
                                  completionBlock:^(ADAuthenticationResult *result) {
                                      if (AD_SUCCEEDED != result.status){
                                          // display error on the screen
                                      }
                                      else{
                                          completionBlock(result.accessToken);
                                      }
                                  }];`

so Now, the issue is when one login through iPad Pro (12.9) Second generations (iPadOS). We usually having their login ID, And when we pass like query string as explained above, Password get black while clicking on **Sign in**   

This issue doesn't reproduced for first time user, as we don't pass their **login_hint** So, there is something with this **login_hint**.  But it is device specific, i.e iPad Pro (12.9) Second generations (iPadOS).

**Comment by oldalton** [comment]
Did this ever get resolved? I don't see anything unexpected from ADAL client side.

**Comment by vibhootitatva** [comment]
No, it's not yet resolved.

**Comment by oldalton** [comment]
Thanks for an update. Did you check if your proxy depends on user-agent string=

**Comment by vibhootitatva** [comment]
We are not sure, what exactly you want us to check here.

**Comment by jasoncoolmax** [comment]
Could you please try the following?
- Login using ADAL 4.0.5
- Login using Safari browser
See if the issue remains.

Based on the result from you, we will try to see what we can do as the next step.

**Comment by oldalton** [comment]
Closing this issue as stale. Please reopen if needed.
