### ISSUE TITLE
Keychain failed during "retrieve wpj identity attr" operation

### ISSUE THREAD

**Issue by himanthmaddi** [AzureAD/azure-activedirectory-library-for-objc#1477]
Though I have `com.microsoft.adalcache` in my keychain groups, am still facing this problem whenever a popup comes to enter credentials. But It is returning invalid credentials, if they are wrong. Throwing the above error for valid credentials. And I haven't changed the default `ADKeychainTokenCache`. Am not using any certificate based authentication. 

ADAL version -- 2.7.15
Xcode -- 11.0
iOS -- 13.1.2

It was working fine earlier before pushing the app from Xcode 11.

**Comment by oldalton** [comment]
Will be fixed in 2.7.16: https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/1478.
This should work in 4.x.

**Comment by himanthmaddi** [comment]
Yes, It's working in 4.0.3. Thanks.
