### ISSUE TITLE
Signing in Microsoft Teams free user not working

### ISSUE THREAD

**Issue by dzak83** [AzureAD/azure-activedirectory-library-for-objc#1481]
Hi,
When signing in with the MSA account (outlook.com), that is Microsoft Teams free user, I should get a token without claims (like OID etc..). I am getting that on Android ADAL version. However, when using this for iOS, it comes back with the error. Brokered auth is off. 

> TokenProviderException: IOS Auth error: AADSTS50020: User account '{EmailHidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '...' in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

It works fine on Android and on UWP for the same account, same app id. What do I miss?

More info about Teams free users: [https://docs.microsoft.com/en-us/microsoftteams/platform/troubleshoot/faq#teams-apps-and-authentication-with-guest-users-and-microsoft-teams-free](url)

We ran fiddler and it seems that on UWP, the call for the Teams Freemium account is redirected into https://login.microsoftonline.com/common/federation/oauth2, while on iOS it only goes to https://login.microsoftonline.com/common/oauth2

**Comment by oldalton** [comment]
Can you please specify which authority, clientId and resource you're passing to ADAL?

**Comment by oldalton** [comment]
I believe this got resolved by updating application configuration. Please reopen the issue if you're still seeing it. Thanks.

**Comment by dzak83** [comment]
Yes, yes. Thank you again for help!

**Comment by ShmilyLin** [comment]
> Yes, yes. Thank you again for help!

@dzak83 Hi, I encountered the same problem as you, how did you solve it?

Thanks

**Comment by dzak83** [comment]
> > Yes, yes. Thank you again for help!
> 
> @dzak83 Hi, I encountered the same problem as you, how did you solve it?
> 
> Thanks

@ShmilyLin in our case we didn't have passthrough explicitly enabled in our app id configuration (it was set to default) but from what I remember, the more appropriate way is to use “Microsoft Personal Accounts” as an allowed supported account type, and using MSAL library https://github.com/AzureAD/microsoft-authentication-library-for-objc to have full MSA support
