### ISSUE TITLE
ADTokenCache not persisted between app launches on OSX

### ISSUE THREAD

**Issue by aaronrogers** [AzureAD/azure-activedirectory-library-for-objc#1487]
I have a project with a iOS and OSX targets.  The iOS target works great where once the user signs in they're not prompted to log in again on next app launch.  However, on OSX, the user is prompted on each app launch.  It appears that the `ADTokenCache` is empty before signing in.  After signing in, there's an item in it.  Restart the app, and it's gone again.

I'm calling
```
- (void)acquireTokenWithResource:(nonnull NSString*)resource
                        clientId:(nonnull NSString*)clientId
                     redirectUri:(nonnull NSURL*)redirectUri
                 completionBlock:(nonnull ADAuthenticationCallback)completionBlock;
```
What am I doing wrong?

**Comment by oldalton** [comment]
This is not supported by ADAL. You need to persist it yourself. 
Alternatively, you can use MSAL library where this is supported: https://github.com/AzureAD/microsoft-authentication-library-for-objc

**Comment by aaronrogers** [comment]
Sounds good.  I'll check MSAL out.

Is there a reason why it works in iOS and not OSX?

**Comment by oldalton** [comment]
Until 10.15, macOS required different keychain implementation from iOS. ADAL never implemented it due to complexity, so we only implemented it in MSAL which is the authentication SDK going forward.

**Comment by aaronrogers** [comment]
Gotcha!  Thanks!

**Comment by oldalton** [comment]
Closing the issue. Please reopen if you have additional questions. Thanks!
