### ISSUE TITLE
Support for swift package manager?

### ISSUE THREAD

**Issue by dev-manishpandey** [AzureAD/azure-activedirectory-library-for-objc#1489]
Is it possible to add support for swift package manager ?

![Screenshot 2019-11-05 at 4 30 10 PM](https://user-images.githubusercontent.com/30525904/68202415-b58eac80-ffe9-11e9-8cfc-9e7a783dd9b7.png)

**Comment by antrix1989** [comment]
Hi @dev-manishpandey. We are not adding new features to ADAL. I recommend you switching to the [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/737) where we will add swift package manager.
