### ISSUE TITLE
ADAL cache not cleaning up in logout

### ISSUE THREAD

**Issue by thejaa** [AzureAD/azure-activedirectory-library-for-objc#1491]
Using ADAL (4.0.4)
Deleted session cookies , removed WKWebView data and URLCache in Logout. Still login not working (i.e with out asking details it is navigating to next screen).
// Removing URLCache
URLCache.shared.removeAllCachedResponses()

// Removing WKWebview
extension WKWebView {
func cleanAllCookies() {
HTTPCookieStorage.shared.removeCookies(since: Date.distantPast)
WKWebsiteDataStore.default().fetchDataRecords(ofTypes: WKWebsiteDataStore.allWebsiteDataTypes()) { records in
records.forEach { record in
WKWebsiteDataStore.default().removeData(ofTypes: record.dataTypes, for: [record], completionHandler: {})
print("Cookie ::: (record) deleted")
}
}
}
func refreshCookies() {
self.configuration.processPool = WKProcessPool()
}
}

// Removing ADKeychainTokenCache
ADKeychainTokenCache.defaultKeychain().removeAll(forClientId: clientID, error: nil)
ADKeychainTokenCache.defaultKeychain().removeAll(forUserId: useriD, clientId: clientID, error: nil)

// Deleting HTTPCookie
_ = HTTPCookie.self
let cookieJar = HTTPCookieStorage.shared

       for cookie in cookieJar.cookies! {
           cookieJar.deleteCookie(cookie)
       }
I am performing all above actions in logout. Still not working as expected. Did i missed any thing here.Could you please any help on this.

However if I quit the app after a logout, then the next login does ask for details as I would expect.

Thank in advance.

**Comment by oldalton** [comment]
It sounds like cookies in WKWebView. There're a few things you can try out:
1. Pass your own webview. That way you can control the cookie state of the webview and pass ADAL a "clean" webview without state.
2. Pass AD_PROMPT_ALWAYS as a prompt type. That will ensure that regardless of cookies, webview would prompt the user.
Let me know if any of these worked.

See a similar issue for additional discussion: https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1341

**Comment by thejaa** [comment]
@oldalton  Issue is solved by using AD_PROMPT_ALWAYS .

Thanks
