### ISSUE TITLE
identity provider 'live.com' does not exist in tenant 'Microsoft Services'

### ISSUE THREAD

**Issue by iNViTiON** [AzureAD/azure-activedirectory-library-for-objc#1493]
My **Flow** in "Microsoft Flow" stop working. It said that it's have a connection error. When I access "data -> connections" tab it's stuck with forever loading. I open browser console and found this error.

`Uncaught (in promise) ClientError: Unable to get token for audience 'a8f7a65c-f5ba-4859-b2d6-df772c264e9d'. Details: 'AADSTS50020: User account '{EmailHidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '6204c1d1-4712-4c46-a7d9-3ed63d992682'(Microsoft Flow Portal) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
Trace ID: 136907b5-e7b1-45ad-bc5b-e07eafde9c00
Correlation ID: 5d43e4d2-57f8-4c0b-a90f-d81072a69f65
Timestamp: 2019-11-18 07:02:39Z'.
    at F (https://psuxasia.azureedge.net/Content/retail/app.bc5b61b59f35c26b251b.2.js:1:483072)
    at s (https://psuxasia.azureedge.net/Content/retail/app.bc5b61b59f35c26b251b.2.js:1:24964)
    at Object.<anonymous> (https://psuxasia.azureedge.net/Content/retail/app.bc5b61b59f35c26b251b.2.js:1:1119103)
    at u (https://psuxasia.azureedge.net/Content/retail/common.82dbedd5ce0e279d5f19.2.js:128:25700)
    at c (https://psuxasia.azureedge.net/Content/retail/common.82dbedd5ce0e279d5f19.2.js:128:26002)`

I'm not sure how this happen but I suspect that it have a thing to do with my Azure Sphere setup. The document let me create tenant in Azure Active Directory. But I can't recall what have I done and the Azure Sphere document just updated and the instruction I following is now gone.

**Comment by oldalton** [comment]
What application_id are you using? Can you please also confirm that you're using ADAL Objective-C library as I've noticed some "js" logs in your report. Thanks.

**Comment by iNViTiON** [comment]
> What application_id are you using? Can you please also confirm that you're using ADAL Objective-C library as I've noticed some "js" logs in your report. Thanks.

I'm not sure how can I get the application_id?
I'm just using my Hotmail Microsoft account with Microsoft Flow. Not my own application.

**Comment by oldalton** [comment]
ok, thanks. And do you have Microsoft Authenticator app installed on the device?

**Comment by iNViTiON** [comment]
> ok, thanks. And do you have Microsoft Authenticator app installed on the device?

Yes.

**Comment by oldalton** [comment]
@iNViTiON, thanks a lot for the information. This seems like a clear bug on the Microsoft Flow side. I'll be next forwarding it to engineers on the Microsoft Flow side.

**Comment by franva** [comment]
facing the same issue, do we have any update?

**Comment by oldalton** [comment]
@franva, are you facing same issue with ADAL Objective-C library or with Microsoft Flow website? Thanks.

**Comment by franva** [comment]
sorry, not the same. I'm doing this with ASP.NET Core Web API .

**Comment by jasoncoolmax** [comment]
@franva Please report the issue in the ADAL .Net repo if you are using .Net.

**Comment by rohitnarula7176** [comment]
@franva Closing this issue for now.
