### ISSUE TITLE
README.md should probably mention "msauthv3"

### ISSUE THREAD

**Issue by bkarabanms** [AzureAD/azure-activedirectory-library-for-objc#1496]
On iOS13, the "msauthv3" scheme must be included in the LSApplicationQueriesSchemes list of the application's  Info.plist, as documented in the [release notes](https://github.com/AzureAD/azure-activedirectory-library-for-objc/releases/tag/2.7.14) and the [Wiki](https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/ADAL-iOS-13-support), but the [README](https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/README.md) only mentions "msauth" in its "Getting Started" session.

This can be confusing for new users of the library who probably won't read through all the release notes.

**Comment by rohitnarula7176** [comment]
@bkarabanms The directions to add msauthv3 is part of the "Quick Start" section of the Readme. Please see below:
https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/master/README.md#lsapplicationqueriesschemes
Please let me know if you have any additional questions.

**Comment by bkarabanms** [comment]
I hadn't seen the msuathv3 part in the master branch. The confusing part is that if you're just looking at the project's home page: https://github.com/AzureAD/azure-activedirectory-library-for-objc/ you see the content of the README in the "dev" branch, since this is the default branch and this branch hasn't been updated: https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/README.md

**Comment by rohitnarula7176** [comment]
@bkarabanms Thank you for pointing this out. I have created a PR to add the documentation for registering msauthv3 scheme to the ReadMe in the dev branch.
