### ISSUE TITLE
ADAL 2.5.1 domain hint with Authenticator not working

### ISSUE THREAD

**Issue by aleUnix** [AzureAD/azure-activedirectory-library-for-objc#1504]
the method in ADAuthenticationContext.h
"- (void)acquireTokenWithResource:(NSString*)resource
                        clientId:(NSString*)clientId
                     redirectUri:(NSURL*)redirectUri
                          userId:(NSString*)userId
            extraQueryParameters:(NSString*)queryParams
                 completionBlock:(ADAuthenticationCallback)completionBlock"

if the login process is managed from Microsoft Authenticator app, extraQueryParameters filled with value: "domain_hint=xxx.com" don't work.

This query params work correctly  in sts web page.

**Comment by aleUnix** [comment]
This issue remains present in the same way regarding the latest ADAL version 2.7.16

**Comment by oldalton** [comment]
Thanks, we agree that it might be useful to allow domain_hint in the broker, but we don't have an exact timeline for the fix yet. We'll update this issue once we have a timeline for the fix.

**Comment by antrix1989** [comment]
We don't have plans to fix this at the moment.
