### ISSUE TITLE
User not decoded on WebView

### ISSUE THREAD

**Issue by SagarPrajapati98** [AzureAD/azure-activedirectory-library-for-objc#1508]
When passing loginhint the actual value is different on the username textbox i think it's not decoded before displaying 

i am passing the loginhint by encoding by URLEncode but it's not decoded in webview it shows % and kind of value

**Comment by oldalton** [comment]
Looks like a duplicate of this one: https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1509

Can you please take a look at the resolution of that one and let me know if it resolves your issue as well.

**Comment by oldalton** [comment]
Closing this issue as it should be resolved in the latest ADAL version. Please reopen if you're still experiencing the issue. Thanks!
