### ISSUE TITLE
Getting error code as AADSTS650056 after launching Intune SDK integrated IOS app

### ISSUE THREAD

**Issue by pallavkumar112** [AzureAD/azure-activedirectory-library-for-objc#1515]
Hi All,

We have integrated IOS app with Intune SDK referring from sample app Wagr(https://github.com/Microsoft/Wagr-Sample-Intune-iOS-App). 
We have registered the app in our tenant environment and added some required permissions and got Application id and set redirect URI in there.

Enabled SSO login(silent/auto login) In the app using below methods those requires Application Id(client Id) and Redirect URI :

- (void)acquireTokenSilentWithResource:(nonnull NSString*)resource
                              clientId:(nonnull NSString*)clientId
                           redirectUri:(nonnull NSURL*)redirectUri
                       completionBlock:(nonnull ADAuthenticationCallback)completionBlock;

- (void)acquireTokenWithResource:(nonnull NSString*)resource
                        clientId:(nonnull NSString*)clientId
                     redirectUri:(nonnull NSURL*)redirectUri
                 completionBlock:(nonnull ADAuthenticationCallback)completionBlock;
				 
				 
According to the ADAL lib methods, We can’t send empty or null ClientID and redirect URI in the code base as methods parameters above are non-null values.

Added policy and user in our local tenant environment and downloaded app from Company portal and app worked fine(both MAM and MDM). We were able to achieve silent login and we were able to set all the policies applied in Azure portal to the app.

We have uploaded same app to app store , As there are different customers need this app.

One of our customer , Added the same app from app store and registered the app in their tenant environment. They have got different Application Id(Client Id) and they edited same Redirect URI what we have used for our local tenant. They have added policy and users in their environment as well.
Once they install app from Company portal and launch the app they are getting error as attached screenshot(Error code : AADSTS650056).

Please let me know what is wrong here and how to deploy the same app to different tenant as all tenant has different Application Id after registration in Azure portal. How other Intune app works from app store.

Thanks,
Pallav Kumar

<img width="140" alt="error" src="https://user-images.githubusercontent.com/51072934/73488166-6c72ac80-43ce-11ea-9777-adc75c411b84.png">

**Comment by pallavkumar112** [comment]
@msintuneappsdk

**Comment by pallavkumar112** [comment]
@oldalton Can you help please

**Comment by oldalton** [comment]
It looks like a configuration issue for the new clientId. Please make sure that the clientId you're using has listed AAD graph as one of its permissions for the client. If you've already done that and it still doesn't work, please provide a screenshot for you client permissions. Thanks.

**Comment by pallavkumar112** [comment]
Thanks @oldalton  for quick response. Please find the screenshot attached for client permissions.
<img width="891" alt="permissions" src="https://user-images.githubusercontent.com/51072934/73682914-4ce9c580-46e7-11ea-9d1c-746d0a3cf463.png">

**Comment by oldalton** [comment]
Thanks, can you please also add AAD graph to the list and see if it resolves the issue?

**Comment by pallavkumar112** [comment]
Thanks @oldalton.  Is there any specific permission needs to add under AAD graph? Please suggest.

**Comment by oldalton** [comment]
@pallavkumar112, this depends on what your app needs from the AAD graph. See here for description of different permissions: https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-permission-scopes

**Comment by pallavkumar112** [comment]
@oldalton  Customer has added AAD graph permission as well, but it din't help to resolve the problem. Please find the screenshot attached.
<img width="844" alt="AAD graph added" src="https://user-images.githubusercontent.com/51072934/74138162-1942fa00-4c17-11ea-9ae8-093462a368a1.png">

**Comment by oldalton** [comment]
Thanks, are you seeing exactly same error message after the change? Can you please provide the latest error message so that we could take a look at logs from our side?

**Comment by gkrishnan777** [comment]
same issue happens even after the AAD graph permission added.

**Comment by jasoncoolmax** [comment]
Could you please provide us the screenshot again after all the changes you have done? Such that I can further investigate from the server side.

**Comment by pallavkumar112** [comment]
@jasoncoolmax  We already have attached screenshot above.  Please find it below again:
<img width="844" alt="latest" src="https://user-images.githubusercontent.com/51072934/74640751-148dc100-5196-11ea-85c6-e25e7ef1f484.png">

**Comment by oldalton** [comment]
@pallavkumar112, sorry for the confusion. We'd like to see the latest screenshot of your error message like this, not the configuration: https://user-images.githubusercontent.com/51072934/73488166-6c72ac80-43ce-11ea-9777-adc75c411b84.png

To clarify, each error message contains a correlationId and a timestamp which lets us track down your request from our telemetry. We'd like to have the latest correlationId to investigate your issue accurately. Thanks!

**Comment by pallavkumar112** [comment]
Customer is getting same error message still, You can refer screenhsot in the issue details. Please find correlationId :  42313e6c-95d1-4b7d-8881-fb90100af47f

**Comment by jasoncoolmax** [comment]
@pallavkumar112 I checked the server logs, it shows that 

> AADSTS65001: The user or administrator has not consented to use the application with ID 'd658ce6b-6fc6-4491-bb50-099c264f53f0' named 'MultiLine for Intune (iOS)'. Send an interactive authorization request for this user and resource.

I am not an expert on portal settings. I search about it online, find [some people are facing the same issue and resolved it](https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi/issues/19). Could you please also try? :)

Let me know if that could resolve your issue.

**Comment by rohitnarula7176** [comment]
@pallavkumar112 Closing this issue for now. Please feel free to reopen if you still face any issues.
