### ISSUE TITLE
Make PDFView to fit in added view.

### ISSUE THREAD

**Issue by Narendra-Pandey** [AzureAD/azure-activedirectory-library-for-objc#1516]
I don't need horizontal scrolling in **APPDFViewController** Pdf view. I just wanted to fit the PDFView as specified View width.

Please let me how could I fit the pdf into added view.

**Comment by jasoncoolmax** [comment]
Could you please make sure you post the question in the correct repository? :)

**Comment by oldalton** [comment]
Closing this issue for now, as it seems not applicable to ADAL project. Please reopen if you still need help.
