### ISSUE TITLE
Move from ADALiOS, missing acquireToken with scope or policy 

### ISSUE THREAD

**Issue by Halfpint-Code** [AzureAD/azure-activedirectory-library-for-objc#1517]
We are moving from ADALiOS to ADAL due to the iOS13 issue and ADALiOS being deprecated. I have the pod added and building. I've looked into replacing the methods we were using and I don't see any method with scopes or policy. We need the policy.

We were using:
[authContext acquireTokenWithScopes: additionalScopes: clientId: redirectUri: identifier: promptBehavior: extraQueryParameters: policy: completionBlock:];

Is there a replacement for this? I didn't see a new method with these parameters.

**Comment by jasoncoolmax** [comment]
@Halfpint-Code I guess you were using our preview release for B2C. If so, you are recommended to switch to use MSAL to work with B2C. Please refer the following for more detials:
https://docs.microsoft.com/en-us/azure/active-directory/develop/config-authority#b2c

**Comment by Halfpint-Code** [comment]
Thanks, I'll give that a try

**Comment by oldalton** [comment]
Thanks, let us know if you find any issues.

**Comment by jasoncoolmax** [comment]
Close it because of no response. Please feel free to reopen it if issue persists.

**Comment by Halfpint-Code** [comment]
Hey,
So got big time sidetracked after contacting you guys. Finally getting around to implementing this. I am getting the error:

(lldb) po error
2020-03-04 09:18:27.431739-0600 RemoteInventory[4479:4223872] XPC connection interrupted
Error Domain=MSALErrorDomain Code=-50003 "(null)" UserInfo={MSALDeclinedScopesKey=(
    "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
), MSALGrantedScopesKey=(
    "/"
), MSALErrorDescriptionKey=Server returned less scopes than requested, MSALInvalidResultKey=<MSALResult: 0x1c02adb00>}

Myself and our backend developer have both looked into this a little. We found the following link but not sure it helps.
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/393

Do you know of any settings off-hand that might be affecting this that we should look into?

We are currently using com.microsoft.aad:adal:2.0.1-alpha with no issues right now. If we can get this working on iOS with MSAL, I believe we will likely be updating that as well for consistency.

Thanks

[../Logo/WithoutWire/woWire_LogoFinal%203-15-16%2072dpi.png]

Dillon Pint, Mobile Developer
WithoutWire Inventory Sciences
dillonp@withoutwire.com<mailto:dillonp@withoutwire.com>

**Comment by Halfpint-Code** [comment]
Hi, was wondering if you had seen my last comment. I added the error handling when the error happens to try to grab the token silently with the granted scopes as suggested in another link, but there are no granted scopes and it fails again.
