### ISSUE TITLE
After Sign Out Accounts is cleared from cache but MSALwebView still shows  previous user  credentials. It seems cookies are not getting cleared ? I implemented Graph API in Swift

### ISSUE THREAD

**Issue by jayeshcode** [AzureAD/azure-activedirectory-library-for-objc#1520]

**Comment by jasoncoolmax** [comment]
Could you please try our sign out API in our dev branch where we implemented new logic to pop up webview to sign out an account in the browser as well, if that is what you are looking for.
https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/MSAL/src/public/MSALPublicClientApplication.h#L458

Please let me know if that fits your needs.

**Comment by jayeshcode** [comment]
I Am using -> MSAL1.0.7. I don't see API Sign Out Api in my MSALpubliclientApplication.

#pragma mark - Remove account from cache

/**
    Removes all tokens from the cache for this application for the provided account.
    MSAL won't be able to return tokens silently after calling this API, and developer will need to call acquireToken.
    User might need to enter his credentials again after calling this API
 
    @param  account    The account to remove from the cache
 */
- (BOOL)removeAccount:(nonnull MSALAccount *)account
                error:(NSError * _Nullable __autoreleasing * _Nullable)error;


@end

**Comment by jayeshcode** [comment]
@jasoncoolmax, I did pod install from dev branch 

I see API now in my project but I am not able to build project as it is complaining about  #import "IdentityCore_Internal.h"  not found

pod 'MSAL', :git => 'https://github.com/AzureAD/microsoft-authentication-library-for-objc', :branch => 'dev'

**Comment by jayeshcode** [comment]
@jasoncoolmax  Any updates ?

**Comment by oldalton** [comment]
I think you're missing submodule flag. See guidance [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/Installation).

From the guidance:

> Note: if you're checking out a particular branch or tag of MSAL, you will need to add the :submodules => true flag to your podfile, so that CocoaPods finds MSAL dependencies
> 
> `pod 'MSAL', :git => 'https://github.com/AzureAD/microsoft-authentication-library-for-objc', :branch => 'master', :submodules => true`
> You then you can run either pod install (if it's a new PodFile) or pod update (if it's an existing PodFile) to get the latest version of MSAL.

**Comment by jayeshcode** [comment]
@oldalton  Thanks project builds now.

Just want to confirm  I don't have signOut params I am creating new from webviewParams ?
 let signOutparams = MSALSignoutParameters(webviewParameters: webViewParameters)

After calling Signout API it shows  wrong message on alert Appname Wants to use microsoftonline to sign in (should be sign out instead) is there way to disable alert ? then it opens web view where user can select account to sign out ? can we sign out user without web view ?

**Comment by oldalton** [comment]
You cannot signout without a WebView. If you're using WKWebView, you can yourself clean all cookies from it, but we don't generally recommend that approach.

Regarding the alert message, unfortunately, we don't control it and it is shown by iOS.

**Comment by jayeshcode** [comment]
Thanks for response

@oldalton SignoutAPI is signingOut how can I signout and forget ?

**Comment by jayeshcode** [comment]
@oldalton We are having issue with signOutAPI happy path is working as expected. 

When user press cancel on first popover or cancel without selecting account on second screen  the Signout API still returns True in result & account is removed. If user taps SignOut again account is removed and we can not use signOutAPI as we don't have any account now.

**Comment by oldalton** [comment]
Thanks for the feedback. Unfortunately, client side cannot detect whether user completed sign-in inside web view or not. The signout from webview is a "best-effort" and relies on the end user to complete it successfully. 

If you need to retrieve the signed-out account at a later point, you can modify MSAL account enumeration parameters to include "signed-out" accounts in the result as well. By default MSAL only returns accounts that haven't been yet signed-out. See documentation [here](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALAccountEnumerationParameters.html#/c:objc(cs)MSALAccountEnumerationParameters(py)returnOnlySignedInAccounts)

**Comment by jayeshcode** [comment]
@oldalton I check let account = self.currentAccount() before calling SignOut Api. 

current account is coming nil when I make build from release or from App centre
When I make build in debug mode I have current account & can call sign out API.

Do you have any demo app where you use Sign out API.

**Comment by jasoncoolmax** [comment]
@jayeshcode do you have more questions regarding this issue?

**Comment by jayeshcode** [comment]
@jasoncoolmax   No Thanks ! closing ticket now
