### ISSUE TITLE
Does SFBrowserRemoteVC uses UiwebView or WKwebview.

### ISSUE THREAD

**Issue by jayeshcode** [AzureAD/azure-activedirectory-library-for-objc#1532]
While submitting the app issue was raised by Apple. 

ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by jayeshcode** [comment]
Is default webviewType for  applicationContext.acquireToken which is SFBrowserRemoteVC uses UIWebview or WKWebview !

**Comment by oldalton** [comment]
@jayeshcode. ADAL 4.x and above only uses WKWebView. ADAL 2.x uses UIWebView, and we recommend everyone who is using that ADAL version to migrate to ADAL 4.x and above.

MSAL doesn't use UIWebView at all, and supports WKWebView as well as ASWebAuthenticationSession (https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews).

I'm not sure what is SFBrowserRemoteVC - is it some kind of a library you're using? In any case, if you're either using MSAL or ADAL 4.0 and above, there should be no references to UIWebView from our side. It might be that some other library is using UIWebView.

**Comment by jayeshcode** [comment]
We are using Using MSAL (1.1.1) in our project. We are not using UIwebview all over project so when Apple flagged us for using UIwebview I contacted you. we only have MSAL as 3rd party in our project. 

When I open debugview in XCODE the screen presented after " applicationContext.acquireToken" was named as SFBrowserRemoteViewcontroller.
