### ISSUE TITLE
Using ADAL without use_frameworks! in podfile

### ISSUE THREAD

**Issue by VaibhavMisra** [AzureAD/azure-activedirectory-library-for-objc#1533]
Can we use ADAL pod without `use_framework!` in podfile in a Swift project? 
[This](http://blog.cocoapods.org/CocoaPods-1.5.0/) blogpost says we don't need to use it anymore if we are using cocoapods >v.1.5 (which I am)

Hence, I removed `use_frameworks!` from my podfile and instead added `:modular_headers => true` for ADAL. I got following two errors:

> 1. Umbrella header 'ADAL.h' not found
> 2. Could not build Objective-C module 'ADAL'

I'm trying this because I want to use another pod from MyScript which is only packaged as Static library.

**Comment by oldalton** [comment]
I don't think we support :modular_headers => true. Can you try removing it?

**Comment by antrix1989** [comment]
hi @VaibhavMisra , did you have a chance to try removing modular headers option from your pod?

**Comment by VaibhavMisra** [comment]
@antrix1989 @oldalton Thank you for your replies. I had tried removing `:modular_headers => true` as well before posting the question. I was still getting some compilation error, which I don't remember right now. I got busy with other work and couldn't try it again to note down what was the actual error.

Hence, I figured for ADAL to work, it needs `use_framework!` in the podfile. Is my understanding incorrect?

**Comment by oldalton** [comment]
@VaibhavMisra, can you show your exact PodFile as an example? It should be possible to use ADAL without use framework.

**Comment by mipetriu** [comment]
Hi @VaibhavMisra, are you still seeing this issue?

**Comment by VaibhavMisra** [comment]
@oldalton @mipetriu I'm pasting the content below of my Podfile below. I just tried by commenting `use_frameworks! ` line. It didn't work.  However, it will be difficult for me to go back and test it again get you exact details of the issue right now. 

Since, you have reopened it, I hope you have been able to recreate it at your end.

```
platform :ios, '9.0'
use_frameworks!

inhibit_all_warnings!

def all_pods
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'MagicalRecord', '~> 2.0'
    pod 'SVProgressHUD', '~> 2.0'
    pod 'RMPickerViewController', '~> 2.2'
    pod 'DZNEmptyDataSet', '~> 1.0'
    pod 'KGNAutoLayout'
    pod 'EAIntroView', '~> 2.0'
    pod 'SAMKeychain', '~> 1.5'
    pod 'MGSwipeTableCell', '~> 1.0'
    pod 'ReachabilitySwift'
    pod 'DeviceGuru', '~> 5.0.0'
    pod 'Zip'
    pod 'SkyFloatingLabelTextField'
    pod 'BrightFutures'
    pod 'CocoaLumberjack/Swift'
    pod 'ADAL'
    pod 'AppCenter/Analytics'
    pod 'AppCenter/Crashes'
	
end

target 'MyApp' do
    all_pods
end

target 'MyAppTests' do
    all_pods
end

```

**Comment by mipetriu** [comment]
@VaibhavMisra I was not able to reproduce this issue using CocoaPods version 1.9.3 and the provided Podfile with `use_frameworks!` removed. If possible, could you test again with CocoaPods version 1.9.3? Also, if you have any other details that can help me reproduce your environment, please let me know.
