### ISSUE TITLE
ADAL Ionic [iOS]

### ISSUE THREAD

**Issue by webteambel** [AzureAD/azure-activedirectory-library-for-objc#1534]
Hello,

Can someone tell me how to generate an "ADAL FILE" like this one in the repo: 

https://github.com/fradali/azure-activedirectory-library-for-cordova/tree/adal-ios-wkwebview/src/ios/ADAL.framework

I just tried to remove uiwebview from the cordova plugin but it still shows me the problem when I push to the store a version and I think that the "ADAL FILE" is the problem.

Thanks.

**Comment by rohitnarula7176** [comment]
@webteambel Can you explain why you are trying to remove the UIWebview manually from the framework. Can you try compiling the framework with the latest version of the ADAL library that doesn't use the UIWebview and instead uses the WKWebview.
