### ISSUE TITLE
ADAuthenticationError.h' file not found

### ISSUE THREAD

**Issue by alantom1423** [AzureAD/azure-activedirectory-library-for-objc#1540]
Hi
    On Pod updating to ADAL 4.0.8 and building iOS project getting the error
**ADAuthenticationError.h' file not found.** I'm trying this in an Ionic capacitor project
Could you please help

**Comment by jasoncoolmax** [comment]
Thank you for reporting this. We will investigate.

**Comment by antrix1989** [comment]
I verified pod on a new project, no issues. @alantom1423, seems something with your configuration.
