### ISSUE TITLE
Facing issue with Telenor Active directory user.

### ISSUE THREAD

**Issue by cnfuzedRk62** [AzureAD/azure-activedirectory-library-for-objc#1549]
Hi Team i am facing issue using  Azure SSO while trying to login with telenor active directory user using iOS App. And Azure SSO worknig fine with other active directories . I am going to attached the screen shot of that. Please help me with this issue.
Thank you.
![image001 (3)](https://user-images.githubusercontent.com/52038339/92385348-5c266b00-f12f-11ea-97ce-f6f52b9d8430.png)

**Comment by hieunguyenmsft** [comment]
@cnfuzedRk62 Hi It looks like an issue of MSAL, Please help to
1. Create a new issue in MSAL: 
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues
2. Collect the log when this error happens:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=objc#logging-in-msal-for-ios-and-macos

**Comment by cnfuzedRk62** [comment]
HI  @hieunguyenmsft  i resolved this issue doing enable keychain share feature in ios app and Add microsoft authentacation app redirect url ie:- com.microsoft.adalcache and now it is working fine. Now i am going to close this one.
