### ISSUE TITLE
Couldn't able to set label and protect file using "User-Defined" label (ad hoc)

### ISSUE THREAD

**Issue by sw-tt-rumitkkhakhi** [AzureAD/azure-activedirectory-library-for-objc#1569]
When we are trying to set label and protect the file using "User Defined" label (ad hoc) but we are getting following error while protecting the file.

**Label requires ad-hoc protection, but protection has not yet been set. Call FileHandler::SetProtection with ad-hoc protection settings before calling FileHandler::SetLabel**

Please suggest us, how can we set label(of type "userdefined") on file and protect file using "User-Defined" label.

We are using C++  MIP SDK to achieve this.

Thanks

**Comment by jasoncoolmax** [comment]
Hi @sw-tt-rumitkkhakhi , ADAL doesn't handle anything related to label. 
I think probably you can try to post your question [here](https://github.com/Azure-Samples/mipsdk-protectionapi-cpp-sample-basic). You can also try it [here](https://github.com/MicrosoftDocs/Azure-RMSDocs/issues). I am not sure which one is the suitable repo.
