### ISSUE TITLE
Please Provide some provision for  Third Party Apps to customise the status bar light or dart content mode.

### ISSUE THREAD

**Issue by sehaswaran** [AzureAD/azure-activedirectory-library-for-objc#1582]
Hi Team

Third Party Apps  who use your framework ,

calling the acquireToken, which presents the webview with your own navigation controller.

Problem:

Default navigation controller status bar style is black or darkContent.
But, Third Party Apps might support light and dark mode of content .

Please Provide some provision for  Third Party Apps to customise the status bar

**Comment by mipetriu** [comment]
Hi @sehaswaran, we're not currently taking new feature requests for ADAL at this time, but we can evaluate this for [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-objc).

**Comment by sehaswaran** [comment]
Thanks @mipetriu I will check
