### ISSUE TITLE
Failed to get the default ADKeychainTokenCache

### ISSUE THREAD

**Issue by arsalangolestanekh** [AzureAD/azure-activedirectory-library-for-objc#1584]
Hi, 
After ADAL 6.0.0 update I can not login

I receive error:
IntuneMAM: (2021-11-01T17:50:44.031Z) MAMError: "Failed to get the default ADKeychainTokenCache"
IntuneMAM: (2021-11-01T17:50:44.032Z) Failed to get the default ADKeychainTokenCache

Before I have replaced ADKeychainTokenCache  with ADALKeychainTokenCache
Logs are attached.

![image](https://user-images.githubusercontent.com/61407619/139717051-7a640862-4d99-4be8-ae2e-e16dd68f5e92.png)
[logsIntune.txt](https://github.com/AzureAD/azure-activedirectory-library-for-objc/files/7455218/logsIntune.txt)

**Comment by mipetriu** [comment]
Hi @arsalangolestanekh, alongside the ADAL 6.0.0 update, the Microsoft Intune MAM SDK also published an update to be compatible with the naming updates introduced in ADAL 6.0.0. Do you mind trying to update the Intune MAM SDK as well, and see if that solves the issue?

**Comment by arsalangolestanekh** [comment]
Hi, @mipetriu, Yeah, I am trying to build with ADAL 6.0.0 with MAM 14.7.1 and Xcode 12.3 
I am not sure if It is allowed to use 15.3.1 with Xcode 12.3. Will try to do it now

**Comment by arsalangolestanekh** [comment]
@mipetriu The same issue appears with 15.1.3

**Comment by mipetriu** [comment]
@arsalangolestanekh I misspoke about the state of the MAM SDK. I received the proper info - their team is currently working on supporting ADAL 6.0.0 now, and should have a release ready by mid-next week. I'm sorry for the confusion.

**Comment by arsalangolestanekh** [comment]
@mipetriu, thank you for update
