### ISSUE TITLE
Library working in XCode environment but produces error code 34018 in production

### ISSUE THREAD

**Issue by menasheu** [AzureAD/azure-activedirectory-library-for-objc#1586]
Hi,
We use the MSAL library  1.1.25 (but the problem occurred also with 1.1.24) and everything works fine when in the application is loaded from XCode. However when we produce an ipa file and either export it or upload to the store the user gets the following error:

_**Couldn't query current account with error: Error Domain=NSOSStatusErrorDomain Code=-34018 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to get items from keychain.}**_

com.microsoft.adalcache is correctly defined in the Keychain Sharing. Same for the entitlements.

**Comment by fernandatoledo** [comment]
@menasheu I'm having the same issue, how did you solve it? Thank you!
