### ISSUE TITLE
ADAL builds broken on macOS 12.3

### ISSUE THREAD

**Issue by GeorgeSealy** [AzureAD/azure-activedirectory-library-for-objc#1591]
With macOS 12.3, Apple no longer provides a link to python at /usr/bin/python. At least one build script for ADAL references this path when building for iOS, and so the builds are failing.

We have attempted installing python separately, but then we hit the problem that symbolic linking in /usr/bin is not allowed by Apple's System Integrity Protection (see https://superuser.com/questions/1168773/how-to-create-symbolic-links-in-usr-bin-on-a-mac).

Can we have a fix / suggested work around for this build failure that doesn't require disabling System Integrity Protection?

**Comment by juan-arias** [comment]
Hi @GeorgeSealy, we see Python 2.7 was removed on macOS 12.3 and now Python 3 should be used, ir order to bypass the build error, please update the Python version that is used: ADAL Mac target -> Build Phases -> Run Script  change from `/usr/bin/pyhton "${PROJECT_DIR}...` to `/usr/bin/pyhton3 "${PROJECT_DIR}...`

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/1686668/160022235-c11a98bf-a67a-484c-be46-ab98dbad1133.png">

**Comment by GrebeniukLA** [comment]
Hi @juan-arias, I can see that you created a release branch 6.0.2 with this changes. Could you make the same changes for **ADAL iOS target** as well?

**Comment by juan-arias** [comment]
Hi @GrebeniukLA, thanks for bringing this into our attention. The change has been made for the iOS target as well on the release branch.

**Comment by juan-arias** [comment]
Hi @bhargavbajani-simformsolutions, these changes are scheduled for the upcoming April release.

**Comment by juan-arias** [comment]
A new ADAL version 6.0.2 has been released. Please feel free to reopen this issue in case you are still experiencing the problem.
