### ISSUE TITLE
Unable to Integrate ADAL via Carthage

### ISSUE THREAD

**Issue by ashishguru1986** [AzureAD/azure-activedirectory-library-for-objc#1598]
PhaseScriptExecution Run\ Script /Users/User/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/azure-activedirectory-library-for-objc/2.7.18/Build/Intermediates.noindex/ArchiveIntermediates/ADAL\ iOS/IntermediateBuildFilesPath/ADAL.build/Release-iphoneos/ADAL\ iOS.build/Script-6079EB5A1D7954EF00E95AB1.sh (in target 'ADAL iOS' from project 'ADAL')
    cd /Users/User/Documents/Code/Test/AdalTest/Carthage/Checkouts/azure-activedirectory-library-for-objc/ADAL
    /bin/sh -c /Users/User/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/azure-activedirectory-library-for-objc/2.7.18/Build/Intermediates.noindex/ArchiveIntermediates/ADAL\\\ iOS/IntermediateBuildFilesPath/ADAL.build/Release-iphoneos/ADAL\\\ iOS.build/Script-6079EB5A1D7954EF00E95AB1.sh
/Users/User/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/azure-activedirectory-library-for-objc/2.7.18/Build/Intermediates.noindex/ArchiveIntermediates/ADAL iOS/IntermediateBuildFilesPath/ADAL.build/Release-iphoneos/ADAL iOS.build/Script-6079EB5A1D7954EF00E95AB1.sh: line 2: /usr/bin/python: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/User/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/azure-activedirectory-library-for-objc/2.7.18/Build/Intermediates.noindex/ArchiveIntermediates/ADAL\ iOS/IntermediateBuildFilesPath/ADAL.build/Release-iphoneos/ADAL\ iOS.build/Script-6079EB5A1D7954EF00E95AB1.sh (in target 'ADAL iOS' from project 'ADAL')
(1 failure)
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/User/Documents/Code/Test/AdalTest/Carthage/Checkouts/azure-activedirectory-library-for-objc/ADAL.xcworkspace -scheme ADAL\ iOS -configuration Release -derivedDataPath /Users/User/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/azure-activedirectory-library-for-objc/2.7.18 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/fg/_3dxvtrj229_v0c1pjwr_ftc0000gp/T/azure-activedirectory-library-for-objc SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/User/Documents/Code/Test/AdalTest/Carthage/Checkouts/azure-activedirectory-library-for-objc)

Mac OS: 12.6.2
Carthage Verison: 0.38.0
Xcode:13.0
CartFile Entry : github "AzureAD/azure-activedirectory-library-for-objc" ~> 2.7.16

**Comment by kaisong1990** [comment]
@mipetriu Seems to active conversation for a while, should we close it?
