### ISSUE TITLE
acquireToken API stalls if Multi-factor auth to join devices is enabled in azure subscription

### ISSUE THREAD

**Issue by svallur** [AzureAD/azure-activedirectory-library-for-objc#186]
1. Enable "Require Multi-factor auth to join devices" on azure subscription
2. Call acquireToken for a service other than DRS, and ensure the call succeeds.
3. Call acquireToken for DRS, expecting prompt for multi-factor auth.

Observed: The page is stalled at an inactionable "401 unauthorized" error.

**Comment by kpanwar** [comment]
@svallur - I am closing this bug as I have not heard back on it for a while. Let me know if someone else can verify this.
