### ISSUE TITLE
remove custom base64 encoding/decoding in favor of platform support.

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-objc#207]
The file NSString+ADHelperMethods.* contain a custom implementation of base64 encoding and decoding.  This was because support for this was not in the platform libs before iOS7.  Now that we only support iOS 7 and above we can remove this custom code and just rely on the base platform support for this functionality.

**Comment by RPangrle** [comment]
Sadly the APIs added in iOS 7 don't include Base64 URL encoding support and have bugs around padding, the sum total of which is we won't be able to fix with the current state of iOS APIs :-/
