### ISSUE TITLE
Allow for non-strict login_hint

### ISSUE THREAD

**Issue by brandwe** [AzureAD/azure-activedirectory-library-for-objc#222]
Need to see if we match .net with allowing non-strict enforcement of matching login_hint with UPN

**Comment by RandalliLama** [comment]
@RPangrle This has been fixed, right?  If so, can you close the issue please?

**Comment by RPangrle** [comment]
Hasn't been fixed in master yet. I'll close this issue when we do the big merge down.

**Comment by RPangrle** [comment]
This was fixed with ADUserIdentifier. Closing this issue marked as fixed in the 2.1 milestone.
