### ISSUE TITLE
UI glitch when the user rotates the device with the keyboard present on iPad

### ISSUE THREAD

**Issue by IntDeXIOSSPPlugEng** [AzureAD/azure-activedirectory-library-for-objc#226]
During our investigation of PS161850: Sign in page in iOS SSP gets into a weird state when accidently rotating the screen.
Please see screens attached in the bug. However, since the iOS SSP uses the ADAL library for authentication, the authentication flow is taken over by the ADAL library and its auth controller.
Therefore, the right fix should happen in the ADAL library. For a lack of better option, we proposed to lack screen orientation change for the “ADAuthenticationViewController” to mask to UI issue. However, if there is a better solution that involves fixing the issue rather than masking it, that would be even better. We currently have a solution on the iOS SSP side that involves using ObjC runtime reflection to disable orientation change on the ‘ADAuthenticationViewController’ but feel it’s too much of a hack on the SSP side. Do you think this is an issue that you can help us fix or help us figure out what the best solution is?

![screenrotationbug](https://cloud.githubusercontent.com/assets/9665597/5303651/56b84c2a-7bb9-11e4-854c-65a7f4a15a96.PNG)

**Comment by kpanwar** [comment]
Closing the issue as it was fixed by Service side. Please let me know if the issue still happens.
