### ISSUE TITLE
Cannot read the items in the keychain. Error code: -34018

### ISSUE THREAD

**Issue by roligtroll** [AzureAD/azure-activedirectory-library-for-objc#241]
In one of our test devices we are getting the following error. This does not occur in the rest of the devices with same code running. The problematic device is an iPhone 6+. What can be causing this?

ERROR: Error raised: 11. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode:(null) Details:Cannot add a new item in the keychain. Error code: -25243.

**Comment by roligtroll** [comment]
This solved our issue, thanks a lot!

**Comment by roligtroll** [comment]
We are now currently having a similar but different issue even after adding "com.microsoft.adalcache" to the entitlement. 

 ERROR: Error raised: 11. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode:(null) Details:Cannot read the items in the keychain. Error code: -34018. Query: {
    svce = "MSOpenTech.ADAL.1|aHR0cHM6Ly9sb2dpbi53aW5kb3dzLm5ldC9ob3JtaWdhdGVzdC5vbm1pY3Jvc29mdC5jb20|aHR0cHM6Ly9kNTY3MTVlMDQzZjQ0MjVhODY1MTMwMzY2MzRkYjIzYS5jbG91ZGFwcC5uZXQ|MDNiNGNjYzMtNzBmZC00NGJhLTkzMWMtM2IxOWYyMDRjNzM2";
}. ErrorCode: 11.

**Comment by roligtroll** [comment]
com.microsoft.workplacejoin was also added to the entitlements

**Comment by roligtroll** [comment]
Additionally, this happens only when the app has been on background for around 5 minutes.

**Comment by kpanwar** [comment]
If the keychain gets locked, then it cannot be accessed and you will get this error. The issue has been fixed and pending release in master. You could also checkout https://devforums.apple.com/thread/246122?tstart=0 where people are facing similar issues in iOS 8.

**Comment by kpanwar** [comment]
See https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/245 for reference
