### ISSUE TITLE
Token retrieval fails when running in the background

### ISSUE THREAD

**Issue by vikasra** [AzureAD/azure-activedirectory-library-for-objc#245]
When running a background task (via performFetchWithCompletionHandler) access token retrieval fails when the phone is locked with a pin (ADAL returns error code 11). Believe this is because keychain access is disabled when the phone is locked.

**Comment by vikasra** [comment]
Believe this is because of the attribute kSecAttrAccessibleWhenUnlockedThisDeviceOnly that is used when creating a keychain item. Would be great to have this configurable to kSecAttrAccessibleAlwaysThisDeviceOnly based on parameter during context initialization

**Comment by kpanwar** [comment]
Thank you for reporting the issue. This will be fixed in the upcoming release. I will update this thread as soon as we have a release out.

**Comment by kpanwar** [comment]
Fixed, pending code review and release as 1.2.0
