### ISSUE TITLE
Tests to ensure that aquireToken with AD_PROMPT_NEVER still succeed when the main thread is blocked

### ISSUE THREAD

**Issue by RPangrle** [AzureAD/azure-activedirectory-library-for-objc#248]
It's possible something is blocking the main thread while one of these APIs is called:

-(void)  acquireTokenWithResource: (NSString*) resource
                         clientId: (NSString*) clientId
                      redirectUri: (NSURL*) redirectUri
                   promptBehavior: (ADPromptBehavior) promptBehavior
                           userId: (NSString*) userId
             extraQueryParameters: (NSString*) queryParams
                  completionBlock: (ADAuthenticationCallback) completionBlock;

This can result in an unfortunate circumstance where a resource loop occurs resulting in a deadlock. Adding tests for this to make sure the call still works while the main thread is being blocked. (Namely remove the part in the test code where it keeps the run loop spinning) would be helpful for finding these bugs and preventing future ones from being added.

**Comment by kpanwar** [comment]
Yes, this method can potentially be called. I'll remove the main queue call.
-(void) internalAcquireTokenByRefreshToken: (NSString*) refreshToken
                                  clientId: (NSString*) clientId
                                  resource: (NSString*) resource
                                    userId: (NSString*) userId
                                 cacheItem: (ADTokenCacheStoreItem*) cacheItem
                         validateAuthority: (BOOL) validateAuthority
                             correlationId: correlationId
                           completionBlock: (ADAuthenticationCallback)completionBlock

**Comment by kpanwar** [comment]
Only call that is made on main thread is the one that launches the UI.If you pass PROMPT.NEVER then it should always execute on the background thread.

**Comment by RPangrle** [comment]
We should have tests on the Silent APIs where we don't keep the main run loop spinning to make sure nothing inadvertently ends up trying to jump to the main thread that shouldn't.
