### ISSUE TITLE
Provide a delegate or  block to execute before the webview is closed

### ISSUE THREAD

**Issue by dangodb** [AzureAD/azure-activedirectory-library-for-objc#251]
With the current behavior, the completion block is called only after the adal webview is closed. This doesn't allow app to immediately show the the post-authenticated view to the user. The ideal flow on sucessful authentication would be pre-authenticated view -> Adal -> post-authentication view, but right now the completion callback only allows it to be pre-authenticated view -> Adal -> pre-authenticated view -> post-authentication view.

**Comment by RPangrle** [comment]
If you want to show UI in such a manner you have to pass in a webView and control the UI behavior yourself.
