### ISSUE TITLE
Missing AcquireTokenSilentSync method

### ISSUE THREAD

**Issue by greathansen** [AzureAD/azure-activedirectory-library-for-objc#258]
For the Android Library Adal has a acquireTokenSilentSync method.

Could you add the method?

For sync this method we did a simple method with a semaphore. Maybe could help ->

https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/master/sdk-objectivec/office365_odata_base/office365_odata_impl/ADALDependencyResolver.m

**Comment by kpanwar** [comment]
This method already exists in the API. https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/master/ADALiOS/ADALiOS/ADAuthenticationContext.h
Search for AcquireTokenSilentWithResource

**Comment by joshgav** [comment]
Yes, but this still requires a callback where the result is passed, so we have to [wait on the callback](https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/master/sdk-objectivec/office365_odata_base/office365_odata_impl/ADALDependencyResolver.m#L48). In Android we have [acquireTokenSilentSync](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/master/src/src/com/microsoft/aad/adal/AuthenticationContext.java#L577) which is actually a synchronous method.

Can you create acquireTokenSilentSyncWithResource in ADAL for iOS?

**Comment by kpanwar** [comment]
iOS API is completely async. what you are doing is exactly what I would need to do. I don't see a reason to break the async pattern. I think you should keep your code as is. I am curious as to why are you developing synchronous API?
