### ISSUE TITLE
Archiving fails due to copy command inside the custom script

### ISSUE THREAD

**Issue by jpanchal** [AzureAD/azure-activedirectory-library-for-objc#262]
Archiving fails with following error because it is unable to copy the headers specified in the Run Script block:

PhaseScriptExecution Run\ Script /Users/.../Library/Developer/Xcode/DerivedData/Daylight-caloagasaogkxseytgtwrsrlopmi/Build/Intermediates/ArchiveIntermediates/Daylight/IntermediateBuildFilesPath/ADALiOS.build/Debug-iphoneos/ADALiOS.build/Script-8B19339718BAEDE4008FD93A.sh

cp: /Users/.../Library/Developer/Xcode/DerivedData/Daylight-caloagasaogkxseytgtwrsrlopmi/Build/Intermediates/ArchiveIntermediates/Daylight/InstallationBuildProductsLocation/usr/local/lib/Headers/ADALiOS/: No such file or directory

//******* THIS IS CAUING ERROR ****** 

/bin/cp -a "${TARGET_BUILD_DIR}/${PUBLIC_HEADERS_FOLDER_PATH}/" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.framework/Versions/A/Headers"

**Comment by kpanwar** [comment]
How are you including the SDK? Suggested way is to use cocoapods.

**Comment by jpanchal** [comment]
I am not using cocoapods. I am using Git submodules to clone the repo and include the project file. Than add the lib to  Linked Framework and Libraries.

**Comment by jpanchal** [comment]
It works file in simulator, running on device, but archiving fails. If I comment that line of code, I am able to archive just fine.

**Comment by jpanchal** [comment]
Did anyone get a chance to look into this?

**Comment by RPangrle** [comment]
I am aware of the issue. There's a problem in how one the build scripts are set up and will need to make sure when I fix this I don't break cocoapods.

**Comment by luukjansen** [comment]
Is there a 'alpa/beta sollution' so that can be tested so I can get my project build?
I also have the project added as a subproject and the library linked.

**Comment by shashank109** [comment]
I am facing same issue. Can someone suggest me any extension how to make build as I have integrated 
ADALiOS into my project or is there any alternate way for making the build? Please someone look into this. Thanks

**Comment by RPangrle** [comment]
To clarify: The issue was that the headers were being copied into the "Headers" folder instead of "include". Since Apple added Framework support on iOS we started tripping up on this. The fix for this will ship in 2.1.

**Comment by joelrb** [comment]
@RPangrle not yet fixed. I just cloned repo few minutes ago (March 30, 2016) and I still get this error when I build ADALiOs.. thanks! (using latest XCode 7.3)
cp: /Users/fresh/Library/Developer/Xcode/DerivedData/ADALiOS-fuawkeadacuhylezqxbbitscougr/Build/Intermediates/ArchiveIntermediates/ADALiOS/InstallationBuildProductsLocation/usr/local/lib/Headers/ADALiOS/: No such file or directory

**Comment by RPangrle** [comment]
It's fixed in 2.1 beta, not 1.2.x
