### ISSUE TITLE
Office for Mac - NTLM support in Office iOS apps issue 

### ISSUE THREAD

**Issue by mail2ptyagi** [AzureAD/azure-activedirectory-library-for-objc#265]
Hi Team, 

We Tested NTLM support in Office iOS apps and found issues in it. 

Account used for testing: testuser1@aadadfs20.info
testuser1@aadadfs20.info is enabled for the ADFS 2.0 server since Feb 12th 2015, and  NTLM was configured to support “Send NTLMv2 response only”. 

We tested on both Old build (without NTLM code lib integrated) and New build (with NTLM code lib integrated) and in both the builds we were able to login with account testuser1@aadadfs20.info in Word/Powerpoint/Excel apps. 

Issue: In New build (with NTLM code lib integrated) we don’t see NTLM auth token in Fiddler trace so cant confirm that NTLM auth is working fine.

Kindly contact "v-ptyagi@microsoft.com" and "ranyel@microsoft.com" for more information.

**Comment by RPangrle** [comment]
Auth worked, so I'm not sure what the ADAL bug is here... Maybe there's a server configuration issue?

**Comment by mail2ptyagi** [comment]
+Rany
