### ISSUE TITLE
Single token for multiple resources

### ISSUE THREAD

**Issue by jpanchal** [AzureAD/azure-activedirectory-library-for-objc#276]
How do we prompt for a single login screen to access multiple recourses? For example:

outlook.office365.com
graph.windows.net
tenant.sharepoint.com

It requires to get token for each resource, how can we single sing-on to each resource using this SDK?

Earliest response is really appreciated.

Thanks.

**Comment by kpanwar** [comment]
you should not need to enter creds for your application (assuming there is only 1 application) again once signed in. If your token is a multi-refresh token then it is used to get access token each unique resource. Are you passing AD_PROMPT_ALWAYS as a promptBehavior? If so, then don't.

**Comment by jpanchal** [comment]
Thanks for the quick response. It is one application. There is only one clienid configured in azure with permission to multiple resources. I get access token for resource outlook.office365.com and for result,  multiresourcerefreshtoken is set to YES. Now when I try to access another resource using this token (microsoft-my.sharepoint.com), it throws error:

Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed. (NSURLErrorDomain error -1012.)"

**Comment by kpanwar** [comment]
you cannot use the SAME access token against another resource. You need to call acquiretoken again with a different resource and the API will get you another access token for that particular resource.

**Comment by jpanchal** [comment]
Aha! Perfect. I was missing that piece. It's working now. I really appreciate your prompt responses.

Thanks again.

**Comment by kpanwar** [comment]
you are welcome. Glad to help!
