### ISSUE TITLE
ADAuthenticationContext interface should conform to the ADAuthenticationContext protocol.

### ISSUE THREAD

**Issue by MIchaelMainer** [AzureAD/azure-activedirectory-library-for-objc#278]
https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/master/ADALiOS/ADALiOS/ADAuthenticationContext.h

ADAuthenticationContext interface should conform to the ADAuthenticationContext protocol since the protocol exists. Or else, remove the protocol and change ADALDependencyResolver initWithContext so that it takes  ADAuthenticationContext instead of the qualification of the id, (id<ADAuthenticationContext>). Otherwise, all samples will have a warning.

**Comment by kpanwar** [comment]
Where does ADALDependencyResolver come from? there is no such thing in ADAL iOS.

**Comment by MIchaelMainer** [comment]
That is in https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/master/sdk-objectivec/office365_odata_base/office365_odata_impl/ADALDependencyResolver.m

**Comment by kpanwar** [comment]
This issue should be filed in their SDK.

**Comment by MIchaelMainer** [comment]
Agreed. But still, there is a ADAuthenticationContext protocol that probably shouldn't exist in the iOS SDK.

**Comment by kpanwar** [comment]
Only protocol that exists in ADAL public API is ADTokenCacheStoring. I am not sure where are you getting "ADAuthenticationContext protocol. Can you be more specific please?

**Comment by MIchaelMainer** [comment]
You're right. There is that single protocol. I should have closed with my last comment.  I meant to state that it shouldn't exist in the O365 iOS SDK.
