### ISSUE TITLE
Appropriate NSBundle search

### ISSUE THREAD

**Issue by damienpontifex** [AzureAD/azure-activedirectory-library-for-objc#280]
I am using cocoa pods 0.36 and integrating ADALiOS as a framework in my project. I am commonly getting the error for not including the resource bundle. Although inspecting the app product and the ADALiOS.framework contains both storyboards. 

In the code https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/master/ADALiOS/ADALiOS/ADAuthenticationBroker.m#L130-L162 for `+ (NSBundle *)frameworkBundle` why not use the function `NSBundle *adalBundle = [NSBundle bundleForClass:[self class]];`? I would have assumed this should resolve the correct path regardless of integration methods of the ADALiOS library

**Comment by CosminRadu** [comment]
+1. 
We're also hitting this issue. Per [Cocoapods doc](http://blog.cocoapods.org/CocoaPods-0.36/) under the Caveats section, the suggestion above is the recommended way of addressing this:

One caveat about bundling resources is, that until now we had to embed all resources into the application bundle. The resources were referenced programmatically by [NSBundle mainBundle]. Pod authors were able to use mainBundle referencing to include resources the Pod brought into the app bundle. But with frameworks, you have to make sure that you reference them more specifically by getting a reference to your framework's bundle e.g.

    [NSBundle bundleForClass:<#ClassFromPodspec#>]
