### ISSUE TITLE
MFA not working for iOS ADAL

### ISSUE THREAD

**Issue by askhade** [AzureAD/azure-activedirectory-library-for-objc#286]
Repro Steps : 1) Install the OneDrive app / Company Portal
                       2) Sign in with the MFA credential’s
                       3) It gets navigated to the new page , where it says “ Additional Security Verification “ required
                       4)Tap on “Set it up” button and a white blank screen is observed. 

Looks like adal issue to me because I can repro it from OneDrive as well as company portal app on iOS but android and browser works

**Comment by kpanwar** [comment]
Already fixed in 1.2.2.
