### ISSUE TITLE
OS X Support with Cocoapods

### ISSUE THREAD

**Issue by damienpontifex** [AzureAD/azure-activedirectory-library-for-objc#287]
Is there a guide to integrating the library into a Mac application?

There seems to be a lot of conflict with using iOS types i.e. UIWebView, UIViewController, UIAlertView etc. Also adding these lines to the ADALiOS.podspec 
```
s.ios.deployment_target = "7.0"
s.osx.deployment_target = "10.8"
````
and running `pod lib lint` while in the directory shows all these errors about unknown types.

**Comment by kpanwar** [comment]
UI* classes are only in iOS. We have an OSXUniversal branch that you could use. It is not published on cocoapods though.

**Comment by damienpontifex** [comment]
There seems to be large divergence (~200 commits ahead and behind master) on that branch. Is there a pathway to merging them into single branch at some point?

I ask as version specified in the pod spec defines it still as 0.5. Does this mean the branch is behind 1.0 release status?

**Comment by RandalliLama** [comment]
@damienpontifex You are correct there is a large divergence.  The OSXUniversal branch is not really supported currently.  We are planning on reducing branches and consolidating in to a single release out of the master branch, but it is going to take us a while to get there.  In the meantime, Mac support is limited at best.

**Comment by RPangrle** [comment]
Reopening as we're now looking at official mac support.

**Comment by damienpontifex** [comment]
@RPangrle is there an issue that outlines the items needing to be done for convergence/offical support for Mac? Would love to contribute, test/support if there is an outline of making this happen

**Comment by RPangrle** [comment]
Not at the moment. A lot of the issues are more architectural then anything. I'm looking to avoid some of the pitfalls that we have with the OS X Universal branch, particularly around large amounts of copy/paste code between iOS and Mac. (Also, convergence tends to refer to the convergence branch around here which is yet a different thing that isn't covered here at all! Confusing, I know.)

Some of this work has already been done in the broker-mac branch.  And I've been trying to tag issues with the Mac label to track them.

https://github.com/AzureAD/azure-activedirectory-library-for-objc/labels/Mac

I'll be sure to let you know when things are closer to being testable/ready. (Hopefully soon(ish))

**Comment by RPangrle** [comment]
The CocoaPod for ADAL is now simply 'ADAL' and supports both iOS and Mac.
