### ISSUE TITLE
We should not Log Error when User Cancel Auth

### ISSUE THREAD

**Issue by ranyelhousieny** [AzureAD/azure-activedirectory-library-for-objc#288]
This will create an assert, when user cancels the sign-in window. Please, change it to VERBOSE

#5	0x1b831fe3 in -[ADAuthenticationBroker webAuthenticationDidCancel] at /Users/debug/Downloads/azure-activedirectory-library-for-objc-OSXUniversal-dev/ADAL-OSX/ADAL-OSX/ADAuthenticationBrokerOSX.m:235

ADAuthenticationError* error = [ADAuthenticationError errorFromCancellation];
AD_LOG_ERROR(message, code, info);

**Comment by RPangrle** [comment]
I disagree. Cancellation data is a potentially error level event and teams have expressed interest in being able to get that data. Creating an assert is not a function of the ADAL code.

**Comment by RPangrle** [comment]
The assert is not generated by ADAL code. How your team chooses to handle ADAL logging is of your concern, however us not logging an error is out of the question.
