### ISSUE TITLE
[OSX] Module definition

### ISSUE THREAD

**Issue by damienpontifex** [AzureAD/azure-activedirectory-library-for-objc#290]
With Xcode now supporting modules (and Swift's requirement for modules) can the OS X project be updated with build settings for DEFINES_MODULES to Yes?

I believe the target name will also need renaming if this occurs to conform with c99 standards i.e. rename to ADAL_OSX vs the hyphen in the current name.

**Comment by RPangrle** [comment]
@damienpontifex Can you take a peek at the broker-dev branch and see if this fixes your issue?

**Comment by damienpontifex** [comment]
Initial test still getting the error 'No such module ADAL'. Still trying to debug what is missing. I wouldn't have thought a custom module map was required, the Xcode framework target should be able to generate everything required.

One thing to note is the 'ADAL Mac' framework target doesn't seem to have sufficient headers marked as Public.

On another note looking at #473 about mac & iOS support, why not use `WKWebView` which is apple's modern web rendering view and exists on both platforms?

**Comment by RPangrle** [comment]
Give broker-mac-ui-impl a shot then. I added all the public headers into the framework and the module map. 

The main reason to not use WKWebView is we haven't in the past, already have the the code for UIWebView/WebView and there's not much to gain from using it right now as we're not terribly JavaScript heavy. Also I might still have to support iOS 7. :-/ Not entirely sure on that last point. I could see once iOS 10 comes out making the switch.

**Comment by damienpontifex** [comment]
That seemed to work on topics/broker-mac-ui-impl branch :)

I did change the 'Skip Install' build setting to 'No' so I could archive the product and get the release output.

Thanks for this, feel free to close this issue.
