### ISSUE TITLE
X.509 certificate authentication does not work

### ISSUE THREAD

**Issue by Chirag-Chauhan** [AzureAD/azure-activedirectory-library-for-objc#293]
The "Sign in using X.509 certificate" does not automatically pickup the certificate or does not give the popup to select the certificate. I am successfully able to do form based authentication (username/password).

If I try the same process with Safari browser, the option "Sign in using X.509 certificate" does get me a popup to select the certificate.

Any help will be appreciated.

Thanks.

**Comment by brandwe** [comment]
We currently do not support x.509 certificates in the webview of our SDK.

**Comment by Chirag-Chauhan** [comment]
Thanks a lot for quick reply. 

I even tried wrapping up the iOS native application using Microsoft Intune wrapper. With wrapped application also, I got the same behaviour of X.509 certificate authentication. Here also "Sign in using X.509 certificate" does not automatically pickup the certificate or does not give the popup to select the certificate.

Is there any other approach to achieve the same?

Thanks.

**Comment by brandwe** [comment]
Unfortunately no. We are looking in to supporting it but at the moment we don't.

**Comment by Chirag-Chauhan** [comment]
Thanks for the confirmation.

**Comment by PeterSelchDahl** [comment]
Hi Brandon,
What is the timeline and is it on your roadmap now? 

Azure Feedback - Please yote for this support:
http://feedback.azure.com/forums/170031-sdk-and-tools/suggestions/8146017-adal-support-for-certificate-authentication-x-509

**Comment by RandalliLama** [comment]
@PeterSelchDahl Unfortunately we do not have a timeline at this point.

**Comment by PeterSelchDahl** [comment]
Why have this issue been closed? Have you provided support in collaboration with Apple?

Just looking for a reason

**Comment by RPangrle** [comment]
This feature will require using the Authenticator and broker, but it does work.

**Comment by kaushikn** [comment]
We are having the same issue with OneDrive for Business on IOS. It is not picking up the client certificate. Any help on how to get this to work using Authenticator/Broker.

**Comment by RandalliLama** [comment]
Sign in via certificate is currently supported in limited circumstances.  However you need to have the Azure Authenticator installed.  It works with the Word, Powerpoint and Excel at this time.  

@brandwe Do we have any public docs on this?

**Comment by kaushikn** [comment]
Thanks Rich. 

How is the certificate installed; can the app pull the certificate from the system profile ?

**Comment by RandalliLama** [comment]
@kaushikn Yes, that's exactly where it comes from.  The Azure Authenticator invokes a Safari View Controller to do login when it detects that client cert auth is being requested by the server.  The Safari View Controller has the same access to certificates that the Safari app has.  You should be able to install the cert in the same way you would install a cert that would be used by Safari.

Note: Because of the way the Safari Web Controller works if you are using the Azure Authenticator for MFA you may be blocked.  The Azure Authenticator will not be able to show you an MFA prompt while the SWC is active, and you will not be able to get to your Azure Authenticator OTP codes.

**Comment by kaushikn** [comment]
Thanks Rich.

I am trying this with One Drive for Business on IOS. I have a certificate installed in my system profile and trying to use modern authentication with One Drive via our SAML IDP. I presume that One Drive for business is also using Safari Web Controller but for some reason the Safari Web Controller is not able to access the certificate.

The reason I am looking the Azure Authenticator is to check if it can solve the problem I am having with native One Drive app on IOS.

**Comment by kaushikn** [comment]
Hi Rich,

Quick follow up question; I am presuming that the reason the OneDrive for Business app does not work is because it it not using the Safari Web Controller but the webview instead ?

**Comment by RandalliLama** [comment]
@kaushikn Have you tried the OneDrive app when the Azure Authenticator is installed?  I think that OneDrive should work.  Unless you are using the older, separate OneDrive for Business app.  There is a combined OneDrive app here that you should try:

https://itunes.apple.com/us/app/onedrive-cloud-storage-for/id477537958?mt=8

And yes, without the Azure Authenticator OneDrive will simply use a webview that does not have access to the system keychain with the appropriate cert.

**Comment by kaushikn** [comment]
Thanks, will try it out.

**Comment by kaushikn** [comment]
Thanks a lot Rich. It worked.

**Comment by derekharkin** [comment]
Would you know if this works on Android too? I didn't see anything specifically referencing support on Android of this feature.

**Comment by RandalliLama** [comment]
In Android it should work without the Authenticator.

**Comment by anivaros** [comment]
Hello! Can I use CBA to auth user from my app with ADAL on ADFS, not Azure?

**Comment by RPangrle** [comment]
No

**Comment by anivaros** [comment]
Very sad :(
Do you have any plans to implement CBA flow for authentication on ADFS?
