### ISSUE TITLE
Our AAD authentication for mobile service (.NET) has stopped working

### ISSUE THREAD

**Issue by TheDudeV2** [AzureAD/azure-activedirectory-library-for-objc#299]
We have a mobile service (for an iOS Application) that was authenticating just fine (ADALiOS, Mobile Service SDK, JS backend).

We are now trying to port our application to .NET backend.

With the new release of the Azure Mobile Services Framework and the new build of ADALiOS, our authentication no longer functions.

We try to follow the documentation found here (last updated02/25/2015): http://azure.microsoft.com/en-us/documentation/articles/mobile-services-dotnet-backend-ios-adal-sso-authentication/

But the Azure portal does not permit us to follow the instructions as written:
"Scroll the page down to the permissions to other applications section and click the Add application button. Choose Other from the Show menu and search for todo. Click TodoList to add it the mobile service you registered earlier and click the checkmark for done. Grant access to the mobile service application. Then click Save".

  We suspect this documentation needs to change with the new updates, but can't figure out the correct steps ourselves.

If we use our old AAD setup, we can get to the point where the AAD login screen is presented, but upon entering a username and password we are met with a generic server error (Invalid resource, resource not registered for client).

If anyone has any step-by-step instructions on getting this to work with the new libraries/frameworks, we would find it extremely helpful.

Thanks,
TheDudeV2

**Comment by brandwe** [comment]
This should still work. If you have a valid iOS app and a valid todo app you can allow the iOS app to access the todo app in this manner. 

Are you using the new portal?

**Comment by TheDudeV2** [comment]
The new portal?  I'm not sure.  How do I know if it's the new portal?  Should I be?

We get this error exactly:
ADALiOS [2015-04-24 20:26:12 - 31E708B1-DE6C-4B81-8546-46E9E856AFDA] ERROR: Error raised: 15. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode:invalid_request Details:AADSTS90027: The client 'bcfc1f4e-33c9-4623-9b9e-200ae*******' and resource 'https://**********.azure-mobile.net/login/aad' identify the same application.
Trace ID: ddc77e37-9e50-4d24-8e8b-80ef9077b639
Correlation ID: 31e708b1-de6c-4b81-8546-46e9e856afda
Timestamp: 2015-04-24 20:26:13Z. ErrorCode: 15.

We just can't figure out how to deal with this.  Any advice?

**Comment by paulbatum** [comment]
Hi,

Where the documentation says "choose other" it should say "choose all apps". Once you pick 'all apps', then type in the first few characters in the name and you should see it in the list. Here is an example:
![image](https://cloud.githubusercontent.com/assets/10663/7330654/6f6567a0-eaa7-11e4-863b-496bd5aad3af.png)

The next problem you will have, when switching from the JS backend to the .NET backend, is that the Reply URL is different. It needs to be in the format of `https://****.azure-mobile.net/signin-aad`. Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/10663/7330670/dae04fd6-eaa7-11e4-9536-8548b894d556.png)

Let us know whether this addresses your issues!
