### ISSUE TITLE
Add notifications for various webview events

### ISSUE THREAD

**Issue by RPangrle** [AzureAD/azure-activedirectory-library-for-objc#315]
Allowing apps to observe on web view events (loading, url traversal, finish, close) would allow apps to better responding to ADAL and help with AI automation, and is much safer then the cascading delegates currently used in OS X Universal.

**Comment by RandalliLama** [comment]
@RPangrle Can you add some more detail on precisely what the benefits and tradeoffs are.  Are you suggesting adding more extensibility.  I am leery of adding too many extensibility points.

**Comment by RPangrle** [comment]
This would allow for observation, but it wouldn't allow for actually changing any of the flows. It would be useful for teams looking to observe the ADAL auth flows for telemetry or automation purposes.
