### ISSUE TITLE
WebView if provided by the caller has to be displaying until the acquireToken call’s completion block gets called.

### ISSUE THREAD

**Issue by svallur** [AzureAD/azure-activedirectory-library-for-objc#33]
A delegate facilitating the UI activation when in need would be ideal, hence letting the caller know when the UI needs to be shown and when collapsed. Similarly, it could also help for the caller to know when the webview is used to load a webpage, perhaps to display a "loading" test or image.

**Comment by RandalliLama** [comment]
@RPangrle Can you take a look and comment on this?

**Comment by RPangrle** [comment]
I'm not entirely sure what scenario you're looking to unblock here. Keeping the UI up until the completion block gets hit seems like a reasonable requirement to me. The time between the web view being done and the completely block getting hit is exceedingly small anyways. ADAL doesn't know whether the web page involved needs or is going to need user input (although it usually does unless the sso cookie is there and good). If the goal is for UI less flows there are silent versions of the APIs.
