### ISSUE TITLE
Using cocoapods > 0.36  and use_frameworks! should not require bridging header

### ISSUE THREAD

**Issue by pierreUMAknow** [AzureAD/azure-activedirectory-library-for-objc#353]
I created an empty Swift project in Xcode using a single view controller and nothing in it. I have a swift file that declares a class and contains the following line of code:

    import ADALiOS

I use cocoapods 0.38 and I have a simple podfile containing:

    platform :ios, '8.3'
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'ADALiOS'
    use_frameworks!

When I build the project, I get an error in ADAuthenticationParameters+Internal.h at the line:

    @interface ADAuthenticationParameters (Internal)

The error message is:
"Cannot find interface declaration for 'ADAuthenticationParameters'; did you mean "ADAuthenticationBroker'?"

Everything worked fine using the Bridging Header and not using use_frameworks! in the podfile. However, this prevents me from using other pods that are native in Swift.

Any workaround?

**Comment by BluMist** [comment]
I'm seeing this issue as well. I have to add use_frameworks! due to other Swift pods.

**Comment by RPangrle** [comment]
Fixed this for ADAL 2.1. There's a beta available on CocoaPods now.
