### ISSUE TITLE
Web view displays incorrectly on iPhone 5 devices leaving user unable to "remember me"

### ISSUE THREAD

**Issue by brandwe** [AzureAD/azure-activedirectory-library-for-objc#358]
when the user clicks login the AD UI pops up – if the user then taps on the username field, the focus immediately shifts to the password field, which is quite annoying for the users. Worse, if the user clicks on the "Remember Me" button it takes the user to Help. This is a bug on the clickable regions.

**Comment by RPangrle** [comment]
This is an Apple bug, I can repro it on MSIT pages in Safari on an iPhone 6/6S.

**Comment by RPangrle** [comment]
This got fixed sometime in iOS 9, I can't repro it on iOS 9 devices, but I can on iOS 8.
