### ISSUE TITLE
Crash in ADInstanceDiscovery.m - [__NSCFString UUIDString]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by szalap** [AzureAD/azure-activedirectory-library-for-objc#364]
The crash appears in [ADInstanceDiscovery validateAuthority:correlationId:completionBlock:] (ADInstanceDiscovery.m:149), where it tries to use UUIDString on correlationId object which is somehow not UUID at this point.
It happened only once, so it is not very devastating, but still.

**Comment by RPangrle** [comment]
This appears to be a synchronization issue on the correlation ID parameter and should be resolved once we fix #387

**Comment by RPangrle** [comment]
Fixed when we switched the correlationID to be a per-request property.
