### ISSUE TITLE
Authenticator app stay on screen without launching Office app back

### ISSUE THREAD

**Issue by cesarami** [AzureAD/azure-activedirectory-library-for-objc#370]
1. reset iOS Office creds;
2. install up-to-date Word and Authenticator on iOS 9 beta5;
3. finish FRE in Word, and sign in with a Microsoft OrgID, which is enrolled with 2FA, and authenticator app will be launched to finish auth;
4. after type in PIN and type the "Authenticate" button in Authenticator app, sign in is fully finished,

Expected:
Word should be launched back;

The issue:
Word is not launched back as expect;

I debugged into ADAL code, we did set the right redirect url but Office is not being called back,

**Comment by RPangrle** [comment]
This is probably a bug in broker SDK, or the Authenticator App, not ADAL
