### ISSUE TITLE
Collect sign in waiting time in callback response for telemetry

### ISSUE THREAD

**Issue by liwa** [AzureAD/azure-activedirectory-library-for-objc#384]
If possible we’d like to add some telemetry data about sign in waiting time so that we can have better understanding on how long people waiting for sign in.
Can you evaluate whether ADAL can record the waiting time and send it back as part of the sign in result?

**Comment by RPangrle** [comment]
@jasoncoolmax Is this data being collected in the current telemetry?

**Comment by jasoncoolmax** [comment]
Assuming "waiting time" is the time used for UI interaction, then yes :)
