### ISSUE TITLE
MSA account sign in broken if using xcode 7

### ISSUE THREAD

**Issue by niketk** [AzureAD/azure-activedirectory-library-for-objc#386]
We upgraded to xcode 7/ swift 2.0 and MSA sign in is now broken .. AAD account works.

9E7265EC-46DA-4CFF-A51D-F1C5A4F00876] ERROR: authorization error. Additional Information: An SSL error has occurred and a secure connection to the server cannot be made.. ErrorCode: 4294966096.

**Comment by RPangrle** [comment]
This is an MSA issue, not specifically ADAL related, but it's due to App Transport Security. (https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/master/README.md#note-regarding-ios-9) We are aware of the problem and are working on it.
