### ISSUE TITLE
[ADBrokerKeyHelper createBrokerKey:] creates errorFromNSError with errorDetails:nil resulting in exception

### ISSUE THREAD

**Issue by HiKumar-MS** [AzureAD/azure-activedirectory-library-for-objc#388]
[ADBrokerKeyHelper createBrokerKey:] creates errorFromNSError with errorDetails:nil resulting in NSInvalidArgumentException in [ADAuthenticationError initInternalWithDomain:...].
[ADAuthenticationError errorFromNSError:[NSError errorWithDomain:@"Could not create broker key." code:AD_ERROR_UNEXPECTED userInfo:nil] errorDetails:nil]

**Comment by RPangrle** [comment]
I think this is already fixed... @jasoncoolmax to verify.

**Comment by jasoncoolmax** [comment]
I tested the broker-dev branch, the following line in ADBrokerKeyHelper.m now can be successfully executed without throwing any exception:

[ADAuthenticationError errorFromNSError:[NSError errorWithDomain:@"Could not create broker key." code:AD_ERROR_UNEXPECTED userInfo:nil] errorDetails:nil]
