### ISSUE TITLE
Apple Bug: Intermittent keychain error -34018

### ISSUE THREAD

**Issue by siddheshcnaik** [AzureAD/azure-activedirectory-library-for-objc#392]
Hi,

We are getting following error randomly. 
2015-10-01 17:30:02.159 [2151:542849] ADALiOS [2015-10-02 00:30:02 - E45569F5-D2A1-4B36-9FC0-6410BA2004D2] ERROR: Error raised: 11. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode:(null) Details:Cannot read the items in the keychain. Error code: -34018. Query: {
   svce = "MSOpenTech.ADAL.1|aHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tL2NvbW1vbg|aHR0cHM6Ly9vdXRsb29rLm9mZmljZTM2NS5jb20v|MGVjZjQ1MzItZjJmYS00YjZlLWI1OWUtM2EzYzBmOTc2ZWEx";
}. ErrorCode: 11.

This causes the Office 365 SDK to hang up.

Could you please help us with this.

Thanks

**Comment by appcurry** [comment]
We are also running into this issue and it is causing our app to fail at random. The error does not get propagated to the top level call and it just hangs. 

Would appreciate any feedback from the developers of the Azure iOS SDK.

**Comment by RPangrle** [comment]
This unfortunately is a known iOS bug: https://forums.developer.apple.com/thread/4743 It appears to happen more when you're attached to the debugger and when low memory warnings occur.

**Comment by RPangrle** [comment]
The Office 365 SDK hanging is an issue for that SDK, not a specific ADAL issue. The error itself is an Apple bug, I don't see an ADAL bug here.
