### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by shankarsirigiri** [AzureAD/azure-activedirectory-library-for-objc#396]
ADAuthenticationErrorDomain ProtocolCode:invalid_resource Details:AADSTS50001: The application named https://slalomconsulting.sharepoint.com/sites/onevoice was not found in the tenant named slalomconsulting.onmicrosoft.com.

let resourceID : String = "https://slalomconsulting.sharepoint.com/sites/onevoice"

I am getting above error while integrating sdk,so please guide me to solve this issue.

Very urgent.

Thanks in advance.

**Comment by RandalliLama** [comment]
@shankarsirigiri 
Per this website it looks like your resource id should really be "https://slalomconsulting.sharepoint.com/"

https://samlman.wordpress.com/2015/02/27/using-adal-access-tokens-with-o365-rest-apis-and-csom/

```
The main thing to call out here really is the GetSharePointHost method that creates the Url that is used as the Resource ID when getting an access token.  The net of this advice is that no matter where your SharePoint site lives, you really want to use the root site as the Resource ID.  So if your o365 site is https://steve.sharepoint.com/sites/blazers, the Resource ID to get an access token should be https://steve.sharepoint.com.  Doesn’t matter where the site is in that hierarchy – from the root all the way down as far as you want to go – you want to make sure you use the root site as the Resource ID.  About a billion thanks to Dan K. for clearing that up for me; your Christmas card is in the mail!  The other thing worth noting is that you MUST include a trailing slash on the Url that you use as the Resource ID.  It cause ADAL no end of pain and suffering when you leave that out.  Both of these little gems are captured in those two lines of code above.  Yay!
```
