### ISSUE TITLE
Page loading forever when going through some ADAL sign in scenarios

### ISSUE THREAD

**Issue by cesarami** [AzureAD/azure-activedirectory-library-for-objc#406]
In ADAL for Mac when going over some paths for signing in there are some webviews that will load indefinitely. 

1. Clean keychain
2. Sign in with an account that will require phone/app verification. (Contact cesarami for the account I am using for reproing this) 
3. You will be asked for a verification code on given phone, cancel current sign in by choosing "sign out and sign in with another account"
4. On the new webpage select "Use another account"
5. Now the next webview will load forever.

ADAL is never returning anything to our webview, it seems that somewhere is the ADAL code the page is never actually requested.

**Comment by RPangrle** [comment]
This sounds like a server issue and I've never seen it repro'd. The "Sign in with another account" link specifically should never show up as long as you're using PROMPT_ALWAYS.
