### ISSUE TITLE
Resource bundle marked as executable prevents App Store submission

### ISSUE THREAD

**Issue by boxtcarpel** [AzureAD/azure-activedirectory-library-for-objc#410]
Apple is now enforcing that bundles which do not contain a bundle executable not be marked as such.
The current setup of the ADAL iOS bundle prevents apps from being submitted to the App Store.

ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/YourApp.app/ADALiOS.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

**Comment by RPangrle** [comment]
Fixed in PR #411
