### ISSUE TITLE
Guidelines on which branch is best to use?

### ISSUE THREAD

**Issue by Jtango18** [AzureAD/azure-activedirectory-library-for-objc#415]
Hi all,

I've been playing around with ADALiOS quite a bit. I'd love to contribute some code at some point if needed. I'm a little confused as to which branch I should be working with though. What is the difference between convergence, convergence-dev, dev etc?

Any guidance you can offer spelling this out would be great.

Cheers

JT

**Comment by RandalliLama** [comment]
@Jtango18 We have too many branches. :frowning: .  We are working toward merging many of these and hope to get down to only two main branches, master and dev.  If you have contributions please submit PR's against the dev branch for now.

**Comment by Jtango18** [comment]
Sweet. I'm working on a Swift port and wasn't sure which branch I should be basing it on.

**Comment by RandalliLama** [comment]
@Jtango18 Our of curiosity, what are you hoping to get out of a Swift port?  The objective-C implementation should be useable from Swift with very little overhead, no?

**Comment by Jtango18** [comment]
Absolutely it's useable. The migration work is mostly academic. It's helping to give me a strong understanding of the inner workings of the framework. 

I suspect that we will also start to see programmers coming in to the iOS development sphere who don't have a strong Objective-C background (I'm one of these, though arguably the process of migrating this means I'm much more well versed in Obj-C than I was 4 weeks ago). I think having the code base available in Swift makes it more accessible to people who might come from C#/Java backgrounds. 

Mostly, it's just a bit of fun. I have no expectation that it will be merged in to the official branch and I'm happy to maintain my own repository for it with help from anyone who wants to contribute :-)

**Comment by RandalliLama** [comment]
@Jtango18 Sounds great.  Let us know if we can help in any way.
