### ISSUE TITLE
scope header is missing in acquireTokenForAssertion 

### ISSUE THREAD

**Issue by kusosk** [AzureAD/azure-activedirectory-library-for-objc#418]
UseSAMLAssertionAsync is the API winOffice using to issue a access token for given SALM assertion, the request looks like this:
grant_type=urn:ietf:params:oauth:grant-type:saml1_1-bearer&assertion=PHNh....Pg==&client_id=d3590ed6-52b3-4102-aeff-aad2292ab01c&resource=https://testtesto365partnerapex-my.sharepoint.com/&scope=openid 

The response is like:
{"token_type":"Bearer",
"expires_in":"3600",
"scope":"user_impersonation",
"expires_on":"1447724201",
"not_before":"1447720301",
"resource":"https://testtesto365partnerapex-my.sharepoint.com/",
"access_token":"…SAM1w",
"refresh_token":"…",
"id_token":"eyJ...vbSIsInZlciI6IjEuMCJ9."}
We can get the user info from the id_token field, which contains the first/last name, providerId, tenantId and etc..
 
But for acquireTokenForAssertion, we send the request without &scope=openid attached, which leads to missing id_token fields in the response.

**Comment by RPangrle** [comment]
The right change here is probably to add the "openid" scope to the SAML flow and make sure we cache the tokens properly.
