### ISSUE TITLE
branch: convergence-dev Could not build module 'ADALiOS' while importing in swift project

### ISSUE THREAD

**Issue by artiy** [AzureAD/azure-activedirectory-library-for-objc#423]
I created a swift project and imported this library through pod. when I import ADALiOS module in a swift file, it gives me error while compiling the project. my pod file is:
```
platform :ios, '8.0'
use_frameworks!

target 'ADTesting' do
pod 'ADALiOS', :git => 'https://github.com/AzureAD/azure-activedirectory-library-for-objc', :branch => ‘convergence-dev’
end
```
error it was showing is: 

![screen shot 2015-11-30 at 4 24 00 pm](https://cloud.githubusercontent.com/assets/5718195/11469780/e8beb244-977e-11e5-98c0-b09ca226c758.png)

**Comment by mstritt-ka** [comment]
We have also seen this when trying to import via a pod, with the additional context that:
- Problem happens on Xcode 7.2
  - Both a Swift project similar to above
  - **And** a brand new Objective-C project just to test the pod import
- Problem does not happen on Xcode 7.1

FYI: Cocoapods v0.39.0

We **were** able to include the contents of the "ADALiOS" source folder directly into the Swift project as a subfolder, and successfully build and run it (after adding the "azure-activedirectory-library-for-objc/ADALiOS/ADALiOS/ADALiOS-Prefix.pch" file to the targets "Prefix header" build setting).

We would prefer to use Cocoapods (of course).

**Comment by mstritt-ka** [comment]
Could you please let me know what the fix was to this issue? I didn't see any checkins on this branch.

**Comment by artiy** [comment]
I did same as suggested by your reply. Deleted cocoapod instllation of ADALiOS and using files manually in my project solved it.
