### ISSUE TITLE
Error returned by ADAL library when it attempts to refresh an expired access token for AAD B2C

### ISSUE THREAD

**Issue by HoffmannKA** [AzureAD/azure-activedirectory-library-for-objc#424]
Using the convergence-dev branch (because that's the branch used by the B2C-NativeClient-iOS demo in GitHub).  I can successfully login and obtain an access token from ADAL.  Later, I call the following method against ADAuthenticationContext: acquireTokenSilentWithScopes:clientId:redirectUri:identifier:policy:completionBlock.  If the access token has not yet expired, the token is returned successfully.  If the access token has expired, ADAL attempts to use the refresh token to obtain a new access token.  The call out to AAD B2C fails.  ADAL parses the following from the response:

correlation_id: "bc723626-35dc-4609-87a8-1647f6bedf0d"
error: "invalid_request"
error_description: "AADSTS50091: Passed query string length exceeds supported limit.
    encodedRequest=\"rQIIAVWVucosCQGFufcfhJnBQRTFwMBARIT6qX0xq6qurn3t2pOia-va9_0F
        zOcpjMVQfACjYUIRBCOZBzD2Diaani84wTnwffEl8g6-g8AwZe_Qb9_gd_B3
        vwLzBCVQ6glACJgCKE4iAEU8YQBHMxLOIRSPU3z68Rc_-jU-_fnv2Of33__h
        Z_y___KPH_7rw4dvPn7428cvdXpdCtju66z758efs02ZdQvdpc6cTf-Dvn57
        q_bl67ef9M_vs_cpy6dsLpbv2R_fflH0ed4-uy6GE-i979oymfq5z5f3pG__
        -vbTT7Qpuyx6Jkk2z7_sh6wr02_fvvr__Nu3H_yXfPPZZ9999vE3H777_E9fZ
        ac0PT2z1EupSvhmCWDqDF1y120RUiv60B7iLHZhk5QiLlbcqrIS9f4u1zpv2X
        4PI-1gDbz4TnR-b1u3qJM1z9jZC8K4A-FVRVHpjcWMqi5pYjN2t9vzfknR8xl
        WjxbEetT252pDWNckex-_ZTvuCjokJt34QlrQw2q6M0EI76USo2Y92vDbSCk4
        klVLAdHMlPJFVqN7c3TjQAeVemarcwJjotnpOu_9vIlyanL7rqWVK-H0eT4Qg
        FUQERhETxu99LlOmMm1QLAevohlJt6pbbryGSYYyHPSlB5zR6CsNKqICOFEov
        xIEYGa-5jKV1KXRdhJbvzF6mgj3DVsfNbOiRPYUNIR-XAMObbaIzLDpLdmkAO
        regzXzIfQ-mEyutNaGgBwqjVEKT8vhzI81l7AoFnV7PBk9IZ6sbl057MI18xC
        hbKx7iiZHG4LGGSODOXdNYppdWi4L9qxcMqv1URXrd0r8hnZCxpQUgUztEcWk
        17hfm7WYyc-VCGY8SIhsvsOEHtiXvOiSCIyAGXUW8QewXf-2LMic_kNVKHNAO
        9yt8q3T9UIAzouslucDjvmLbjnDCrZku"
error_codes: [ 50091 ]
timestamp: "2015-11-30 21:08:46Z"
trace_id: "181d6257-d109-4fb7-9cfe-e8c531f1b858"
url: "https://login.microsoftonline.com/{directoryname}.onmicrosoft.com/oauth2/v2.0/token?x-client-Ver=3.0.0-pre.1"

where {directoryname} is the name of my AAD B2C tenant.

**Comment by artiy** [comment]
Hi,
I am facing exact same issue in my iOS application and also my Access_Token expires in one hour. 
Is there any solution for this? Please suggest.
Thanks

**Comment by shashank109** [comment]
I am facing exactly same issue in my iOS application and also my Access_Token expires in one hour.
Is there any solutions for this? Please suggest.
Thanks

**Comment by jasoncoolmax** [comment]
@shashank109 Could you please confirm that this still happens with the latest convergence-dev branch? if so, could you provide the logs such that I can look into details?

To get full logs of ADAL, you need to set the log level. 
I.e., assuming you are using the B2C-NativeClient-iOS demo in Github, put [ADLogger setLevel:ADAL_LOG_LEVEL_VERBOSE]; somewhere before you make the request, say put it in the beginning of method [samplesWebAPIConnector getClaimsWithPolicyClearingCache:].

PS: you may need to import the header file as well #import "ADALiOS/ADLogger.h".

**Comment by jasoncoolmax** [comment]
I am closing this as there is no response from original poster for more than 2 weeks.
