### ISSUE TITLE
ADALiOS refresh token issue

### ISSUE THREAD

**Issue by artiy** [AzureAD/azure-activedirectory-library-for-objc#436]
In my app, I implemented ADADiOS Login successfully. Login happens successfully returning access token also. But as soon the token expired, to get new access token from refresh token I called below method 

```
- (void) getTokenClearingCache : (BOOL) clearCache
                        parent:(UIViewController*) parent
             completionHandler:(void (^) (NSString*, NSError*))completionBlock;
{
    SamplesApplicationData* data = [SamplesApplicationData getInstance];
    // NSString *userId = [[NSString alloc]init];
    if(data.userItem){
        completionBlock(data.userItem.accessToken, nil);
        return;
    }
    
    /*
     if(data.userItem && data.userItem.userInformation)
     {
     userId = data.userItem.profileInfo.username;    }
     else
     {
     userId = nil;
     }
     */
    
    
    ADAuthenticationError *error;
    ADAuthenticationContext* authContext;
    authContext = [ADAuthenticationContext authenticationContextWithAuthority:data.authority error:&error];
    authContext.parentController = parent;
    NSURL *redirectUri = [[NSURL alloc]initWithString:data.redirectUriString];
    
    if(!data.correlationId ||
       [[data.correlationId stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]] length] == 0)
    {
        authContext.correlationId = [[NSUUID alloc] initWithUUIDString:data.correlationId];
    }
    
    [ADAuthenticationSettings sharedInstance].enableFullScreen = data.fullScreen;

    
    [authContext acquireTokenWithScopes:data.scopes
                       additionalScopes: nil
                               clientId:data.clientId
                            redirectUri:redirectUri
                             identifier:[ADUserIdentifier identifierWithId:data.userItem.profileInfo.username type:RequiredDisplayableId]
                         promptBehavior:AD_PROMPT_AUTO
                        completionBlock:^(ADAuthenticationResult *result) {
                            
                            if (result.status != AD_SUCCEEDED)
                            {
                                completionBlock(nil, result.error);
                            }
                            else
                            {
                                data.userItem = result.tokenCacheStoreItem;
                                completionBlock(result.tokenCacheStoreItem.accessToken, nil);
                            }
                        }];
}

```

As soon as the call ended , Bad request occurred. Error is shown in below  image

  
![screen shot 2015-12-12 at 3 48 17 pm](https://cloud.githubusercontent.com/assets/5718195/11761453/9557a8f8-a0e9-11e5-829f-493ca6f1e495.png)

Following error is also coming:
ADAuthenticationErrorDomain Details: The argument 'cacheItem.scopes' is invalid. Value:(null). ErrorCode: 2.

Is there anything which I am missing to get token??

**Comment by jasoncoolmax** [comment]
@artiy For the function call *acquireTokenWithScopes*, if you have set a client id value in scope, make sure it is the same as the client id you provided to the function call.

-----------------

If the above doesn't not solve your problem, could you please provide the logs such that I can look into details? (please use the lastest version convergence-dev branch :) )

To get full logs of ADAL, you need to set the log level. 
I.e., assuming you are using the B2C-NativeClient-iOS demo in Github, put [ADLogger setLevel:ADAL_LOG_LEVEL_VERBOSE]; somewhere before you make the request, say put it in the beginning of method [samplesWebAPIConnector getClaimsWithPolicyClearingCache:].

PS: you may need to import the header file as well #import "ADALiOS/ADLogger.h".

**Comment by jasoncoolmax** [comment]
I am closing this as there is no response from original poster for more than 2 weeks.
