### ISSUE TITLE
Add service error info in ADAL acquireToken call back

### ISSUE THREAD

**Issue by liwa** [AzureAD/azure-activedirectory-library-for-objc#438]
Can you add service info (error, correlation Id, etc) in acquireToken callback?
We intend to log these in some telemetry data and log data so that we have better understanding of how many auth failure are related to service side.
Especially, we need to identify the situation that the user cancel the request because the user sees auth failure and canceling is the only choice. 
Thanks,
Lin

**Comment by liwa** [comment]
We want those error details in sign in flow and refresh token flow.

**Comment by RPangrle** [comment]
@jasoncoolmax: I would start by adding correlation ID to the ADAuthenticationResult. The service error is already included in the authentication error (it's the "protocol code" bit), that of course is assuming that we actually hit the service, which isn't the case when tokens are removed underneath us.
