### ISSUE TITLE
 ADAL Keychain "__51-[ADKeychainTokenCacheStore addOrUpdateItem:error:]_block_invoke" operation failed with error code -25243..

### ISSUE THREAD

**Issue by artiy** [AzureAD/azure-activedirectory-library-for-objc#440]
I am using 'Convergence' branch for ADALiOS authentication in my swift project. To do so I copied all required files in my prjoect. Inside support file I have addde plist where all authority, client id, redirect uri etc info is saved. In addition of this I have added a. .entitlement file also with following content

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<string>$(AppIdentifierPrefix)com.microsoft.adalcache</string>
</array>
</plist>

Now before making any web service call  I am calling 

``` objectiveC
- (void)getToken:(UIViewController *)viewCont completionHandler:(void (^)(NSString *))completionBlock {
    //[self setStatus:@"Starting Acquire Token Silent." type:TALogStatus];
    
    //    NSURL* resource = [NSURL URLWithString:@"http://testapi007.azurewebsites.net/api/WorkItem"];
    ADAuthenticationError * error;
    
    ADUserDefaultsSettings* settings = [ADUserDefaultsSettings defaultSettings];
    
    //401 worked, now try to acquire the token:
    //TODO: replace the authority here with the one that comes back from 'params'
    NSString* authority = [settings authority];//params.authority;
    NSString* clientId = [settings clientId];
    NSString* userId = [settings userId];
    //NSString* __block resourceString = mAADInstance.resource;
    NSString* redirectUri = [settings redirectUri];
    //[ADTestAppLogger logMessage:[NSString stringWithFormat:@"Authority: %@", authority] type:TALogInformation];
    ADAuthenticationContext *context = [ADAuthenticationContext authenticationContextWithAuthority:authority
                                                                                             error:&error];
    if (!context)
    {
        //[self setStatus:error.errorDetails type:TALogError];
        return;
    }
    context.parentController = self;
    
    [context acquireTokenSilentWithScopes:[settings scopes]
                                 clientId:clientId
                              redirectUri:[NSURL URLWithString:redirectUri]
                               identifier:[ADUserIdentifier identifierWithId:userId]
                          completionBlock:^(ADAuthenticationResult *result)
     {
         if (result.status != AD_SUCCEEDED)
         {
             //[self setStatus:result.error.errorDetails type:TALogError];
             
             ADUserDefaultsSettings* settings = [ADUserDefaultsSettings defaultSettings];
             
             NSString* authority = [settings authority];
             NSString* clientId = [settings clientId];
             NSString* redirectUri = [settings redirectUri];
             BOOL validateAuthority = [settings validateAuthority];
             NSString* userId = [settings userId];
             
             ADAuthenticationError* error = nil;
             //[weakSelf setStatus:[NSString stringWithFormat:@"Authority: %@", params.authority]];
             ADAuthenticationContext* context = [ADAuthenticationContext authenticationContextWithAuthority:authority
                                                                                          validateAuthority:validateAuthority
                                                                                                      error:&error];
             if (!context)
             {
                 NSLog(error.errorDetails);
                 //[self setStatus:error.errorDetails type:TALogError];
                 return;
             }
             context.parentController = viewCont;
             
             NSArray* scopes = [settings scopes];
             NSArray* additionalScopes = [settings additionalScopes];
             
             //[self setStatus:@"Acquiring Token" type:TALogStatus];
             
             NSLog(@"Acquiring token");
             
             ADUserIdentifier* adUserId = [ADUserIdentifier identifierWithId:userId type:RequiredDisplayableId];
             NSString* policy = [[[ADUserDefaultsSettings defaultSettings] objectForKey:@"policies"] objectAtIndex:1];
             [context acquireTokenWithScopes:scopes
                            additionalScopes:additionalScopes
                                    clientId:clientId
                                 redirectUri:[NSURL URLWithString:redirectUri]
                                  identifier:adUserId
                              promptBehavior:AD_PROMPT_AUTO
                        extraQueryParameters:nil
                                      policy:policy
                             completionBlock:^(ADAuthenticationResult *result)
              {
                  if (result.status != AD_SUCCEEDED)
                  {
                      NSLog(result.error.errorDetails);
                      
                      //             [self setStatus:result.error.errorDetails type:TALogError];
                      return;
                  }else {
                      completionBlock(result.accessToken);
                  }
              }];
             
             
             return;
         }
         else {
             completionBlock(result.accessToken);

         }
     }];
}
```

As soon as my app starts, before making first web service call it asks for credentials and then inside my output log I am getting following error

```
ADALiOS [2015-12-17 09:50:08 - 1EC5EEC5-1205-4256-AC15-6051743A49A4] ERROR: Error raised: 11. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode: -25243 Details: ADAL Keychain "__51-[ADKeychainTokenCacheStore addOrUpdateItem:error:]_block_invoke" operation failed with error code -25243.. ErrorCode: 11.
``` 

This clearly indicates that adal is not able to store my token cache inside my keychain. Because of above error it is not able to get new access token using refresh token hence, login page is opening before each service call. Although there I don't need to enter my credentials but yes the screen comes up again and again.

**Comment by RPangrle** [comment]
The most common cause of this error is a lack of keychain entitlements. Make sure you have com.microsoft.adalcache in your keychain sharing groups entitlement.

**Comment by RPangrle** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-objc#set-up-keychain-sharing-entitlements-in-your-xcode-project

**Comment by artiy** [comment]
Yes i did tgat. Entitlement files exists in my project with value com.microsoft.adalcache. Still this issue is coming up

**Comment by mstritt-ka** [comment]
I was also unable to run on device with either "Keychain Sharing Entitlements" turned on, OR the following code (as recommended above):
`[[ADAuthenticationSettings sharedInstance] setSharedCacheKeychainGroup:@"<your.bundle.id.here>"];`

The only thing that worked was to set the keychain group to "nil" (my code in Swift):
`ADAuthenticationSettings.sharedInstance().sharedCacheKeychainGroup = nil`

**Comment by artiy** [comment]
Thanks a lot. setting ADAuthenticationSettings.sharedInstance().sharedCacheKeychainGroup= nil solved my  addOrUpdateItem issue perfectly. But as soon as I enter into my app I need to check whether token is already available in the keychain or not. Becuase on the basis of that only I will let user enter my app directly otherwise user will have to enter credentials and go through proper channel. For the same I wrote below code in ObjectiveC 

- (BOOL)isTokenValid {
    ADUserDefaultsSettings* settings = [ADUserDefaultsSettings defaultSettings];
    NSString* authority = [settings authority];
    NSError *error;
    ADAuthenticationContext *context = [ADAuthenticationContext authenticationContextWithAuthority:authority
                                                                                                 error:&error];

    ADAuthenticationError *ADError;// = [[ADAuthenticationError alloc] init];
    NSArray *allItems = [context.tokenCacheStore allItems:&ADError];
    
    if (allItems.count > 0) {
        NSString *token = [(ADTokenCacheStoreItem *)allItems[0] accessToken];
        if (token.length >0) {
            return true;
        }
    }
    return false;
}

But allItems is returning nil and because of this user needs to signin every time  he/she enters into my app. Can you please put more light on it?

**Comment by RPangrle** [comment]
The symptoms you describe match exactly the expected behavior if you have no keychain entitlements at all. I would double check the executable bundle (https://developer.apple.com/library/ios/qa/qa1798/_index.html) and the device logs when you run the app to see if any errors come up.

**Comment by artiy** [comment]
Ye you are absolutely right. I am getting following error in my device log
```
"secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found"
```

But as per knowledge I am following all the required steps to add entitlements in my app. Also there is one more crash coming up in line 

```
enumerateLinesUsingBlock

- (NSString*)adSpaceDeliminatedString
{
    NSMutableString* string = [NSMutableString new];
    
    __block BOOL first = YES;
    
    [self enumerateLinesUsingBlock:^(id obj, BOOL *stop) {
        if (![obj isKindOfClass:[NSString class]])
        {
            return;
        }
        
        if (!first)
        {
            [string appendString:@" "];
        }
        else
        {
            first = NO;
        }
        
        [string appendString:obj];
    }];
    
    return string;
}
```

I am not able to understand the problem with my app Id. If you have reference please do help me.

**Comment by RPangrle** [comment]
Are you on a corporate dev account? If you are and don't have admin privs then you'll fail to add the keychain sharing group to the App ID even though Xcode will pretend like everything worked. :(

Last time I had to deal with that nonsense it required wrangling someone with admin privs, having them open the xcode project on their machine with their Apple Dev Account, removing the keychain sharing groups then adding them back and flipping the switch back and forth until it finally took.

**Comment by artiy** [comment]
Were you using convergence branch b2c?

**Comment by RPangrle** [comment]
The branch is irrelevant.

**Comment by artiy** [comment]
For the same thing when we tried in b2b convergence everything was working fine. But when it comes to b2c refresh token is   not able to give access token.
