### ISSUE TITLE
Rename "ADAuthenticationBroker" to "ADWebAuthController" and make private

### ISSUE THREAD

**Issue by RPangrle** [AzureAD/azure-activedirectory-library-for-objc#447]
This class really should not be public, the only public part of it is the cancel API and we will move that API elsewhere.

**Comment by jasoncoolmax** [comment]
How about adding a public visible *cancel* function in ADAuthenticationRequest? Such that such a public visible *cancel* function will call the private *cancel* function of ADAuthenticationBroker?

**Comment by RPangrle** [comment]
ADAuthenticationRequest is a private interface and I'm inclined to keep it as such.
