### ISSUE TITLE
Replace NSURLConnection with NSURLSession

### ISSUE THREAD

**Issue by RPangrle** [AzureAD/azure-activedirectory-library-for-objc#483]
NSURLConnection was deprecated in iOS 9.

**Comment by RPangrle** [comment]
Looking at the NSURLSession API this is going to have to wait for a 2.2 at least. It's a pretty big change with a lot of potential side effects.

**Comment by RPangrle** [comment]
With iOS 10 coming out Apple is going to be less-and-less concerned about breaking something that was deprecated in iOS 9. We should probably look at doing this soon.

**Comment by unpluggedk** [comment]
This has been completed as a PR referenced above.
