### ISSUE TITLE
Error 400 may not return a JSON response and will result in a failure

### ISSUE THREAD

**Issue by kpanwar** [AzureAD/azure-activedirectory-library-for-objc#498]
Error 400 may not return a JSON response and will result in a failure. Please confirm with someone from server side. https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/491/files#r52533426

**Comment by RPangrle** [comment]
In this case the connection already failed anyways, and we properly handle the JSON error, I wouldn't want to do any out-of-spec error processing in this case.
