### ISSUE TITLE
9.2.1 Error with URL Scheme

### ISSUE THREAD

**Issue by mevdev** [AzureAD/azure-activedirectory-library-for-objc#544]
http://stackoverflow.com/questions/35710225/ios-9-canopenurl-error-for-adal-login/35733501#35733501

There seems to be problems with the URL Scheme for iOS apps with ADAL iOS library.

URL: "msauth://broker" - error: "This app is not allowed to query for scheme msauth"

Fixed by adding this your app's plist:
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>msauth</string>
	</array>

It still has this error though:
canOpenURL: failed for URL: "msauth://broker" - error: "(null)"

**Comment by nhart12** [comment]
+1 I have encountered this same issue

**Comment by RPangrle** [comment]
That's some broker code that never should have made it into the 1.2.x line but was erroneously merged into dev before we forked for 1.2.x. I'll be removing it in 1.2.6 but for now the error message is harmless.
