### ISSUE TITLE
Redirecting to SignIn Page

### ISSUE THREAD

**Issue by Ramakrishna530** [AzureAD/azure-activedirectory-library-for-objc#548]
Hi Team,
I've integrated SingleSignOn through this library.I'm able to SignIn to the application.i'm able to access the URL's with this token cache, but when i terminate and relaunch the application ,when i try to access the URL's it is redirecting to SignIn page instead of original page

**Comment by RPangrle** [comment]
I'm confused what opening URLs has to do with the iOS library...
