### ISSUE TITLE
The token cache store for this resource contain more than one user. Please set the 'userId' parameter to determine which one to be used

### ISSUE THREAD

**Issue by shashank108** [AzureAD/azure-activedirectory-library-for-objc#551]
I am using ADALiOS convergence branch for user authentication in a workspace which contains two different apps. I am having different users for both the apps. When I login into one app with a user, it successfully authenticate the user and when I install second app into the same device with other user it won't sign in and gives me following error-

**"The token cache store for this resource contain more than one user. Please set the 'userId' parameter to determine which one to be used.."**

For more details you can visit stackoverflow link . Here is the link-

[http://stackoverflow.com/questions/35932065/the-token-cache-store-for-this-resource-contain-more-than-one-user-please-set-t
]

Can you please suggest me how to login with multiple user in different apps in same device?
Thanks

**Comment by shashank108** [comment]
Hello,
I was digging some more into this issue and just want to know how I can add userId into the cache,so that I can differentiate the users while picking them from cache. Please someone look into this issue.
Thanks.

**Comment by RPangrle** [comment]
The userId has to come from the server in the id token or profile info. Without it we don't know which token to give you. Specifying a userId in the acquireToken call should also make this go away.

**Comment by neerajyadav** [comment]
How can I get the userId even before calling _acquireToken_ method? In case of azure B2C tenant the profile info coming from the server is not complete. The only information it has is:
`{
  "ver": "1.0",
  "tid": "47e7d095-0860-410b-a9df-ed6992458ba0",
  "sub": null,
  "name": "Arti yadav",
  "preferred_username": null,
  "idp": null
}`

In this ios sdk profile object is filled only from the profileInfo coming from the server, which is not sufficient. It should extract profile from profileInfo as well as from JWT. It is a bug in existing sdk. I'm soon going to raise a bug for this.

**Comment by jasoncoolmax** [comment]
@neerajyadav could you please provide the logs of both apps? such that I can look into the details of the issue.

**Comment by RPangrle** [comment]
ADAL does not crack open access tokens or refresh tokens as they are not meant for the client and can be encrypted. 

I would recommend either not sharing the same client ID between the two apps, or not sharing a keychain cache between the two apps.

**Comment by jasoncoolmax** [comment]
I am closing this as there is no response from original poster for more than 2 weeks.

**Comment by himanthmaddi** [comment]
Provide more information in the same request.

You can do a new AcquireTokenSilent request providing some more information that allows ADAL to definitively pick a cache entry. In this case, ADAL needs a userId meaning your app would need to store or lookup this value and pass it in the request. In our example,
[authContext acquireTokenSilentWithResource:resource clientId:clientId redirectUri:[NSURL URLWithString:redirectURI] userId:userId completionBlock:^(ADAuthenticationResult *result) {

}];

**Comment by supervixen** [comment]
This can happen on the first time the user has installed the app, and when the app didn't yet have a chance to make any successful acquire token calls nor store the userId. What's the recommended error handling for this case? Are the users supposed to know their ADAL user Id and app developers supposed to provide a UX for the user to enter their userId's manually ?
