### ISSUE TITLE
Project is not using recommended build settings

### ISSUE THREAD

**Issue by d-ronnqvist** [AzureAD/azure-activedirectory-library-for-objc#553]
When opening this project in Xcode 7.2, there is a warning that the project is not using the recommended settings.

Updating would perform these changes

**ADALiOSTests:**
 - Adopt the "Product Bundle Identifier" build setting.

**ADALiOSBundle:**
 - Upgrade Base SDK Configuration to Latest iOS.

**ADAL Mac:**
 - Remove the Architectures setting, so that Xcode can automatically select architectures.

**ADAL:**
 - Turn on "Build Active Architectures Only" for Debug builds
 - Turn on "Enable Testability" for Debug builds

---

As I see it, there is no reason why these settings should match the recommended settings. Right now,  not using recommended build settings is only creating noise (warnings).

**Comment by RPangrle** [comment]
It looks like you fixed this in #554
