### ISSUE TITLE
Build errors for ADAL Mac in Xcode 7.3 beta

### ISSUE THREAD

**Issue by d-ronnqvist** [AzureAD/azure-activedirectory-library-for-objc#555]
When building ADAL Mac in Xcode 7.3 beta, there are build errors (unused result warnings treated as errors `[-Werror,-Wunused-value]`) wherever the `SAFE_ARC_RETAIN`, `SAFE_ARC_AUTORELEASE`, etc. macros are used.

For example

    error: expression result unused [-Werror,-Wunused-value]
    SAFE_ARC_RETAIN(_sessionKey);
                    ^~~~~~~~~~~

    note: expanded from macro 'SAFE_ARC_RETAIN'
    #   define SAFE_ARC_RETAIN(x) (x)
                                   ^

**Comment by RPangrle** [comment]
I believe you fixed this in your PR #556. I'm not seeing build errors in the final version of 7.3
