### ISSUE TITLE
Add iOS Extension Support

### ISSUE THREAD

**Issue by liwa** [AzureAD/azure-activedirectory-library-for-objc#560]
UIApplication sharedApplication is not supported in our extension target. 
https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6
One approach can be that ADAL allow us to define macro to separate extension target from main application target.

**Comment by RPangrle** [comment]
This would be interesting to try to tackle for 2.1, but might not get in on time. There's also some questions about being able to do auth in an extension. It's possible for embedded auth, but brokered auth would not work. We can't even call canOpenURL: to check if the broker is there. @brandwe would it be better to just not support interactive auth at all?

**Comment by ogkent** [comment]
> would it be better to just not support interactive auth at all?

This would work for us. 👍

**Comment by brandwe** [comment]
I'd be fine with that in the extension, yes.

**Comment by RPangrle** [comment]
Fixed in #674
