### ISSUE TITLE
ADPersistenTokenCacheStore module issues with __declspec

### ISSUE THREAD

**Issue by damienpontifex** [AzureAD/azure-activedirectory-library-for-objc#565]
Integrating ADALiOS into a Swift project via cocoapods and using framework targets I am getting compilation errors of the ADALiOS module at https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/master/ADALiOS/ADALiOS/ADPersistentTokenCacheStore.h#L44-L46 of:

- Duplicate member '__declspec'
- Expected ')'
- Expected parameter declarator
- Expected ';' at end of declaration list

I was using the podspec version 1.2.4 and tried upgrading to 3.0.0-pre3 to see if the issue was resolved, but still seeing the same errors.

See here for project that reproduces the issue https://github.com/damienpontifex/ADALErrorSample

_Update_: Using Xcode 7.3 (Swift 2.2)

**Comment by aminbagheri** [comment]
getting same error with Xcode 7.3 (Swift 2.2)

**Comment by fgrmt** [comment]
Same errors for me. Using XCode 7.3.

**Comment by nhart12** [comment]
As a temporary workaround, commenting out the lines throwing the error doesn't seem to have any negative affects. Albeit with little testing.

**Comment by egrimmius** [comment]
Same errors here as well.  Using XCode 7.3, Swift 2.2.

**Comment by RPangrle** [comment]
Can you try ADALiOS 1.2.5 please?

**Comment by amin-b** [comment]
unfortunately same compile error with 1.2.5 (Xcode 7.3, Swift 2.2, via CocoaPods and use_frameworks!).

**Comment by amin-b** [comment]
It seems __declspec attribute is not supported anymore in Xcode 7.3, by removing it, everything works fine. If that's the case and will not cause any side effects, is it possible to have a patch on 1.2.5?

**Comment by RPangrle** [comment]
I've pushed a 1.2.5.1 to CocoaPods that removes the offending header that was tripping up Xcode 7.3. The header in question was not used anywhere in ADAL.
