### ISSUE TITLE
Use ADALiOS for On-prem exchange and Office 365 dedicated

### ISSUE THREAD

**Issue by siddheshcnaik** [AzureAD/azure-activedirectory-library-for-objc#569]
Hi,

Is there a way to port this library to use against On-prem exchange or Office 365 dedicated?

Thanks

**Comment by RPangrle** [comment]
No. ADAL is an OAuth library. On-Prem Exchange does not currently support OAuth. And "port" refers to getting code from one platform working on another, not changing the protocol the code implements entirely.
