### ISSUE TITLE
Authenticating to Web API

### ISSUE THREAD

**Issue by karlbarek** [AzureAD/azure-activedirectory-library-for-objc#573]
Right now, I have a native azure app that my iOS app uses ADAL to authenticate to with no issues. I've added a Web API in azure and it's being managed by the Azure API Management resource. I have this API using an oAuth server that uses Azure AD for authentication (all created within the Azure API Management). 
The issue I'm having is the oAuth token I'm receiving from my iOS App is not being accepted by my Web API. They are both using oAuth to the same Azure Active Directory.  I tried changing in my iOS app, to use the Web API app client ID instead of the native app client ID. The issue then becomes during authentication, it needs a "client_secret" in the request. Looking at the ADAL library, I'm not seeing a method to get a token that passes in a client secret as a parameter.

**Comment by RPangrle** [comment]
You must use a native client ID with ADAL for iOS. What parameters are you using with ADAL? If you're getting a token back from ADAL then this is not an ADAL bug, rather a configuration issue with your server.
