### ISSUE TITLE
Access token validation failure

### ISSUE THREAD

**Issue by peted70** [AzureAD/azure-activedirectory-library-for-objc#583]
I am using the convergence_dev branch and attempting to access the graph api using converged auth (https://graph.microsoft.com/v1.0/drives/root/children) and am getting back an access token but I get the following response when I try to use it:
Optional({
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure.",
    "innerError": {
      "request-id": "313a66f4-6a57-4aa1-ae5d-ed5636c93571",
      "date": "2016-04-05T11:13:43"
    }
  }
})
I have a working UWP sample and have based my IOS code on this. When I decode my token it doesn't appear to contain any scopes whereas my working UWP token has the files.read scope defined within it . What is the best way to diagnose this?

my code:
            let scopes: [String] = []
            let additionalScopes: [String] = ["https://graph.microsoft.com/files.Read"]
    
            ac.parentController = self;
            ac.acquireTokenWithScopes(scopes, additionalScopes: additionalScopes, clientId: ClientId, redirectUri: NSURL(string: RedirectUri), promptBehavior: AD_PROMPT_ALWAYS, completionBlock: {
                (result: ADAuthenticationResult!) in
                if (result.accessToken != nil) {
                    print(result.accessToken)

                    let config = NSURLSessionConfiguration.defaultSessionConfiguration()
                    let headers = [
                        "Authorization": "Bearer " + result.accessToken
                    ]
                    config.HTTPAdditionalHeaders = headers
                    let session = NSURLSession(configuration: config)
                    let url = NSURL(string: "https://graph.microsoft.com/v1.0/me/drive/root/children")
                    let task = session.dataTaskWithURL( url!, completionHandler: {
                        (data, response, error) -> Void in
                        if(error != nil) {
                            // If there is an error in the web request, print it to the console
                            print(error!.localizedDescription)
                        } else {
                            print(NSString(data: data!, encoding: NSUTF8StringEncoding))
                        }
                        self.busy = false
                    })
                 
                    task.resume()
                }

**Comment by michaelloistl** [comment]
I'm getting the same error response for a request to `GET https://graph.microsoft.com/v1.0/me` using a token successfully received through:
````
context.acquireTokenWithScopes(["https://graph.microsoft.com/profile"], additionalScopes: [], clientId: clientID, redirectUri: NSURL(string: redirectUri) , promptBehavior: AD_PROMPT_AUTO, completionBlock: { (result) in                
    if result.status != AD_SUCCEEDED {
        completion(accessToken: nil, error: result.error)
    } else {
        self.accessToken = result.accessToken
        completion(accessToken: result.accessToken, error: nil)
     }
})
````
Is there anything wrong with my scope?

I'm using `pod 'ADALiOS', '~> 3.0.0-pre4'`

**Comment by michaelloistl** [comment]
@jasoncoolmax would you be able to look into this issue. I have to ship an update with Office365 login, but can't as I can't get AD v2 working (it was all working with v1).
/cc @RPangrle

**Comment by jasoncoolmax** [comment]
@michaelloistl ADAL is supposed to get the token from server for you. But if the access token is rejected in your case, I guess getting more information on why the token is rejected from the server side will be really helpful :)

**Comment by michaelloistl** [comment]
@jasoncoolmax thank you for your quick reply.

From `context.acquireTokenWithScopes:additionalScopes:clientId:redirectUri:promptBehavior:completionBlock:` I get `result.status` = `AD_SUCCEEDED` with an access_token like `eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSJ9.eyJhdWQiOiJlYTFiMjFmNy0yZDc0LTRlZjUtYThhOS1hNjFhYjBiZWYwMDQiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vNjQxOTQxNTgtZDIyNy00YTkyLWE4YzItNWRhZGQ5ZjhkMjAyL3YyLjAiLCJpYXQiOjE0NjM2ODM4MzcsIm5iZiI6MTQ2MzY4MzgzNywiZXhwIjoxNDYzNjg3NzM3LCJpcGFkZHIiOiIxNTQuNTguOTguMTkwIiwibmFtZSI6Ikxvb3BkIEFjY291bnQiLCJvaWQiOiJiMDVmMmViMS1hOTBjLTQ5N2ItODE0Ni02NTIyNmNiODU1MjgiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJMb29wZEB0YWJsZXQtYWNhZGVteS5jb20iLCJzdWIiOiJCVGVJbGFoNkdUejhRVl9tbXFzQ215UTd4MUhCS0pQcTBrNWp2MTJCdEx3IiwidGlkIjoiNjQxOTQxNTgtZDIyNy00YTkyLWE4YzItNWRhZGQ5ZjhkMjAyIiwidmVyIjoiMi4wIn0.gASUn2dFv50Rb2vQ_3qB2pVHvQjRLmYWDJMV2K15UT43AltgQ-LR17B9-WVQ5lK5bgc_aYr-z-ILqrZVPdte9mbNYRmsqpfKblJ-BbEPJSGEN870yeByJJ4bqkS-H-lSCHwUONl2UFE4dy1DtqsGPw2msOFDsPZAyAAhikQz2LdN773CD06HUYgveGdnvc1RF2LGCB373GYLIMh4tdrhK0PLR-RBHHOqiQwDIKkEU0wAZtvbUYQlKae41gmgJGlZ7mDeg4xPyHbbzWqNXUur18Aan4nLDTykWdfrMy-jEKtCeGV6d_HOccqcE9dDd03JuMVnjdB2rbeAXo0P4KuE2w`

`GET https://graph.microsoft.com/v1.0/me` returns however with
````
{
    error =     {
        code = InvalidAuthenticationToken;
        innerError =         {
            date = "2016-05-19T18:55:38";
            "request-id" = "4b4b16d3-0e1f-4816-bf49-6225be8fe43a";
        };
        message = "Access token validation failure.";
    };
}
````

How can I get more information on why the token is rejected from the server side?

**Comment by jasoncoolmax** [comment]
@michaelloistl I have checked your access token, there is no scope in it. My guess is that, your scope value is not in a good shape. 

Can you try "profile" as scope value instead of "https://graph.microsoft.com/profile"? Please let me know if it works :)

**Comment by michaelloistl** [comment]
Have tried that already. This is the `access_token` I get back with `scopes = ["profile"]`:
`eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSJ9.eyJhdWQiOiJlYTFiMjFmNy0yZDc0LTRlZjUtYThhOS1hNjFhYjBiZWYwMDQiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vNjQxOTQxNTgtZDIyNy00YTkyLWE4YzItNWRhZGQ5ZjhkMjAyL3YyLjAiLCJpYXQiOjE0NjM3NzY2NDgsIm5iZiI6MTQ2Mzc3NjY0OCwiZXhwIjoxNDYzNzgwNTQ4LCJpcGFkZHIiOiIxNTQuNTguOTguMTkwIiwibmFtZSI6Ikxvb3BkIEFjY291bnQiLCJvaWQiOiJiMDVmMmViMS1hOTBjLTQ5N2ItODE0Ni02NTIyNmNiODU1MjgiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJMb29wZEB0YWJsZXQtYWNhZGVteS5jb20iLCJzdWIiOiJCVGVJbGFoNkdUejhRVl9tbXFzQ215UTd4MUhCS0pQcTBrNWp2MTJCdEx3IiwidGlkIjoiNjQxOTQxNTgtZDIyNy00YTkyLWE4YzItNWRhZGQ5ZjhkMjAyIiwidmVyIjoiMi4wIn0.PwtDB2DiLYboNM3tqrmMgAY5uwNTJPaumkyBNoXNVP1Ie7q1cPpwCYkkhHsqnKFinV1v0uqpLW7ioi0BxeSU24qZrko3k1eRsaRQAJ766wNos132yU0HCtpcz-FXH5ej_IbY-jLXDU31klI8QZI2Z73Wbh_ebMwwFF1ob5dfyLQIepW7slMClP9GGwTLyQCRy2VIt1zKJFMU_S5DIO6YrMMQY2NxN_Ib0EaNjh9G134VFr1mFr0ZCMl8ZWBWIcl_X7XUjiXTw7wIdR9rIXZAluvZoe4zlCZpGhdFC2-ZFAsjKMoAFeQls9Wm1YtAYV6wGEHPs5d81QiP34NWGsWuag`

**Comment by michaelloistl** [comment]
@jasoncoolmax any sample code for the api v2 that would show an implementation that's working?

**Comment by michaelloistl** [comment]
@jasoncoolmax any ETA on a solution for that issue?

**Comment by michaelloistl** [comment]
@jasoncoolmax is there anything I can do to help you investigate this issue?
I really need that solved, as otherwise I can't push my release .... getting super urgent!

**Comment by RPangrle** [comment]
The convergence previews of ADAL are not to be used in production code, they're provided for experimental purposes only.

**Comment by michaelloistl** [comment]
@RPangrle having exact same issue with official version installed via cocoapods `pod 'ADALiOS', '~> 3.0.0-pre4'`.

**Comment by RPangrle** [comment]
That's also a preview release, thus the 'pre' in the version number.

**Comment by michaelloistl** [comment]
@RPangrle is there a working (non preview) version that can be used with api v2 for production?
`pod 'ADALiOS', '~> 3.0.0-pre4'` is what I get from https://cocoapods.org/pods/ADALiOS

**Comment by RPangrle** [comment]
No, the v2 API is still in preview as well.

**Comment by michaelloistl** [comment]
We have the v2 API working server side as well as from Android, it's just the iOS side that isn't working.
Is there an ETA for when the v2 API will be out of preview?

**Comment by jasoncoolmax** [comment]
@peted70 @michaelloistl We have made some bug fixes in recent release. Feel free to try out 3.0.0-pre6.

**Comment by RPangrle** [comment]
Closing due to lack of feedback.

**Comment by kibagami** [comment]
Experiencing the same issue with AdalJS v1.0.11

**Comment by mborysenko** [comment]
Experiencing the same issue with AdalJS v1.0.11. No matter which api is requested beta or v1.

**Comment by drcrook1** [comment]
I think I'm experiencing this issue.  https://github.com/Azure/azure-data-lake-store-python/issues/133

**Comment by NazarovVassil** [comment]
Hello!

I had the same issue: "Access token validation failure" with one of the demos.  It turned out that these two entries in App.config: "**ida:GraphResourceId**" and "**ida:GraphEndpoint**" both had the erroneous value of "**https://graph.windows.net/**" whereas the correct value seems to be "**https://graph.microsoft.com/**". The error went away after the fix.

HTH

**Comment by muralidharvr** [comment]
> Hello!
> 
> I had the same issue: "Access token validation failure" with one of the demos. It turned out that these two entries in App.config: "**ida:GraphResourceId**" and "**ida:GraphEndpoint**" both had the erroneous value of "**https://graph.windows.net/**" whereas the correct value seems to be "**https://graph.microsoft.com/**". The error went away after the fix.
> 
> HTH

Yes, this worked! By changing to https://graph.microsoft.com, we were able to generate the right bear token and able to create the Guest user in Azure B2C.
