### ISSUE TITLE
AD_ERROR_NON_HTTPS_REDIRECT for about:blank

### ISSUE THREAD

**Issue by alexduong** [AzureAD/azure-activedirectory-library-for-objc#585]
One of our clients AAD login page triggers a "about:blank" page. This causes the AAD login screen to appear and disappear right away. The reason is this line of code

if (![requestURL hasPrefix: @"https"])

in ADAuthenticationWebViewController.m line 163

throws AD_ERROR_NON_HTTPS_REDIRECT when requestURL is "about:blank". Is it acceptable to exclude urls that are "about:blank" in the check?

**Comment by kpanwar** [comment]
Fixed.

**Comment by alexduong** [comment]
Thanks!

**Comment by ill** [comment]
Can we do a 1.2.5.2 release as well with this fix?
