### ISSUE TITLE
2 ADTokenCacheStoreItems are created; causing the refresh token logic to fail

### ISSUE THREAD

**Issue by 5fcgdaeb** [AzureAD/azure-activedirectory-library-for-objc#598]
Upon a successful login, 2 ADTokenCacheStoreItems are created. One of them contains the accessToken (refreshToken is nil) and the other one contains the refreshToken (accessToken is nil). This is fine, but it causes the refresh token logic to fail. 

The [attemptToUseCacheItem:] method uses the ADTokenCacheStoreItem that contains the accessToken. If the accessToken is expired, it checks the refresh token. In this item, the refresh token is nil so the whole process fails with the 'Attempting to use an item without refresh token' error.

What might be the problem here?
<img width="476" alt="screen shot 2016-04-13 at 11 15 48" src="https://cloud.githubusercontent.com/assets/877496/14488801/3ea22f06-016a-11e6-95bd-b7183d1ce513.png">

**Comment by RPangrle** [comment]
The access token is stored separately from the Multi Resource Refresh token in the cache for ADALiOS. If you call acquireTokenSilent it will successfully refresh an AT from the MRRT.

The line "The second item (with the refresh token) is actually never accessed." is false. Look at -attemptToUseCacheItem: in ADAuthenticationContext (1.2.x) or ADAuthenticationRequest (2.1) you can see where ADAL looks for the MRRT and tries it. Look for the "//Try
 multi-resource refresh token if not currently trying it" comment if you're having a hard time finding it.

There is a considerable amount of unit testing around this very scenario and you try try it manually in the test app as well. The only way you see the behavior you claim is if you're not using the proper acquireToken entry points.

**Comment by 5fcgdaeb** [comment]
Thanks Ryan for the info. The unit tests actually did help, I hadn't noticed them before. You are right, it is working well; I have missed the part in the [findCacheItemWithKey:] method. That method does the switch from the access token to the refresh token if the access token is expired.
