### ISSUE TITLE
Crash when accessing ADAuthenticationResult.tokenCacheStoreItem.refreshToken

### ISSUE THREAD

**Issue by tbechtum** [AzureAD/azure-activedirectory-library-for-objc#618]
Hi,

I am evaluating your iOS library in a Xcode 7.3 Swift project by using an Azure AD client app registration. The access token is received successfully by acquireTokenWithResource. After the first call (successful login) I could receive the refresh token in tokenCacheStoreItem.refreshToken. But after this any access to tokenCacheStoreItem.refreshToken fails after acquireTokenWithResource and there is this exception:
fatal error: unexpectedly found nil while unwrapping an Optional value.
Thanks for help.

**Comment by jasoncoolmax** [comment]
@tbechtum could you please provide us the logs such that I can take a look at the problem in detail?

**Comment by jasoncoolmax** [comment]
I am closing this as there is no response from original poster for more than 2 weeks.
