### ISSUE TITLE
Can't install ADALiOS swift project & XCode 7.3 via cocoapods.

### ISSUE THREAD

**Issue by buskerone** [AzureAD/azure-activedirectory-library-for-objc#619]
Having issues installing ADALiOS on a swift project using XCode 7.3 via cocoapods.
podfile: 
pod 'ADALiOS', :git => 'https://github.com/AzureAD/azure-activedirectory-library-for-objc', :branch => 'convergence-dev'

Added to bridging header correctly but it give me an error "Could not build module 'ADALiOS'."

Any other user having the same issue? 
@jasoncoolmax

**Comment by RPangrle** [comment]
Duplicate of #578
