### ISSUE TITLE
Extra whitespace before email address causes crash

### ISSUE THREAD

**Issue by joelklabo** [AzureAD/azure-activedirectory-library-for-objc#628]
If you login with the email: "joel@somethign.com" it works. If you login with " joel@something.com" NSURL URLWithString will return nil. 

ADAuthenticationRequest+WebRequest Line 427

**Comment by jasoncoolmax** [comment]
@joelklabo May I know which function did you call to log in? what are the parameters? I am trying to reproduce the issue :)

**Comment by jasoncoolmax** [comment]
I cannot reproduce it. I am closing this because there is no reply from the original poster for more than 2 weeks.
