### ISSUE TITLE
How to simulate an expired token scenario?

### ISSUE THREAD

**Issue by roligtroll** [AzureAD/azure-activedirectory-library-for-objc#629]
We need to make some tests regarding cases where the token is expired and it is not practical to wait a few hours each time. Is it possible to force the library to come out with an expired token error?

**Comment by RPangrle** [comment]
You can point the ADAL test app at the same keychain sharing group you use in your main app and use the cache view to manually expire or invalidate tokens. Note this only works on device, as keychain sharing groups don't work properly in the simulator.
