### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by clement89** [AzureAD/azure-activedirectory-library-for-objc#653]
I'm trying to sign in to Azure service using the following code 

ADAuthenticationError *error = nil;

authContext = [ADAuthenticationContext authenticationContextWithAuthority:@"https://login.windows.net/SwiftMeap_TST.onmicrosoft.com"
                                                                                error:&error];
I got an error message that tenant name is not a valid DNS name.

![simulator screen shot 26-may-2016 4 54 36 pm](https://cloud.githubusercontent.com/assets/11992113/15601500/53e2e84a-240d-11e6-8970-0b15fce13d6f.png)

**Comment by jasoncoolmax** [comment]
@clement89 I guess it is because your authority is not correct. Could you please double check the correctness of the authority?
