### ISSUE TITLE
User is requested to install company portal, when it is already installed

### ISSUE THREAD

**Issue by dimabs** [AzureAD/azure-activedirectory-library-for-objc#659]
1. Enroll device using company portal
2. Try to fetch token, enter username/password
3. User gets message in the web dialog that device security needs be improved. Web dialog has button '"Enroll". When click on it takes you to Company Portal page in AppStore
Note: can't get the log at this point, due to blocker described in https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/657

**Comment by jasoncoolmax** [comment]
@dimabs make sure the two apps are signed at the same level (dev, enterprise, etc.), otherwise they cannot share the same cache.

**Comment by dimabs** [comment]
what two apps are you referring to?

2016-06-01 23:25 GMT-07:00 Yong Zeng <notifications@github.com>:

**Comment by jasoncoolmax** [comment]
the company portal app and the app you used to fetch token in step 2.
