### ISSUE TITLE
cant call authContext.tokenCacheStore removeAllWithError:nil on swift

### ISSUE THREAD

**Issue by masbenx** [AzureAD/azure-activedirectory-library-for-objc#664]
i try to logout and using authContext.tokenCacheStore removeAllWithError:nil on swift with this code
`ADAuthenticationContext.tokenCacheStore.removeAllWithError(nil)` 
but seems tokenCacheStore function wont call in swift

**Comment by jasoncoolmax** [comment]
@masbenx removeAllWithError has been removed as it could be easily abused.
For iOS, you should use the [ADKeychainTokenCache removeAllForClientId:error:] or [ADKeychainTokenCache removeAllForUserId:clientId:error:]

You can take a look at ADKeychainTokenCache.h for more information.

**Comment by amteklab** [comment]
@jasoncoolmax thanks.
