### ISSUE TITLE
Login fails if MS Authenticator app is not installed

### ISSUE THREAD

**Issue by joelklabo** [AzureAD/azure-activedirectory-library-for-objc#677]
When trying to login through 0365 nothing happens if the authenticator app is not installed. This used to send a text or phone call for the 2FA. 

Currently on Version 2.2.0

I see this in the log but nothing else:
-canOpenURL: failed for URL: "msauth://broker" - error: "(null)"

**Comment by joelklabo** [comment]
This also seems to be happening in 2.1.0

**Comment by jasoncoolmax** [comment]
@joelklabo Please refer to the readme here: https://github.com/AzureAD/azure-activedirectory-library-for-objc#brokered-authentication

**Comment by joelklabo** [comment]
We have been using ADAL login with the authenticator app with no problems for about a year. This is a new problem for us. If you didn't have the authenticator app you would get a text or a phone call. Now, we don't make it past the O365 login screen. We haven't changed any configuration.

**Comment by jasoncoolmax** [comment]
@joelklabo I will need the logs to take a detailed look. Please remember to set the logging level to ADAL_LOG_LEVEL_VERBOSE.

**Comment by RPangrle** [comment]
I think we're conflating brokered auth with MFA here. The authenticator covers both functions but ADAL is not directly involved in MFA, even when it does brokered auth.
