### ISSUE TITLE
Importing ADAL module results in build error (v 2.2.1)

### ISSUE THREAD

**Issue by eddiekim** [AzureAD/azure-activedirectory-library-for-objc#693]
I get build errors on v2.2.1 when semantically importing the ADAL module (`import ADAL`). This was fine in v2.2.0, and appears to be related to commit https://github.com/AzureAD/azure-activedirectory-library-for-objc/commit/91d7000b8c6eefc2846f700657c9bc624a2ecec0 . Seems that Xcode doesn't like that the same header files are made available by both the `ADALiOS` static library and `ADAL` framework by the same path.

![adal-module-error](https://cloud.githubusercontent.com/assets/1395025/16638139/af59f802-4399-11e6-884b-83d50aacef3a.png)

To reproduce in `MyTestiOSApp`:

* Remove `libADALiOS.a` from `Linked Frameworks and Libraries`
* Add `ADAL.framework` to `Embedded Binaries`
* Replace `#import <ADAL/ADAL.h>` with `@import ADAL;` in `ADTestAppDelegate.m`
* **Result**: `error: include of non-modular header inside framework module 'ADAL' `
* Workaround: go to `Build Phases` for `ADALiOS` static library and change `Copy Files` `Subpath` to something else (anything)
* Clear derived data and build again
* **Result**: Build success

**Comment by RPangrle** [comment]
Unfortunately that change was made so that applications only using the static libraries can import headers properly. The only way I can think around this is to not have the ADAL framework rely on the ADALiOS static lib

**Comment by eddiekim** [comment]
I think you will have more people who prefer framework to static libs going forward, so it's something to think about. As-is, it doesn't seem like you can use the `ADAL` framework unless you build it outside of the client project first (or make changes to the Xcode project)

This isn't really an issue for us anymore, so feel free to close.

**Comment by RPangrle** [comment]
I've done some work to mitigate this. The static lib build has been split into two libs, one that'll copy headers and one that won't. This way you'll be able to include the xcode project in your project and choose framework or static libs, you won't be able to do both though.
