### ISSUE TITLE
ADAL framework require iOS 9.2 ?

### ISSUE THREAD

**Issue by eddiekim** [AzureAD/azure-activedirectory-library-for-objc#694]
The ADAL framework target has a deployment target explicitly set to 9.2. Is that a requirement? Our app needs to support 8.0+

![adal-deployment-target](https://cloud.githubusercontent.com/assets/1395025/16664855/e6f065a6-4436-11e6-9db9-fdcdddff8f8c.png)

**Comment by RPangrle** [comment]
The static lib itself still has a deployment target of iOS 7 (even though our support policy says iOS 8)...
