### ISSUE TITLE
Add Telemetry feature

### ISSUE THREAD

**Issue by jasoncoolmax** [AzureAD/azure-activedirectory-library-for-objc#695]
High level goal is to enable reporting on AuthN experience, key scenarios 
1) too many login prompts, 
2) login failure,
3) slow performance.

**Comment by eddiekim** [comment]
Would a client be able to measure token refresh timing with this? Specifically, we need elapsed time for a network token refresh. If not, I can open a new issue to discuss.

**Comment by eddiekim** [comment]
> Would a client be able to measure token refresh timing with this? Specifically, we need elapsed time for a network token refresh. If not, I can open a new issue to discuss.

Should I create a new issue to discuss this?

**Comment by jasoncoolmax** [comment]
Sorry that I didn't notice that there is a question here :package: 

Yes, Telemetry does generate event for token refresh(with information like start time, end time, etc.)
