### ISSUE TITLE
ADAL 2.1.2: removeAllForUserId does not work on iOS 9.3.x and iPhone 5/5S

### ISSUE THREAD

**Issue by tbechtum** [AzureAD/azure-activedirectory-library-for-objc#705]
Hi,

while the latest ADAL 2.2.2 does not compile when integrated with CocoaPods 1.0.1 (/Pods/ADAL/ADAL/src/public/ADAL.h ADAL/ADAuthenticationContext.h file not found) in a Swift project I am using ADAL 2.1.2. To logout I used previously authContext.tokenCacheStore.removeAllWithError(&error) in the ADALiOS library. Now I planned to migrate to ADAL by using ADKeychainTokenCache()!.removeAllForUserId. On iPhone 6 the logout is working correctly and the Azure Login Web pages are appearing after calling authContext.acquireTokenWithResource(resourceId, clientId: clientId, redirectUri: redirectURL). On iPhone 5/5S the Azure Login Web pages do not appear (only for a short moment and flickering). Is this a issue about the animation for the login view or do I am using your library as requested?

Thanks for your help,
Thomas

**Comment by RPangrle** [comment]
You have cookies laying around still even after you call removeAllForUserId, make sure you clean up NSHTTPCookieStorage
