### ISSUE TITLE
ADTokenCacheItem's resource becoming nil after some time

### ISSUE THREAD

**Issue by mkarp** [AzureAD/azure-activedirectory-library-for-objc#707]
Hey everyone!

Is it an expected behaviour that `ADTokenCacheItem`'s resource becomes nil after some time? 

Here are the steps on how we're getting there: 

* Put a log operation in `ADTokenCacheItem`'s `- (id)initWithCoder:(NSCoder *)aDecoder` that prints the `_resource`.

* We sign in like this:

```objc
    self.aadContext = [ADAuthenticationContext authenticationContextWithAuthority:OurAADAuthority
                                                                validateAuthority:YES
                                                                            error:&error];
    ...
    [self.aadContext acquireTokenWithResource:OurAADResource
                                     clientId:OurAADClientID
                                  redirectUri:self.redirectURL
                               promptBehavior:AD_PROMPT_ALWAYS
                                       userId:nil
                         extraQueryParameters:nil
                              completionBlock:block];
```

* After signing in using ADAL, and then killing and reopening the app, the resource becomes present after second time querying the `ADTokenCacheItem` from `ADKeychainTokenCache`'s `-allItems`. Here's how the output looks like:

```
2016-07-29 09:33:35.675 Test[56202:1474270] ADAL version 2.2.2
2016-07-29 09:33:37.514 Test[56202:1474270] resource (null)
2016-07-29 09:33:37.522 Test[56202:1474270] resource <redacted>
2016-07-29 09:33:37.530 Test[56202:1474270] resource <redacted>
2016-07-29 09:33:37.721 Test[56202:1474270] resource <redacted>
2016-07-29 09:33:37.891 Test[56202:1474348] resource <redacted>
2016-07-29 09:33:37.907 Test[56202:1474348] resource <redacted>
2016-07-29 09:33:37.921 Test[56202:1474348] resource <redacted>
```

* If we kill the app and then reopen it after significant time has passed (lets say 24 hours), the output of this log operation becomes different. You can see I've set my system time to three days in the future:

```
2016-08-01 09:20:02.626 Test[55512:1457250] ADAL version 2.2.2
2016-08-01 09:20:05.948 Test[55512:1457250] resource (null)
2016-08-01 09:20:07.267 Test[55512:1457602] resource (null)
2016-08-01 09:20:08.611 Test[55512:1457250] resource (null)
2016-08-01 09:20:09.598 Test[55512:1457250] resource (null)
```

Some rationale for this:

To check whether a user is authenticated, we fetch all keychain items from ADAL. Then we iterate through all of the items and pick the one that matches our `authority`, `clientId` and `resource`. If it's present, we assume user is (or at least was) authenticated. After a significant time change, both `authority` and `clientId` are there, but `resource` is nil. 

I imagine we may be doing something wrong. If so, what are we doing wrong, and is there a better way to check whether a user is authenticated?

Thank you!

**Comment by mkarp** [comment]
Update: after a significant time change, we silently reauthenticate the user, and we have two keychain items: one with the access token and resource, and the other one with both of these being nil.

**Comment by RPangrle** [comment]
An ADTokenCacheItem with a 'nil' resource means that it is a Multi Resource Refresh Token.

**Comment by RPangrle** [comment]
And we recommend against crawling through the cache yourself unless you're looking for items to delete. Always use acquireToken or acquireTokenSilent, those APIs will return a cached token if available, or refresh the token for you.

**Comment by mkarp** [comment]
@RPangrle Thank you for the clarification! We'll stop crawling the keychain cache and probably replace it with a plain setting if user has logged in or not.
