### ISSUE TITLE
Utilise WKWebView to remove platform specific implementations

### ISSUE THREAD

**Issue by damienpontifex** [AzureAD/azure-activedirectory-library-for-objc#708]
The current web view for authentication uses platform specific web views of `WebView` and `UIWebView`. The latest framework `WKWebView` is available > iOS8.0 and > OSX 10.10 which also seems to match the requirements on this library as defined in the podsec.

Could the web views be migrated to use `WKWebView` to remove platform checks and simplify this section of the code?

**Comment by RPangrle** [comment]
WKWebView has issues with custom HTTP headers that would cause it to not work with ADAL.
