### ISSUE TITLE
Replace custom base64 implementation with built in methods

### ISSUE THREAD

**Issue by damienpontifex** [AzureAD/azure-activedirectory-library-for-objc#709]
The category `NSString(ADHelperMethods)` has some base64 en/decode helper methods for data and strings.

Since iOS7 and OS X 10.9, the SDK has had base 64 conversion built in with initialisers and methods on `NSData` and `NSString`. I'd be happy to swap out the appropriate pieces with a PR if you are happy for this to happen?

**Comment by RPangrle** [comment]
The built in methods do not do Base64URL encoding.
