### ISSUE TITLE
improve telemetry around NSURLErrorDomain

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-objc#716]
We need to be able to breakdown which request caused this error, 
How long did we wait
what was the error code.

**Comment by RPangrle** [comment]
NSURLSession metrics will get us a lot more information on this, but we'd need to switch to NSURLSession first. https://developer.apple.com/videos/play/wwdc2016/711/

**Comment by jasoncoolmax** [comment]
"which request caused this error"
"How long did we wait"
"what was the error code"

The above three pieces of info have already been captured by the telemetry http event in PR #706
