### ISSUE TITLE
Cannot sign-in/up with Facebook/Google on iOS 10

### ISSUE THREAD

**Issue by marchv** [AzureAD/azure-activedirectory-library-for-objc#717]
Hello there :)

We have successfully used ADAL iOS to sign-in/up using Facebook/Google accounts on iOS 9.x. But now **on iOS 10 betas it fails almost all the time** :S

ADAL now dumps below to the Xcode console when I touch the 'Facebook' or 'Google' button in our app:

    ERROR: authorization error. Additional Information: The operation was cancelled.. ErrorCode: 3072.
    ERROR: Error raised: 3072. Additional Information: Domain: NSCocoaErrorDomain Details: The operation was cancelled.. ErrorCode: 3072.

We are using *covergence-dev* branch (pulled June 15). To our understanding this branch is the one to use for Facebook/Google sign-up/in!? Maybe someone can give an overview of the different branches!?

Thanks :)

**Comment by marchv** [comment]
Hi @RPangrle :)

I've noticed you've made https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/713 on the 1.2.x branch.

I then applied the same changes to *convergence-dev* branch and it seemed to fix the issue! :D

Would it be possible for you make the same fix for the *convergence-dev/convergence* branches too? Or do like me to make a pull request?

Thanks!

Best regards Jens Schwarzer 8)

**Comment by RPangrle** [comment]
You're welcome to do that. Our current guidance is that the convergence versions of ADAL are experimental/preview only, in our sample apps for b2c we're using the NXOAuth2 library:

https://github.com/Azure-Samples/active-directory-ios-native-nxoauth2-b2c

**Comment by marchv** [comment]
Thanks for the reply! OK I understand. But to my understanding the convergence branch is the option if we like to sign-in with Facebook and Google right?

Will do pull request next week then :)

**Comment by RPangrle** [comment]
We highly recommend against shipping any product with an experimental library. There are other OAuth2 libraries (like NXOAuth2) that work with b2c that are not experimental.

**Comment by marchv** [comment]
@brandwe, I believe release 3.0.0-pre7 addresses the same issue? If yes, we can close this issue. Thanks a lot and have a nice weekend :)
