### ISSUE TITLE
Bug: AD_ERROR_TOKENBROKER_RESPONSE_NOT_RECEIVED

### ISSUE THREAD

**Issue by ogkent** [AzureAD/azure-activedirectory-library-for-objc#727]
When adding a corporate account to Outlook that requires MAM CA, if the Authenticator App has to register the device, when the user is returned to Outlook after registration you see a ‘Something went wrong’ screen.

This only happens when the Authenticator app has to register the device. Returning to Outlook from the Authenticator App when adding an account works correctly if the Authenticator App registered the device beforehand.

Here are the logs: [tokenbroker-response.txt](https://github.com/AzureAD/azure-activedirectory-library-for-objc/files/427572/tokenbroker-response.txt)

**Comment by jasoncoolmax** [comment]
This is already fixed. @ogkent you can test it using the latest Authenticator to confirm.

I am going close it. If you still see the error, please reopen the issue :)
