### ISSUE TITLE
Bug: AD_ERROR_TOKENBROKER_UNKNOWN

### ISSUE THREAD

**Issue by ogkent** [AzureAD/azure-activedirectory-library-for-objc#728]
To repro:
1. Install the Authenticator app (don't add your account)
2. Install Outlook and go through the conditional access flow. After you add your account, you'll be redirected back to Outlook with an `AD_ERROR_TOKENBROKER_UNKNOWN` error.

Here are the logs: [tokenbroker-unknown.txt](https://github.com/AzureAD/azure-activedirectory-library-for-objc/files/427617/tokenbroker-unknown.txt)

**Comment by partnerinflight** [comment]
fixed in latest Authenticator update.
