### ISSUE TITLE
SampleSwiftApp  dyld`dyld_fatal_error:

### ISSUE THREAD

**Issue by kohdesmond** [AzureAD/azure-activedirectory-library-for-objc#730]
Hi Mate,

i encountered this crash when i run the SampleSwiftApp on device.

error was:

**dyld: Library not loaded: @rpath/ADAL.framework/ADAL
  Referenced from: /var/containers/Bundle/Application/639571DF-571F-45DC-A4F0-3FC2A5B65C29/SampleSwiftApp.app/SampleSwiftApp
  Reason: image not found**

Weirdly simulator seems to work fine.

**Comment by RPangrle** [comment]
Yeah, the app target is missing the embedded binary. I'll be fixing that soon. Thanks for the report.

**Comment by kohdesmond** [comment]
Thanks!
