### ISSUE TITLE
how long does access token in cache expired for iOS when user changed password?

### ISSUE THREAD

**Issue by kohdesmond** [AzureAD/azure-activedirectory-library-for-objc#745]
Hi Guys,

I encountered a weird problem. 

I have no problem logging into ADAL

WITH  
`authContext.acquireTokenWithResource(resourceUrl, clientId: clientId, redirectUri: redirectUri, promptBehavior: AD_PROMPT_ALWAYS, userId: nil, extraQueryParameters: "nux=1&login_hint=desmondkoh@") `

AND

` authContext.acquireTokenSilentWithResource(resourceUrl, clientId: clientId, redirectUri: redirectUri)`

BUT

say if a user changed their password, I can still log into via `acquireTokenSilentWithResource`

so my question is 
How long does access token in cache expired for iOS when user changed password?

cheers

Des

**Comment by jasoncoolmax** [comment]
@kohdesmond Could you send such questions to stackoverflow, such that other people can benefit from it, be sure to use the ADAL tag :)

**Comment by kohdesmond** [comment]
@jasoncoolmax good call posted

[](http://stackoverflow.com/questions/39261347/after-user-changed-password-how-long-does-adals-cached-access-token-expired-fo)
