### ISSUE TITLE
Bug: Authenticator App does not pick up CA flow from Outlook when installed from app store

### ISSUE THREAD

**Issue by MaxLesMsft** [AzureAD/azure-activedirectory-library-for-objc#746]
If the user is prompted to install the Authenticator App for a Conditional Access flow, then installs and launches the Authenticator App from the App Store page, the Authenticator App does not pick up the ‘register device’ flow. Launching the Authenticator App brings you to the standard launch screen, rather than continuing with authentication that Outlook started.

Repro steps:
- Install Outlook, add account
- Outlook prompts to install Authenticator App
- Install Authenticator App from App Store. Click 'open' to launch Authenticator App

Expected: Authenticator App resumes authentication flow and finishes CA, then kicks back to Outlook
Actual: Authenticator App does not resume authentication flow, and prompts user for QR code

**Comment by RPangrle** [comment]
If you are using a dev or enterprise signed Outlook then it can't write pasteboards in a way that Authenticator can see and this won't work. Outlook and Authenticator have to be signed with the same cert.

**Comment by RPangrle** [comment]
This should be fixed with 2.3.0 as long as you're using builds at the same signing level.
