### ISSUE TITLE
App review rejection due to private API (dispatch:)

### ISSUE THREAD

**Issue by eddiekim** [AzureAD/azure-activedirectory-library-for-objc#776]
We just received notice from Apple that our app submission failed review because a private API `dispatch:` was used. We suspect that it's failing because of [ADDispatcher's similarly named method](https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/ADAL/src/telemetry/ADTelemetry.h#L40). We're patching/resubmitting now, and I'll follow back up to confirm if this is the issue or not once we've gone through review again.

-----

![screen shot 2016-09-15 at 3 48 57 pm](https://cloud.githubusercontent.com/assets/1395025/18570080/01ff9cd4-7b5c-11e6-9c07-bca2db51a449.png)

**Comment by RPangrle** [comment]
/facepalm

sigh.

**Comment by eddiekim** [comment]
Here is the PR: https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/777

Not sure if I based against the right branch, but the changes are simple to apply by hand if it's wrong.

**Comment by eddiekim** [comment]
Closing. https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/777 was merged.

Thanks!
