### ISSUE TITLE
ADALiOS update failure to 1.2.9 version

### ISSUE THREAD

**Issue by ajitkumar1** [AzureAD/azure-activedirectory-library-for-objc#781]
My native iOS app connects to office 365 through ADALiOS.
Currently is is using ADALiOS 1.2.4 and Office365 0.11.0.
With the new iOS 10 update the log in to office 365 is not working.
So ADAL is recommending to update the library to 1.2.9

Below is the pod file which i am using to update
`pod 'Office365', '~>0.11.0'
pod 'ADALiOS', '~>1.2.9'

target 'Compen10' do

end`

With this the 'pod update' command throwing below

> [!] Unable to satisfy the following requirements:

- `ADALiOS (~> 1.2.9)` required by `Podfile`
- `ADALiOS (~> 1.2.9)` required by `Podfile`
- `ADALiOS (= 1.2.4)` required by `orc (0.2.0)`

**Comment by RPangrle** [comment]
Please take this up with the Office 365 SDK team, this is not an ADAL issue.
