### ISSUE TITLE
Failing to fetch AD token

### ISSUE THREAD

**Issue by dimabs** [AzureAD/azure-activedirectory-library-for-objc#788]
2016/09/23 17:36:00:515  Failed to get AAD token, error: Error with code: 500 Domain: ADAuthenticationErrorDomain ProtocolCode:invalid_client Details:AADSTS70002: Error validating credentials. AADSTS50006: Signature verification failed. [Reason - The key was not found., Configured keys: [Key0:Start=01/01/0001, End=12/31/9999;]]

Trace ID: 62d15e06-c6b7-4e85-b17f-99a36e43a195

Correlation ID: 9307abd5-bab9-4668-936d-649953876205

Timestamp: 2016-09-24 00:36:00Z. Inner error details: Error Domain=ADAuthenticationErrorDomain Code=500 "(null)"
2016/09/23 17:36:00:515  Activation failed
2016/09/23 17:36:12:829  Application did enter background
2016/09/23 17:37:16:047  Application did enter background
2016/09/23 17:37:44:050  Application did finish launching (3.4.0.39)
2016/09/23 17:37:44:050  Tenant: Your company admin
2016/09/23 17:37:44:071  migrating FLXFIrstLaunch

2016/09/23 17:38:19:946  Failed to get AAD token, error: Error with code: 503 Domain: ADAuthenticationErrorDomain ProtocolCode:(null) Details:application did not receive response from broker.. Inner error details: Error Domain=ADAuthenticationErrorDomain Code=503 "(null)"
2016/09/23 17:38:19:947  Activation failed
2016/09/23 17:38:26:794  Application did enter background
2016/09/23 17:38:35:414  Tenant: Your company admin

2016/09/23 17:48:09:289  Failed to get AAD token, error: Error with code: 503 Domain: ADAuthenticationErrorDomain ProtocolCode:(null) Details:application did not receive response from broker.. Inner error details: Error Domain=ADAuthenticationErrorDomain Code=503 "(null)"
2016/09/23 17:48:09:294  Activation failed

**Comment by dimabs** [comment]
ADAL version 2.2.5

**Comment by RPangrle** [comment]
Is this the first authentication attempt after going through a device enrollment flow (the "register" button). Does it work on subsequent broker auth attempts?

**Comment by dimabs** [comment]
I don't have other authentications. I have single app. This is first attempt

**Comment by RPangrle** [comment]
There were issues fixed with the PRT flow, which the errors you have included indicate were involved. Please test this again with the most recent versions of ADAL and the Microsoft Authenticator app. If you are still seeing this please reopen the bug with complete logs from both your app and the Authenticator app. (https://github.com/AzureAD/azure-activedirectory-library-for-objc/wiki/Instructions-on-Collecting-Azure-Authenticator-Logs)
