### ISSUE TITLE
Fail to fetch token with ADAL version 2.2.6

### ISSUE THREAD

**Issue by dimabs** [AzureAD/azure-activedirectory-library-for-objc#789]
Sep 27 16:19:13 DimaDevPhone com.apple.xpc.launchd[1](com.apple.splashboard) <Notice>: Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -webAuthShouldStartLoadRequest:. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: +[ADURLProtocol canInitWithRequest:] handling host. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: +[ADURLProtocol canInitWithRequest:] handling host. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: +[ADURLProtocol canInitWithRequest:] handling host. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: +[ADURLProtocol canonicalRequestForRequest:]. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -[ADURLProtocol startLoading]. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -[ADURLProtocol connection:willSendRequest:]. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -[ADURLProtocol connection:willSendRequest:]. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: +[ADURLProtocol canInitWithRequest:] ignoring handling of host. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -webAuthShouldStartLoadRequest:. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: Handling PKeyAuth Challenge. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: Attempting to get registration information - . Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] INFORMATION: PKeyAuth: Received PKeyAuth request but no WPJ info.. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -[ADURLProtocol stopLoading]. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -webAuthShouldStartLoadRequest:. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: +[ADURLProtocol canInitWithRequest:] handling host. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: +[ADURLProtocol canInitWithRequest:] handling host. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: +[ADURLProtocol canInitWithRequest:] handling host. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: +[ADURLProtocol canonicalRequestForRequest:]. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -[ADURLProtocol startLoading]. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:17 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:17 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -[ADURLProtocol connection:willSendRequest:]. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:18 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:18 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -[ADURLProtocol stopLoading]. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:18 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:18 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: +[ADURLProtocol canInitWithRequest:] handling host. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:18 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:18 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: +[ADURLProtocol canonicalRequestForRequest:]. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:18 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:18 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -webAuthDidFinishLoad:. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:19 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:19 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: -webAuthShouldStartLoadRequest:. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:19 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:19 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] INFORMATION: -webAuthDidCompleteWithURL:. Additional Information: (null). ErrorCode: 0.
Sep 27 16:19:20 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:20 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] VERBOSE: ADNTLMHandler. Additional Information: NTLM session ended. ErrorCode: 0.
Sep 27 16:19:20 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:20 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] ERROR: Error raised: 15. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode: access_denied Details: The authentication server returned an error: access_denied.. ErrorCode: 15.
Sep 27 16:19:20 DimaDevPhone Microsoft Authenticator[513] <Warning>: ADALiOS [2016-09-27 23:19:20 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] ERROR: acquireToken failed.. Additional Information: (null). ErrorCode: 15.
Sep 27 16:19:20 DimaDevPhone SpringBoard[58] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Sep 27 16:19:20 DimaDevPhone enterprise[512] <Warning>: ADAL [2016-09-27 23:19:20 - 8E6B5172-A9CD-43DC-8A2F-DD9B83339892] ERROR: Error raised: (Domain: "ADAuthenticationErrorDomain" Code: 500 ProtocolCode: "access_denied" Details: "The authentication server returned an error: access_denied."
Sep 27 16:19:21 DimaDevPhone securityd[102] <Error>:  SecOCSPSingleResponseCreate OCSPResponse: single response has extension(s).
Sep 27 16:19:21 DimaDevPhone securityd[102] <Error>:  SecOCSPSingleResponseCreate OCSPResponse: single response has extension(s).
Sep 27 16:19:21 DimaDevPhone securityd[102] <Error>:  SecOCSPSingleResponseCreate OCSPResponse: single response has extension(s).

**Comment by RPangrle** [comment]
If the server is returning access_denied that usually is a problem with your tenant and/or application configuration, and not specific to ADAL.
