### ISSUE TITLE
ADAL Compile for cocoapods

### ISSUE THREAD

**Issue by ArEnSc** [AzureAD/azure-activedirectory-library-for-objc#791]
http://stackoverflow.com/questions/39774969/office-365-sdk-ios-cocoa-pod-does-not-work-angled-brackets-error-import-adau

**Comment by jasoncoolmax** [comment]
If you only keep pod 'ADAL', '~> 2.2' in your pod file, things work fine. So it is not an issue of ADAL cocoapods. I think it is the issue of other packages which use ADAL.

**Comment by ArEnSc** [comment]
I swore someone wrote something useful the other day looking for that email github .... , about this issue anyways yeah sure its not a ADAL problem, but the office 365 needs ADAL and cannot find its the header.

**Comment by RPangrle** [comment]
This is not a bug in ADAL.
