### ISSUE TITLE
Possible memory leaks

### ISSUE THREAD

**Issue by dtweston** [AzureAD/azure-activedirectory-library-for-objc#794]
Hello!

I was running my project in Xcode 8 and checking things out in the Visual Memory Debugger. There seemed to be a lot of leaks coming from this library. I had a quick look at making a pull request, but it seems like the code base is still supporting non-ARC compilers, and I didn't feel confident about making the required changes.

The biggest issue that I noticed in my project was [this code](https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/ADAL/src/request/ADWebAuthRequest.m#L84-L95) that passes a block which references `self` to [`-[ADWebRequest send:]`](https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/ADAL/src/request/ADWebRequest.m#L148-L159) which saves the block in a property on `self`.

**Comment by dtweston** [comment]
I updated the code I mentioned above to look like this:
```objc
    __weak typeof(self) weakSelf = self;
    [self send:^( NSError *error, ADWebResponse *webResponse )
    {
        __strong typeof(weakSelf) strongSelf = weakSelf;
        if (error)
        {
            [ADWebAuthResponse processError:error correlationId:strongSelf->_correlationId completion:completionBlock];
        }
        else
        {
            [ADWebAuthResponse processResponse:webResponse request:strongSelf completion:completionBlock];
        }
    }];
```

and that seems to fix it, but I'm not sure what the corresponding version would be for non-ARC.

**Comment by RPangrle** [comment]
This is typically required when 'self' also has a strong reference to the block in question (see: http://stackoverflow.com/questions/20030873/always-pass-weak-reference-of-self-into-block-in-arc) I don't see that in this case as it's an anonymous inline block being passed in.

**Comment by dtweston** [comment]
Yes, but if you look at the second link: `-send:` is implemented in the parent class ADWebRequest and stores the completion block in a property on `self`:

```objc
- (void)send:(void (^)(NSError *, ADWebResponse *))completionHandler
{
    SAFE_ARC_RELEASE(_completionHandler);
    _completionHandler = [completionHandler copy];
    
    SAFE_ARC_RELEASE(_response);
    _response          = nil;
    SAFE_ARC_RELEASE(_responseData);
    _responseData      = [[NSMutableData alloc] init];
    
    [self send];
}
```

Does that make sense?

**Comment by RPangrle** [comment]
I'm hesitant to make any change that on the face of it looks suspicious because of something the implementation of another method does. The right response here would be to break the retain cycle by having the parent class clear out _completionHandler once it has been hit.

**Comment by dtweston** [comment]
Yeah, I believe that will work too. It'll just be a short-lived retain cycle then.

**Comment by oldalton** [comment]
Fixed in dev
