### ISSUE TITLE
Does ADAL 2.2.6 support SSO via Comp Portal(Not Authenticator app)?

### ISSUE THREAD

**Issue by ddrdjboy** [AzureAD/azure-activedirectory-library-for-objc#813]
Hi,

Thank you for read this issue.
We are using ADAL 2.2.6 on my company's project. I found that ADAL SSO works via Comp Portal on Android Platform. I just want to confirm that if ADAL 2.2.6 on iOS has the same feature or not?

Thanks,
Sam

**Comment by RPangrle** [comment]
Company Portal does not act as an authentication broker on iOS.
