### ISSUE TITLE
Button login not work when keyboard showed.

### ISSUE THREAD

**Issue by thanhdonghuiit** [AzureAD/azure-activedirectory-library-for-objc#820]
![dd7b0918-a048-11e6-95ab-7263059a62ef copy](https://cloud.githubusercontent.com/assets/3241902/19892025/5fdfc732-a075-11e6-904c-3055678e1233.jpg)

At status keyboard showed, I click Sign in[button]. It only hides keyboard but doesn't sign in. I must touch again to sign in.
How can I make it work fine?

**Comment by RPangrle** [comment]
The behavior in the webview is dictated by the OS and out of our control.
