### ISSUE TITLE
AD_ERROR_TOKENBROKER_RESPONSE_NOT_RECEIVED when using Localytics together with Broker auth through ADAL

### ISSUE THREAD

**Issue by sadefigu** [AzureAD/azure-activedirectory-library-for-objc#821]
PROBLEM

When using Localytics library together with Adal, __swizzle_ApplicationOpenURL method never gets invoked from the Broker after authenticating with azure.

REPRO

1- Install ADAL and Localytics frameworks

2- At your AppDelegate, start Localytics 
    
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        Localytics.autoIntegrate("ENTER YOUR KEY HERE", launchOptions: launchOptions)
        return true
    }

3- Invoke acquire token using the Broker authentication

        let authContext = ADAuthenticationContext(authority: authorityURL, error: &er)
        
        authContext?.credentialsType = AD_CREDENTIALS_AUTO;
        
        authContext.acquireTokenWithResource(resourceID, clientId: clientID, redirectUri: redirectURI as NSURL!, userId:"") {
            (result) -> Void in
                guard let token = result?.accessToken else {
                print ("ERROR")
                return
            }
            print("SUCCESS accessToken: \(token)")
        } 

Expected Result
      The token should be retrieved.
Current result
      AD_ERROR_TOKENBROKER_RESPONSE_NOT_RECEIVED message is printed in the output.

INVESTIGATION

The problem seems to be that Localytics framework replaces the instance returned by SharedApplication Delegate to be LLAppDelegateProxy. The LLAppDelegateProxy has an attribute which is the delegate that contains the actual implementation that will be invoked.

The open url method is not implemented in this LLAppDelegateProxy proxy and will never be invoked. As a result, swizzling it with __swizzle_ApplicationOpenURLiOS9 has no effect.

Maybe the ADAL library could also allow API users to inject the appDelegate open url callback instead of trying to find out.

WORKAROUND
In order to bypass this problem, we can invoke handleBrokerResponseUrl directly from application open url in AppDelegate. Of course this can cause several problems and should not be a final solution.

    func application(app: UIApplication, openURL url: NSURL, options: [String : AnyObject]) -> Bool {
        
        if #available(iOS 9.0, *) {
            
            let sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey]

            if ADAuthenticationContext.isResponseFromBroker(String(sourceApplication!), response:url)
            {
                return ADAuthenticationContext.handleBrokerResponse(url);
            }
        }
        
        return true
    }

**Comment by sadefigu** [comment]
The fix for #872 would solve this problem.

**Comment by RPangrle** [comment]
The real issue here is that Localytics is not swizzling properly when they replace the entire Application's app delegate. Since a workaround exists we will close this issue. The usage of swizzling is currently under discussion.
