### ISSUE TITLE
_authenticationViewController does not nil out when webview timeout happens

### ISSUE THREAD

**Issue by jasoncoolmax** [AzureAD/azure-activedirectory-library-for-objc#828]
This will affect the authenticator SDK in the following way:

If `_authenticationViewController` does not nil out when webview timeout happens,
when the next time `invokeBroker` is being called, it will find that there is an ongoing web auth session going on (which is not true) and will wait for it to end forever.

**Comment by RPangrle** [comment]
I'm pretty sure this isn't authenticator specific.
