### ISSUE TITLE
Cannot log in on Verizon, due to phone call disconnecting network

### ISSUE THREAD

**Issue by joelklabo** [AzureAD/azure-activedirectory-library-for-objc#836]
Has this issue been raised before? We have some app review complaints that users can't log in on LTE because the 2 factor auth phone call kills the connection.

**Comment by RPangrle** [comment]
Yes, but there's not much we can do here on the ADAL side because it's unsafe to retry the connection afterwards (that causes other issues on a number of environments). If possible we recommend switching the 2FA to notifications.
