### ISSUE TITLE
Build error when using this importing "ADAL/ADAuthenticationContext.h"

### ISSUE THREAD

**Issue by faisalil** [AzureAD/azure-activedirectory-library-for-objc#861]
Hey,

I am following your documentation and trying to build my xcode project. So far, I am able to build the project fine before I import "ADAL/ADAuthenticationContext.h". The error I am getting is mainly ".../Pods/Headers/Public/ADAL/ADAL/ADAuthenticationContext.h:127:12: Unknown type name 'WebViewType'" 

A couple of question: 
1) Am I importing the right file? 
2) How can I fix this issue? 

Faisal

**Comment by faisalil** [comment]
More info : http://stackoverflow.com/questions/41274780/ios-project-build-failed-when-importing-adal-adauthenticationcontext-h

**Comment by RPangrle** [comment]
Have you tried importing via the umbrella header?

```#import <ADAL/ADAL.h>```

**Comment by tempestn** [comment]
FYI I was facing same issue and importing via umbrella header fixed for me. Would suggest updating the iOS quickstart docs: https://www.dropbox.com/s/y2e9bhin5rif6sg/Screenshot%202017-01-18%2015.34.43.png?dl=0

**Comment by himanthmaddi** [comment]
@faisalil did you solved this issue? I'm facing same issue and can't find solution. Help me if you found answer

**Comment by partnerinflight** [comment]
Closing this on the assumption that umbrella header fixes the issue. @xerners please update the Quickstart doc as described. @himanthmaddi please reactivate if you're still having the issue after using the umbrella header.

**Comment by xerners** [comment]
Will do.
