### ISSUE TITLE
Use iOS Facebook account to login.

### ISSUE THREAD

**Issue by micchyboy1023** [AzureAD/azure-activedirectory-library-for-objc#863]
Please integrate facebook account on iOS devices to login.

The origibal facebook sdk enables users to login their account integrated to the devices.

Users must login to Facebook again even if they already logged in.
It's bad user experience.

**Comment by RPangrle** [comment]
I assume you're talking about the experimental version of ADAL. It is unsupported and not recommended for production use. Our recommendation is to use the NXOAuth2 library instead.
