### ISSUE TITLE
Object Moved to Here message after logging in 

### ISSUE THREAD

**Issue by mhle** [AzureAD/azure-activedirectory-library-for-objc#873]
Hi, 

I'm using ADALiOS 1.2.8 via CocoaPods in a Swift 2 project. I can login fine with my Live account and get the token but after inputting my password and clicking sign in a white page is displayed with the text: "Object Moved to here". Clicking on the link in the text gets me back to the app and I get the token. 

Wondering if I'm doing anything wrong and how this page can be removed. 

Cheers, 

Michael

**Comment by partnerinflight** [comment]
@mhle is it possible to update to latest ADAL version? The one you're using is fairly old.

**Comment by RPangrle** [comment]
ADAL does not officially support MSA/Live ID, unless going through AAD as a guest account. Can you provide more information here about your exact usage?

**Comment by partnerinflight** [comment]
closing due to no resonse from originator.
