### ISSUE TITLE
Ability to disable close button of auth window

### ISSUE THREAD

**Issue by juturu** [AzureAD/azure-activedirectory-library-for-objc#909]
Is it possible to disable close button of auth window? We don't want the user cancel out the auth flow. 

We are using the default webview experience and not using setWebView method on auth context. To achieve this if we want to go the route of setWebView, then how do we handle when to show the window?

**Comment by jasoncoolmax** [comment]
When you do a non-silent call, show the webview; when the call returns, dimiss the webview.

**Comment by partnerinflight** [comment]
This is not a supported scenario. From a usability perspective, not allowing the user to cancel out of an action is a pretty severe usability dissat. Urge you to reconsider the approach.
