### ISSUE TITLE
Auto focus: When selecting user name text field, focus moves to the password field

### ISSUE THREAD

**Issue by jasohu** [AzureAD/azure-activedirectory-library-for-objc#912]
Steps:
1. When the ADAL web view shows up, click the user name field

Expected result:
Focus is on the user name field 

Actual result:
Focus moves to the password field

This reproduces on various devices and I cannot find a pattern to it:
Does not reproduce:
1. iphone 9.2.1
2. ipad 8.4.1
3. ipad 9.3.3
 
Reproduces:
1. iphone 9.2
2. iphone 8.3
3. iphone 10.2

The issue seems to be a javascript issue with the site.

Here's a video:
[FocusMovesToPasswordFieldVideo.zip](https://github.com/AzureAD/azure-activedirectory-library-for-objc/files/817604/FocusMovesToPasswordFieldVideo.zip)

**Comment by oldalton** [comment]
I believe this is not an issue anymore with new AAD sign in experience. Closing the issue.
