### ISSUE TITLE
AD Logger callback message contains user information (PII)

### ISSUE THREAD

**Issue by rushabh55** [AzureAD/azure-activedirectory-library-for-objc#924]
The message string in the AD Logger callback, as per the documentation should not contain PII.
We have seen PII coming from this message string. 
Here is the sample message string that contains this PII (edited out). 

> ADAL 2.2.7 iOS 10.3
ERROR: Error raised: (Domain: "ADAuthenticationErrorDomain" Code: AD_ERROR_TOKENBROKER_UNKNOWN ProtocolCode: "(null)" Details: "Different user was authenticated. Expected: '**[scrubbed]**'; Actual: '**[scrubbed]**'. Either the user entered credentials for different user, or cookie for different logged user is present. Consider calling acquireToken with AD_PROMPT_ALWAYS to ignore the cookie."

```

/*!
    The LogCallback block for the ADAL logger
 
    @param  logLevel        The level of the log message
    @param  message         A short log message describing the event that occurred, this string will not contain PII.
    @param  additionalInfo  A longer message that may contain PII and other details relevant to the event.
    @param  errorCode       An integer error code if the log message is an error.
    @param  userInfo        A dictionary with other information relevant to the log message. The information varies,
                            for most error messages the error object will be in the "error" key.
 */
typedef void (^LogCallback)(ADAL_LOG_LEVEL logLevel,
                            NSString *message,
                            NSString *additionalInfo,
                            NSInteger errorCode,
                            NSDictionary *userInfo);


```

**Comment by RPangrle** [comment]
This string is coming over from the broker, can you take a look at it @jasoncoolmax ?

**Comment by sdabbiru** [comment]
Why is this a problem? This is not automatically collected by telemetry, and besides this is useful information for troubleshooting.

**Comment by rushabh55** [comment]
It a problem because the documentation says its supposed to be free of PII, and its **not**. So other app developers using this library would send this string across their telemetry pipeline storing PII data. 

The documentation has to be accurate. And also if there are no fields out there that are _really_ PII free, developers can't log anything to their telemetry pipelines, making it harder for them to understand what's going wrong and be able to debug any failures. 

If this information is useful for debugging, why can't it be a part of additional info which may already have the PII? 

```
@param  message         A short log message describing the event that occurred, this string will not contain PII.
@param  additionalInfo  A longer message that may contain PII and other details relevant to the event.
```

**Comment by jasoncoolmax** [comment]
The message was sent by Microsoft Authenticator app.
AFAIK, the Authenticator app won't send the PII in that message since ver 5.2.3.

**Comment by partnerinflight** [comment]
@jasoncoolmax verified this is not returned in latest Authenticator version.
