### ISSUE TITLE
Outlook iOS Unable to Signin after using for some time

### ISSUE THREAD

**Issue by Sudarshanshetty** [AzureAD/azure-activedirectory-library-for-objc#928]
I am unable sign in after using application for some time. If we reset the device and retry to signin , It works without any issue. What could be the problem ?

Using below Pods: -

pod 'Office365' pod 'ADALiOS', '~> 1.2.2'

**Comment by partnerinflight** [comment]
This is a very old ADAL version. @Sudarshanshetty: can you guys update to the latest?

**Comment by partnerinflight** [comment]
closing per no response from originator.
