### ISSUE TITLE
Can't build with warnings as errors

### ISSUE THREAD

**Issue by dalemy** [AzureAD/azure-activedirectory-library-for-objc#929]
`ADKeychainTokenCache.h` has a nullability specifier of `nullable` on its `init` method. Since this object inherits from `NSObject`, `init` must return a non-null value. This causes Xcode to generate a warning, and when projects have "warnings as errors" turned on, they can't be built.

**Comment by dancrevier** [comment]
Specifically we get this with Swift. We're seeing the problem too.

**Comment by RPangrle** [comment]
@oldalton Can you take a look at adding warnings-as-errors into our swift sample app to ensure that we don't run into such problems again?

**Comment by partnerinflight** [comment]
fixed in 2.5.0
