### ISSUE TITLE
Can't login into OneDrive for Business

### ISSUE THREAD

**Issue by Faradei** [AzureAD/azure-activedirectory-library-for-objc#930]
Hello!
Our team has several released apps which are using OneDrive for Business. All things works fine but recently we found that OneDrive integration is broken. After investigation I've found that we receive such error after login:
 
**Error raised: 15. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode:invalid_resource Details:AADSTS50001: Resource 'https://api.office.com/discovery/' is disabled.**

If there any ideas what it could be? I'll be appreciated for any help

**Comment by RPangrle** [comment]
Please send questions to StackOverflow.
