### ISSUE TITLE
Using CocoaPods integration for macOS fails to compile

### ISSUE THREAD

**Issue by macblazer** [AzureAD/azure-activedirectory-library-for-objc#945]
When using CocoaPods to pull in the dev branch ADAL to a macOS project (using "pod 'ADAL', :git => 'https://github.com/AzureAD/azure-activedirectory-library-for-objc.git', :branch => 'dev'"
), the project will not compile because it is missing the ADRegistrationInformation class. The ADRegistrationInformation.h file is present in the ADAL/src/workplacejoin folder.  There is a .m file in ADAL/src/workplacejoin/ios but no corresponding .m file in the ADAL/src/workplacejoin/mac folder.

Should the .m file be pulled out of the ios folder, or is there some other behavior that's needed but not coded for macOS?

**Comment by partnerinflight** [comment]
Resolved offline. Issue was that the config was pointing at dev head, which we don't support. Only building off tagged releases is supported.
