### ISSUE TITLE
How do we get token expiry and logged in user information from the same result of what we are getting access token?

### ISSUE THREAD

**Issue by ramprasad1477** [AzureAD/azure-activedirectory-library-for-objc#954]
Hi, 

I am getting access token using same sample code given in this article..but my requirement is also to get the token expiry and logged in user information like display Id, email..

Can you please help me regarding this..Thanks..

**Comment by oldalton** [comment]
Please use:
result.tokenCacheItem.userInformation for user information (see ADUserInformation.h header for fields) 
result.tokenCacheItem.expiresOn for the access token expiry date
