### ISSUE TITLE
Allow clients to set a custom UserAgent for the HTTP(S) requests

### ISSUE THREAD

**Issue by clausjoergensen** [AzureAD/azure-activedirectory-library-for-objc#960]
To allow customers to enable/disable specific functionality, such as Windows Integrated Auth (WIA), we would like ADAL to allow the clients using the library to be allowed to specify a custom UserAgent, so customers can disable explicit functionality for Mac clients.

ADAL on Mac today uses the standard Safari UserAgent, which prevents customers from disabling certainly functionality (such as WIA) for clients using ADAL without also breaking Safari.

Ideally ADAL would take a UserAgent from the client, and use it for all subsequent HTTP(S) requests as necessary.

**Comment by xerners** [comment]
Assigning to @partnerinflight for triage.

**Comment by partnerinflight** [comment]
WIA is not currently supported by the Objc-C libraries. Making a change like the one proposed for one platform but not another doesn't make a whole lot of sense. Rejecting this enhancement request for now; please reactivate/escalate if the change can be supported with strong customer need.
