### ISSUE TITLE
Acquiring token without webview

### ISSUE THREAD

**Issue by mattgallivan** [AzureAD/azure-activedirectory-library-for-objc#961]
Is there any way to retrieve a token without using the WebView sign in? (ie. sending a username and password through the context.acquireToken(...))

**Comment by oldalton** [comment]
Unfortunately it's not possible with this library. To retrieve the token first time you'll need to do the web view sign in. If you already collected the username in your app, you can provide it as a userId parameter in the acquireToken call.

**Comment by mattgallivan** [comment]
@oldalton Thank you!

**Comment by TeddyCodeDev** [comment]
@oldalton Are there any plans to implement this? It'd be nice to be able to make an app seamless without the deviation to the webView which doesn't match my UI

**Comment by aminemzid** [comment]
Hello,
Same question that @oldalton
