### ISSUE TITLE
Microsoft teams : ADAL Mac 2.5 issue : User is not able to pass through the remediation page after completing the enrollment process

### ISSUE THREAD

**Issue by AndroidTeamsUSer** [AzureAD/azure-activedirectory-library-for-objc#963]
Configuration: 
Test was carried on a dev build for Teams which has ADAL v 2.5 library integrated. We can provide this build to you if you want to use it for debugging. Let us know..
 
Repro Steps
1)Login to team App(Mac desktop App) with Device compliance required  Policy user (Nisha@mcat1.onmicrosoft.com/P@ssw0rd!)
2)Remediation Page with Enroll option shows up
3)Clicking on Enroll takes the user to site where they can download and install company portal.
4)Installed the company portal and Enrolled device with the user mentioned above.
5)Then launched the teams App again
 
Actual
The remediation page still shows up with Enroll option even after the device is enrolled and user have no clue how get through the screen 
User can login in to Teams only after he quit and re launch the App and Login again. This is NOT a good user experience . 
 
Expected
User should be able to login to teams when he tries to access the teams after the device enrollment is completed.

**Comment by partnerinflight** [comment]
this is something that needs to be fixed in STS. We have no control of what's happening inside the WebView. Please follow up offline to engage on this.
