### ISSUE TITLE
SampleSwiftApp does not build

### ISSUE THREAD

**Issue by olavt** [AzureAD/azure-activedirectory-library-for-objc#964]
I downloaded the repo, copied the SampleSwift app, did a "pod init" and added "pod 'ADAL'" to the Podfile and did a "pod installed". Then I opened the workspace in Xcode 8.3.2. I'm getting an hard error like this: 

"/Users/olavt/Projects/SampleSwiftApp/Pods/ADAL/ADAL/src/public/ios/ADKeychainTokenCache.h:61:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'"

and lots of warning like this:

"/Users/olavt/Projects/SampleSwiftApp/Pods/ADAL/ADAL/src/request/ADDrsDiscoveryRequest.h:43:3: '@param' command used in a comment that is not attached to a function declaration"

**Comment by oldalton** [comment]
This issue has been already addressed (please see https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/962), but the version with the fix hasn't been released yet.
