### ISSUE TITLE
Token cache schema version changes break SSO between apps.

### ISSUE THREAD

**Issue by githubursul** [AzureAD/azure-activedirectory-library-for-objc#966]
Send me the link when you've submitted it. Thanks.
________________________________________
From: Brandon Werner
Sent: Tuesday, May 9, 2017 11:17:51 AM
To: Alexey Ursulenko; Olga Dalton; Ryan Pangrle; Eugene Polonsky; Shane Chism
Cc: Kundan Bharti
Subject: Re: ADAL/iOS cache schema versioning 
 
Hi @Alexey Ursulenko - great feature request. Can you put in GitHub issues though so we can triage it?

@Eugene Polonsky as well.

As context for the iOS team - the Office team are making a product called "OneAuth" that is trying to create a unification layer for Office above ADAL. This is one of the issues that the team is looking at that is making them consider writing their own implementation vs. using ADAL. There should be a few of these being logged as issues as I work with the team and @Shane Chism to see what they need to use ADAL.
________________________________________
From: Alexey Ursulenko
Sent: Tuesday, May 9, 2017 10:25:50 AM
To: Olga Dalton; Ryan Pangrle; Brandon Werner
Cc: Kundan Bharti
Subject: ADAL/iOS cache schema versioning 
 
Hi Olga/Ryan/Brandon,

I have a question about ADAL for iOS implementation, and you guys seem to be among the top contributors. Judging the error codes in ADError.h ADAL for iOS may be subject to the cache versioning issue, similar to that of ADAL for Win32. Namely, if cache schema version changes, and app A updates, then app B that has not been updated yet will not be able to SSO with app A. Is my understanding correct? 

We are developing authentication stack for Office iOS that uses ADAL. Our partner, OneDrive in particular, are very interested to onboard and have SSO with Office. However, the update model for OneDrive eliminates a possibility that they can use the same ADAL binary as Office. So if the answer to my question above is positive, we need to look for a possibility of re-implementing ADAL cache in a forward-compatible way. Would this be a feature request that your team could take?

Thank you,
Alexey

**Comment by RPangrle** [comment]
There's never been a token cache schema version change in ADAL for ObjC. We've added fields to the scheme, however none of those have been breaking changes that have required us to increase the version number on our cache.

**Comment by partnerinflight** [comment]
@brandwe it's not unreasonable to settle on a versioning scheme; we're working through the scheme in adal C++ context, and will talk about whether to pick this up for adal objc.

**Comment by githubursul** [comment]
+ @Kundan Bharti<mailto:Kundan.bharti@microsoft.com>

**Comment by oldalton** [comment]
Closing, as it's not an issue for ObjC SDK.
