### ISSUE TITLE
Add an Swift app example using AAD

### ISSUE THREAD

**Issue by greathansen** [AzureAD/azure-activedirectory-library-for-objc#97]
Could you provide and example off a swift app using the existing AAD library?

regards,
Gustavo

**Comment by nimatra** [comment]
Please don't won't fix these requests. Every ADAL newbie needs to go through the same path. Just one simple example would actually benefit ADAL team more. 
We (startup devs) would just change our mind and use Google/FB instead of ADAL if it's hard to use.

**Comment by RandalliLama** [comment]
@nimatra I'll reopen this.  We have nothing against Swift, we are just swamped right now.  We would happily accept a community contribution if you have one.

**Comment by nimatra** [comment]
I started learning/doing Swift and AD B2C yesterday. I'll happily post a sample as soon as I get my AD running on iPhone.

**Comment by RandalliLama** [comment]
@nimatra Got it.  Did you happen to look at the sample I posted above?  It's not pretty, but it was relatively simple to get it working.  Note that the sample was done with an earlier version of Swift.

May I also suggest posting a question to StackOverflow to see if anyone else has already done this?

**Comment by nimatra** [comment]
I found some clues on SO and bridge header helps.
Generally, having a working sample project that I can just replace the AD info with mine from my other apps and see it working on iOS helps a ton.

**Comment by tsteele2013** [comment]
Is a working Swift example still needed?

**Comment by OceanOSdev** [comment]
A working swift example would be much appreciated.

**Comment by tsteele2013** [comment]
Inside my AuthManager class is the following:


    let tenant:String = "TENANT.onmicrosoft.com"
    let authority:String = "https://login.windows.net/TENANT.onmicrosoft.com"
    let clientID:String = "YOUR CLIENT ID"
    let resourceURI:String = "YOUR RESOURCE URI"
    let redirectURI:NSURL = NSURL(string:"YOUR REDIRECT URI")!
    var loggedIn: Bool = false
    // Create a singleton instance of the AuthManager class. The app uses this instance for all operations.
    class var sharedInstance: AuthManager {
        struct Singleton {
            static let instance = AuthManager()
        }
        return Singleton.instance
    }
    
    func login(completionBlock:((Bool, String) -> Void)) {
                var er:ADAuthenticationError? = nil
        let authContext = ADAuthenticationContext(authority: authority, error: &er)
        var token: String!
        authContext.acquireTokenWithResource(resourceURI, clientId: clientID, redirectUri: redirectURI, userId: NSUserDefaults.standardUserDefaults().stringForKey("username")) {
            (result: ADAuthenticationResult!) -> Void in
            if result.status.rawValue != AD_SUCCEEDED.rawValue {
                completionBlock(false, result.error.description)
            } else {
                token = result.accessToken
                let username = result.tokenCacheStoreItem.userInformation.userId
                print(username)
                completionBlock(true, token)
            }
        }
        
    }
    
    func logout() {
        loggedIn = false
        var error: ADAuthenticationError?
        let cache: ADTokenCacheStoring = ADAuthenticationSettings.sharedInstance().defaultTokenCacheStore
        
        // Clear the token cache. This is where the last user is stored.
        let allItemsArray = cache.allItemsWithError(&error)
        if (!allItemsArray.isEmpty) {
            cache.removeAllWithError(&error)
        }
        
        // Remove all the cookies from this application's sandbox. The authorization code is stored in the cookies and ADAL will try to get to access tokens based on auth code in the cookie.
        let cookieStore = NSHTTPCookieStorage.sharedHTTPCookieStorage()
        if let cookies = cookieStore.cookies {
            for cookie in cookies {
                cookieStore.deleteCookie(cookie)
            }
        }
    }


Inside my view controller, I execute the following on viewDidLoad:

```
        let authManager = AuthManager.sharedInstance
        if authManager.loggedIn == false {
            authManager.login() {
                (authenticated: Bool, token: String) -> Void in
                if (authenticated) {
                    self.setupMapView()
                    self.authManager.loggedIn = true
                    self.getJSON()
                } else {
                    print("Authentication Failed!")
                    self.authManager.loggedIn = false
                    self.loginToolbar.alpha = 1.0
                    self.listButton.enabled = false
                    self.filterButton.enabled = false
                }
            }
        } else if authManager.loggedIn == true {
            setupMapView()
            getJSON()
        }
```

I added the loggedIn variable myself, not entirely sure if it adds any value, but I didn't want to take chances. Also, this only works when I use the "ADALiOS" CocoaPod, I haven't the slightest idea why. Hope this helps!

**Comment by tsteele2013** [comment]
Alas, with the release of Swift 3.0, the example I provided above no longer works. Should this be reopened?

**Comment by DianaD96** [comment]
That would be greatly appreciated!

**Comment by osca2000** [comment]
Can you update your swift sample and make it work again? Newbies like me all are chasing Swift not Object-C.

**Comment by tsteele2013** [comment]
@osca2000 The logout method was the only thing broken by Swift 3 I believe. Here's the current implementation I have. Let me know if you have any other questions.

```
func login(_ completionBlock:@escaping ((Bool, String) -> Void)) {
                var er:ADAuthenticationError? = nil
        let authContext = ADAuthenticationContext(authority: authority, error: &er)
        
        var token: String!
        authContext?.acquireToken(withResource: "https://graph.windows.net", clientId: clientID, redirectUri: redirectURI) {
            (result) -> Void in
            if result?.status.rawValue != AD_SUCCEEDED.rawValue {
                completionBlock(false, (result?.error.description)!)
            } else {
                token = result?.accessToken
                let username = result?.tokenCacheStoreItem.userInformation.userId
                self.storeUsername(username!)
                completionBlock(true, token)
            }
        }
    }
```

**Comment by IsuruRanasinghe** [comment]
Hi @tsteele2013 ,
we have custom b2c policy for our application (including facebook). I can not see any place to add b2c policy in any example. Do you have any idea how to add policy to ADAL?

**Comment by tsteele2013** [comment]
@IsuruRanasinghe Unfortunately not... Although I'm sure it's possible. I may look into this if I have some free time.

**Comment by jenasubodh** [comment]
Wrote a Swift Implementation of the same app. Hope it helps
https://github.com/jenasubodh/azuread-ios-swift
