### ISSUE TITLE
-[ADAuthenticationContext acquireTokenForAssertion:assertionType:resource:clientId:userId:completionBlock:] is required to be non-silent API

### ISSUE THREAD

**Issue by yozho** [AzureAD/azure-activedirectory-library-for-objc#972]
We have a scenario to get access token for invited MSA, when call this API -[ADAuthenticationContext acquireTokenForAssertion:assertionType:resource:clientId:userId:completionBlock:] with SALM token, it always failed with error AD_ERROR_UI_NOT_ON_MAIN_THREAD. 

During our investigation, seems it won't trigger Authentication UI prompt, is it necessary to put it in non-silent mode? I modified the SDK and tried to add  [request setSilent:YES]; in 
- (void)acquireTokenForAssertion:(NSString*)assertion
                   assertionType:(ADAssertionType)assertionType
                        resource:(NSString*)resource
                        clientId:(NSString*)clientId
                          userId:(NSString*)userId
                 completionBlock:(ADAuthenticationCallback)completionBlock

It works fine, is there some consideration to make it non-silent API? Thanks.

**Comment by partnerinflight** [comment]
@yozho I think the error should indicate exactly what needs to be done. Are you calling acquireTokenForAssertion on the main thread of your app?

**Comment by RPangrle** [comment]
Despite the name, it legitimately is a silent API, so it shouldn't require being on the main thread.
