### ISSUE TITLE
iOS-Keychain does not persist aad token from acquire token call with non-default keychain sharing group

### ISSUE THREAD

**Issue by shws** [AzureAD/azure-activedirectory-library-for-objc#982]
When a acquiretokenwithresource call is made with a specified cache other than the default adal cache (com.microsoft.adalcache) the aad token acquired does not persist in the specified cache. However, if this custom cache is set to default at the time of app initialization data persists on the keychain in the custom cache group.

**Comment by oldalton** [comment]
Hi. Thank you for reporting this issue. Just double-checking that I understood your issue correctly. Are you trying to use this API and providing a different sharedGroup parameter?

```
- (id)initWithAuthority:(NSString *)authority
      validateAuthority:(BOOL)validateAuthority
            sharedGroup:(NSString *)sharedGroup
                  error:(ADAuthenticationError * __autoreleasing *)error;
```
Thanks a lot.

**Comment by oldalton** [comment]
Closing per no response from originator and not being to reproduce. 
@shws Please re-open this issue if you're still facing it and please provide additional information requested. Thanks!
