### ISSUE TITLE
acquireTokenSilent failing to retrieve keychain values

### ISSUE THREAD

**Issue by jaragones** [AzureAD/azure-activedirectory-library-for-objc#983]
I'm using ADAL library on an iOS project (pod 'ADAL', '~> 2.2') to acquire a token to interact with Microsoft work accounts. First call that I do to get token is:

```
ADAuthenticationError* error = nil;
ADAuthenticationContext* context = [[ADAuthenticationContext alloc] initWithAuthority:authority
                                                              validateAuthority:validateAuthority
                                                                                error:&error];
[context setCredentialsType:credType];    
[context acquireTokenWithResource:resource
                         clientId:clientId
                      redirectUri:redirectUri
                   promptBehavior:AD_PROMPT_AUTO
                   userIdentifier:nil
             extraQueryParameters:@"scope=https%3A%2F%2Fgraph.microsoft.com%2Fmail.read%20https%3A%2F%2Fgraph.microsoft.com%2Fmail.readwrite%20https%3A%2F%2Fgraph.microsoft.com%2Fmail.send"
                  completionBlock:^(ADAuthenticationResult *result)
 {
    // source code
 }];
```

response is as expected, and I get a token to interact with server. If I execute next lines (once previous block is completed, and in same execution of the app), I get a AD_SUCCEEDED as response.

```
ADAuthenticationError* error = nil;
ADAuthenticationContext* context = [[ADAuthenticationContext alloc] initWithAuthority:authority validateAuthority:validateAuthority error:&error];
[context acquireTokenSilentWithResource:resource clientId:clientId redirectUri:redirectUri userId:identifier.userId completionBlock:^(ADAuthenticationResult *result)
 {
     // source code
 }];
```
But the weird behaviour is when I stopped the app and start it again. If I call same code to acquireTokenSilentWithResource, results is AD_FAILED.

In theory, "sessions" should be stored on keychain, right?. I have my capabilities switch on, and I have a group called "com.microsoft.adalcache". I wonder what's going on. Once first login is done I can do (next lines) and I get two items as expected. If I restart application, I don't get any items (always empty).

```
ADKeychainTokenCache *keychain = [ADKeychainTokenCache defaultKeychainCache];
for (ADTokenCacheItem *item in [keychain allItems:nil]) {
    NSLog(@"%@", item.description);
}
```

Any hint that could help? Seems that works till I stop the app/simulator and start it again.

**Comment by sanalraju** [comment]
what was the issue? was it resolved ?

**Comment by jaragones** [comment]
If I don't recall wrong, I went for a workaround. I cannot be more precise, bug from 3 years ago.
