### ISSUE TITLE
Using ADErrorCodes enum values in 64-bit Swift causes a compilation error

### ISSUE THREAD

**Issue by macblazer** [AzureAD/azure-activedirectory-library-for-objc#984]
I am using the ADAL code (release 2.4.1) in a Swift project.  When trying to detect a specific error code, I get an error that

"Binary operator '==' cannot be applied to operands of type 'Int' and 'Int32'"

on the line "authenticationError.code == AD_ERROR_DEVELOPER_INVALID_ARGUMENT.rawValue" below.

```
func process(authenticationError: ADAuthenticationError) {
    if authenticationError.domain == ADAuthenticationErrorDomain
        && authenticationError.code == AD_ERROR_DEVELOPER_INVALID_ARGUMENT.rawValue {
        print("Invalid authority specified")
    }
}
```

If I change ADErrorCodes.h to use the NS_ENUM(NSInteger, <typename>) macro instead of the simple "typedef enum { ... } <typename>;" then the error codes convert to Swift in a nicer manner and are either 32-bit or 64-bit integers depending on the compilation platform.

I can submit a pull request with this change (using NS_ENUM macro), if it is acceptable to the maintainers.

**Comment by RPangrle** [comment]
We'd be happy to accept that PR.

**Comment by oldalton** [comment]
Fixed in dev.
