### ISSUE TITLE
Why Company Portal  is not acts as Authentication Broker?

### ISSUE THREAD

**Issue by Durgaprasad-Budhwani** [AzureAD/azure-activedirectory-library-for-objc#991]
Hi Team,

In Android,  ADALSSO works via Comp Portal but in iOS, it works via Microsoft Authentication.
Microsoft Authentication forces users for Multi-factor authentication (MFA) but not Company Portal does not.  This will force the user to go with MFA for the iOS application. Once MFA is enabled, it will force user for the verification code.
So overall behavior from a user point of view will not consistent.
Do you have any plan to do SSO via Company Portal for iOS app?

**Comment by Durgaprasad-Budhwani** [comment]
Any update on this issue?

**Comment by RPangrle** [comment]
The way IPC works on iOS means in practice we can only have one authentication broker, so we use the Authenticator app.
