### ISSUE TITLE
validBrokerRedirectUri should do a case insensitive comparison of host and scheme

### ISSUE THREAD

**Issue by dianambb** [AzureAD/azure-activedirectory-library-for-objc#995]
In ADAuthenticationRequest+Broker.m > validBrokerRedirectUri ,

if (![host isEqualToString:bundleId]) - this comparison should be case insensitive. The same goes for scheme.

**Comment by antrix1989** [comment]
Server doesn't allow case insensitive comparison. It returns AD_ERROR_TOKEN_BROKEN_INVALID_REDIRECT_URI. Closing it, feel free to reopen it if necessary.
